// packages/react/src/primitives/gradient-editor/GradientEditorRoot.tsx
import React, { type ReactNode } from 'react'

import type { Fill } from '@openweave/scene-graph'

import { useGradientStops } from './useGradientStops'

export interface GradientEditorRootProps {
  fill: Fill
  onUpdate?: (fill: Fill) => void
  children?: ReactNode | ((props: any) => ReactNode)
}

export function GradientEditorRoot({ fill, onUpdate, children }: GradientEditorRootProps) {
  const {
    activeStopIndex,
    stops,
    subtype,
    subtypes,
    activeColor,
    barBackground,
    setSubtype,
    selectStop,
    addStop,
    removeStop,
    updateStopPosition,
    updateStopColor,
    updateStopOpacity,
    updateActiveColor,
    dragStop
  } = useGradientStops(fill, (updated) => onUpdate?.(updated))

  const actions = {
    setSubtype,
    selectStop,
    addStop,
    removeStop,
    updateStopPosition,
    updateStopColor,
    updateStopOpacity,
    updateActiveColor,
    dragStop
  }

  const renderedChildren =
    typeof children === 'function'
      ? children({
          stops,
          subtype,
          subtypes,
          activeStopIndex,
          activeColor,
          barBackground,
          actions
        })
      : children

  return <>{renderedChildren}</>
}

export default GradientEditorRoot

// packages/vue/src/primitives/GradientEditor/GradientEditorRoot.vue
<script setup lang="ts">
import { computed } from 'vue'

import { useGradientStops } from '#vue/primitives/GradientEditor/useGradientStops'

import type { Fill } from '@openweave/scene-graph'

const { fill } = defineProps<{ fill: Fill }>()
const emit = defineEmits<{ update: [fill: Fill] }>()

const {
  activeStopIndex,
  stops,
  subtype,
  subtypes,
  activeColor,
  barBackground,
  setSubtype,
  selectStop,
  addStop,
  removeStop,
  updateStopPosition,
  updateStopColor,
  updateStopOpacity,
  updateActiveColor,
  dragStop
} = useGradientStops(
  computed(() => fill),
  (updated) => emit('update', updated)
)

const actions = {
  setSubtype,
  selectStop,
  addStop,
  removeStop,
  updateStopPosition,
  updateStopColor,
  updateStopOpacity,
  updateActiveColor,
  dragStop
}
</script>

<template>
  <slot
    :stops="stops"
    :subtype="subtype"
    :subtypes="subtypes"
    :active-stop-index="activeStopIndex"
    :active-color="activeColor"
    :bar-background="barBackground"
    :actions="actions"
  />
</template>
