// packages/react/src/primitives/toolbar/ToolbarItem.tsx
import { useToolbar } from '#react/primitives/toolbar/context'
import React, { useMemo } from 'react'

import type { Tool } from '@openweave/core/editor'

export interface ToolbarItemSlotProps {
  active: boolean
  tool: Tool
  actions: {
    select: () => void
  }
}

export interface ToolbarItemProps {
  tool: Tool
  children?: React.ReactNode | ((props: ToolbarItemSlotProps) => React.ReactNode)
}

export function ToolbarItem({ tool, children }: ToolbarItemProps) {
  const { activeTool, setTool } = useToolbar()

  const isActive = activeTool === tool

  const actions = useMemo(
    () => ({
      select: () => setTool(tool)
    }),
    [setTool, tool]
  )

  const renderedChildren =
    typeof children === 'function'
      ? children({
          active: isActive,
          tool,
          actions
        })
      : children

  return <>{renderedChildren}</>
}

export default ToolbarItem

// packages/vue/src/primitives/Toolbar/ToolbarItem.vue
<script setup lang="ts">
import { computed } from 'vue'

import { useToolbar } from '#vue/primitives/Toolbar/context'

import type { Tool } from '@openweave/core/editor'

const { tool } = defineProps<{
  tool: Tool
}>()

const { activeTool, setTool } = useToolbar()

const isActive = computed(() => activeTool.value === tool)
const actions = {
  select: () => setTool(tool)
}
</script>

<template>
  <slot :active="isActive" :actions="actions" :tool="tool" />
</template>
