// src/components/color-picker-panel/HsbFields.vue
<script setup lang="ts">
import { inputNumberValue } from '@openweave/vue'
import { colorToCSS } from '@openweave/core/color'

import StandardColorSlider from '@/components/color-picker-panel/StandardColorSlider.vue'
import { useColorPickerPanelContext } from '@/components/color-picker-panel/context'

const ctx = useColorPickerPanelContext()
</script>

<template>
  <div
    class="grid grid-cols-[repeat(3,minmax(0,1fr))] gap-px overflow-hidden rounded border border-border bg-border"
  >
    <input
      type="number"
      class="bg-input px-2 py-1 text-xs text-surface outline-none"
      :value="Math.round(ctx.hsbColor.h)"
      min="0"
      max="360"
      @change="ctx.updateHSBChannelValue('h', inputNumberValue($event))"
    />
    <input
      type="number"
      class="bg-input px-2 py-1 text-xs text-surface outline-none"
      :value="Math.round(ctx.hsbColor.s)"
      min="0"
      max="100"
      @change="ctx.updateHSBChannelValue('s', inputNumberValue($event))"
    />
    <input
      type="number"
      class="bg-input px-2 py-1 text-xs text-surface outline-none"
      :value="Math.round(ctx.hsbColor.b)"
      min="0"
      max="100"
      @change="ctx.updateHSBChannelValue('b', inputNumberValue($event))"
    />
  </div>

  <StandardColorSlider
    label="Saturation"
    :model-value="ctx.rekaColor"
    channel="saturation"
    color-space="hsb"
    :step="0.1"
    :number-value="Math.round(ctx.hsbColor.s)"
    :number-min="0"
    :number-max="100"
    suffix="%"
    :thumb-fill="colorToCSS(ctx.sliderPreview.hsbSaturation)"
    data-test-id="color-slider-hsb-s"
    @update="ctx.onRekaColorUpdate"
    @update-number="ctx.updateHSBChannelValue('s', $event)"
  />

  <StandardColorSlider
    label="Brightness"
    :model-value="ctx.rekaColor"
    channel="brightness"
    color-space="hsb"
    :step="0.1"
    :number-value="Math.round(ctx.hsbColor.b)"
    :number-min="0"
    :number-max="100"
    suffix="%"
    :thumb-fill="colorToCSS(ctx.sliderPreview.hsbBrightness)"
    data-test-id="color-slider-hsb-b"
    @update="ctx.onRekaColorUpdate"
    @update-number="ctx.updateHSBChannelValue('b', $event)"
  />

  <p class="text-[10px] leading-4 text-muted">{{ ctx.panels.colorHintHsb }}</p>
</template>

// src/components/color-picker-panel/HsbFields.tsx
import React from 'react'

import ColorSliderField from './ColorSliderField'
import { useColorPickerPanelContext } from './context'

const formatPercent = (value: number) => `${Math.round(value)}%`

export function HsbFields() {
  const ctx = useColorPickerPanelContext()
  const { h, s, b } = ctx.hsb

  return (
    <>
      <div className="grid grid-cols-[repeat(3,minmax(0,1fr))] gap-px overflow-hidden rounded border border-border bg-border">
        <input
          type="number"
          aria-label="Hue"
          className="bg-input px-2 py-1 text-xs text-surface outline-none"
          value={Math.round(h)}
          min={0}
          max={360}
          onChange={(event) => ctx.updateHSBChannel('h', Number(event.target.value))}
        />
        <input
          type="number"
          aria-label="Saturation"
          className="bg-input px-2 py-1 text-xs text-surface outline-none"
          value={Math.round(s)}
          min={0}
          max={100}
          onChange={(event) => ctx.updateHSBChannel('s', Number(event.target.value))}
        />
        <input
          type="number"
          aria-label="Brightness"
          className="bg-input px-2 py-1 text-xs text-surface outline-none"
          value={Math.round(b)}
          min={0}
          max={100}
          onChange={(event) => ctx.updateHSBChannel('b', Number(event.target.value))}
        />
      </div>

      <ColorSliderField
        label="Saturation"
        value={s}
        min={0}
        max={100}
        step={0.1}
        displayValue={Math.round(s)}
        displayMin={0}
        displayMax={100}
        suffix="%"
        gradient={ctx.gradients.hsbSaturation}
        thumbFill={ctx.thumbFills.hsbSaturation}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateHSBChannel('s', value)}
        onDisplayChange={(value) => ctx.updateHSBChannel('s', value)}
        data-test-id="color-slider-hsb-s"
      />

      <ColorSliderField
        label="Brightness"
        value={b}
        min={0}
        max={100}
        step={0.1}
        displayValue={Math.round(b)}
        displayMin={0}
        displayMax={100}
        suffix="%"
        gradient={ctx.gradients.hsbBrightness}
        thumbFill={ctx.thumbFills.hsbBrightness}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateHSBChannel('b', value)}
        onDisplayChange={(value) => ctx.updateHSBChannel('b', value)}
        data-test-id="color-slider-hsb-b"
      />

      <p className="text-[10px] leading-4 text-muted">{ctx.panels.colorHintHsb}</p>
    </>
  )
}

export default HsbFields
