// src/components/color-picker-panel/HslFields.vue
<script setup lang="ts">
import { inputNumberValue } from '@openweave/vue'
import { colorToCSS } from '@openweave/core/color'

import StandardColorSlider from '@/components/color-picker-panel/StandardColorSlider.vue'
import { useColorPickerPanelContext } from '@/components/color-picker-panel/context'

const ctx = useColorPickerPanelContext()
</script>

<template>
  <div
    class="grid grid-cols-[repeat(3,minmax(0,1fr))] gap-px overflow-hidden rounded border border-border bg-border"
  >
    <input
      type="number"
      class="bg-input px-2 py-1 text-xs text-surface outline-none"
      :value="Math.round(ctx.hslColor.h ?? 0)"
      min="0"
      max="360"
      @change="ctx.updateHSLChannelValue('h', inputNumberValue($event))"
    />
    <input
      type="number"
      class="bg-input px-2 py-1 text-xs text-surface outline-none"
      :value="Math.round(ctx.hslColor.s ?? 0)"
      min="0"
      max="100"
      @change="ctx.updateHSLChannelValue('s', inputNumberValue($event))"
    />
    <input
      type="number"
      class="bg-input px-2 py-1 text-xs text-surface outline-none"
      :value="Math.round(ctx.hslColor.l ?? 0)"
      min="0"
      max="100"
      @change="ctx.updateHSLChannelValue('l', inputNumberValue($event))"
    />
  </div>

  <StandardColorSlider
    label="Saturation"
    :model-value="ctx.rekaColor"
    channel="saturation"
    color-space="hsl"
    :step="0.1"
    :number-value="Math.round(ctx.hslColor.s ?? 0)"
    :number-min="0"
    :number-max="100"
    suffix="%"
    :thumb-fill="colorToCSS(ctx.sliderPreview.hslSaturation)"
    data-test-id="color-slider-hsl-s"
    @update="ctx.onRekaColorUpdate"
    @update-number="ctx.updateHSLChannelValue('s', $event)"
  />

  <StandardColorSlider
    label="Lightness"
    :model-value="ctx.rekaColor"
    channel="lightness"
    color-space="hsl"
    :step="0.1"
    :number-value="Math.round(ctx.hslColor.l ?? 0)"
    :number-min="0"
    :number-max="100"
    suffix="%"
    :thumb-fill="colorToCSS(ctx.sliderPreview.hslLightness)"
    data-test-id="color-slider-hsl-l"
    @update="ctx.onRekaColorUpdate"
    @update-number="ctx.updateHSLChannelValue('l', $event)"
  />

  <p class="text-[10px] leading-4 text-muted">{{ ctx.panels.colorHintHsl }}</p>
</template>

// src/components/color-picker-panel/HslFields.tsx
import React from 'react'

import { useColorPickerPanelContext } from './context'
import ColorSliderField from './ColorSliderField'

const formatPercent = (value: number) => `${Math.round(value)}%`

export function HslFields() {
  const ctx = useColorPickerPanelContext()
  const { h, s, l } = ctx.hsl

  return (
    <>
      <div className="grid grid-cols-[repeat(3,minmax(0,1fr))] gap-px overflow-hidden rounded border border-border bg-border">
        <input
          type="number"
          aria-label="Hue"
          className="bg-input px-2 py-1 text-xs text-surface outline-none"
          value={Math.round(h ?? 0)}
          min={0}
          max={360}
          onChange={(event) => ctx.updateHSLChannel('h', Number(event.target.value))}
        />
        <input
          type="number"
          aria-label="Saturation"
          className="bg-input px-2 py-1 text-xs text-surface outline-none"
          value={Math.round(s ?? 0)}
          min={0}
          max={100}
          onChange={(event) => ctx.updateHSLChannel('s', Number(event.target.value))}
        />
        <input
          type="number"
          aria-label="Lightness"
          className="bg-input px-2 py-1 text-xs text-surface outline-none"
          value={Math.round(l ?? 0)}
          min={0}
          max={100}
          onChange={(event) => ctx.updateHSLChannel('l', Number(event.target.value))}
        />
      </div>

      <ColorSliderField
        label="Saturation"
        value={s}
        min={0}
        max={100}
        step={0.1}
        displayValue={Math.round(s ?? 0)}
        displayMin={0}
        displayMax={100}
        suffix="%"
        gradient={ctx.gradients.hslSaturation}
        thumbFill={ctx.thumbFills.hslSaturation}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateHSLChannel('s', value)}
        onDisplayChange={(value) => ctx.updateHSLChannel('s', value)}
        data-test-id="color-slider-hsl-s"
      />

      <ColorSliderField
        label="Lightness"
        value={l}
        min={0}
        max={100}
        step={0.1}
        displayValue={Math.round(l ?? 0)}
        displayMin={0}
        displayMax={100}
        suffix="%"
        gradient={ctx.gradients.hslLightness}
        thumbFill={ctx.thumbFills.hslLightness}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateHSLChannel('l', value)}
        onDisplayChange={(value) => ctx.updateHSLChannel('l', value)}
        data-test-id="color-slider-hsl-l"
      />

      <p className="text-[10px] leading-4 text-muted">{ctx.panels.colorHintHsl}</p>
    </>
  )
}

export default HslFields
