// src/components/color-picker-panel/OkhclFields.vue
<script setup lang="ts">
import { colorToCSS } from '@openweave/core/color'
import { fromPercent, toPercent } from '@openweave/vue'

import OkhclChannelSlider from '@/components/color-picker-panel/OkhclChannelSlider.vue'
import { useColorPickerPanelContext } from '@/components/color-picker-panel/context'

const ctx = useColorPickerPanelContext()
const percentText = (value: number) => `${Math.round(toPercent(value))}%`
</script>

<template>
  <div v-if="ctx.isOkHCLFormat && ctx.okhcl?.okhcl" class="flex flex-col gap-2">
    <OkhclChannelSlider
      label="Hue"
      :model-value="ctx.okhcl.okhcl.h"
      :min="0"
      :max="360"
      :step="1"
      :display-value="Math.round(ctx.okhcl.okhcl.h)"
      :display-min="0"
      :display-max="360"
      :thumb-fill="colorToCSS(ctx.okhclSliderPreview?.okhclHue ?? ctx.color)"
      gradient="background: linear-gradient(to right, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff, #ff0000);"
      data-test-id="color-slider-okhcl-h"
      @update:model-value="ctx.updateOkHCLChannel('h', $event)"
      @update-display="ctx.updateOkHCLChannel('h', $event)"
    />

    <OkhclChannelSlider
      label="Chroma"
      :model-value="ctx.okhcl.okhcl.c"
      :min="0"
      :max="0.4"
      :step="0.001"
      :display-value="toPercent(ctx.okhcl.okhcl.c)"
      :display-min="0"
      :display-max="40"
      suffix="%"
      :gradient="ctx.okhclSliderGradient?.okhclChroma ?? undefined"
      :thumb-fill="colorToCSS(ctx.okhclSliderPreview?.okhclChroma ?? ctx.color)"
      :format-value-text="percentText"
      data-test-id="color-slider-okhcl-c"
      @update:model-value="ctx.updateOkHCLChannel('c', $event)"
      @update-display="ctx.updateOkHCLChannel('c', fromPercent($event))"
    />

    <OkhclChannelSlider
      label="Lightness"
      :model-value="ctx.okhcl.okhcl.l"
      :min="0"
      :max="1"
      :step="0.001"
      :display-value="toPercent(ctx.okhcl.okhcl.l)"
      :display-min="0"
      :display-max="100"
      suffix="%"
      :gradient="ctx.okhclSliderGradient?.okhclLightness ?? undefined"
      :thumb-fill="colorToCSS(ctx.okhclSliderPreview?.okhclLightness ?? ctx.color)"
      :format-value-text="percentText"
      data-test-id="color-slider-okhcl-l"
      @update:model-value="ctx.updateOkHCLChannel('l', $event)"
      @update-display="ctx.updateOkHCLChannel('l', fromPercent($event))"
    />

    <OkhclChannelSlider
      label="Alpha"
      :model-value="ctx.okhcl.okhcl.a ?? 1"
      :min="0"
      :max="1"
      :step="0.001"
      :display-value="toPercent(ctx.okhcl.okhcl.a ?? 1)"
      :display-min="0"
      :display-max="100"
      suffix="%"
      checkerboard
      :gradient="`background: linear-gradient(to right, transparent, ${colorToCSS({ ...ctx.color, a: 1 })})`"
      :thumb-fill="colorToCSS(ctx.color)"
      :format-value-text="percentText"
      data-test-id="color-slider-okhcl-a"
      @update:model-value="ctx.updateOkHCLChannel('a', $event)"
      @update-display="ctx.updateOkHCLChannel('a', fromPercent($event))"
    />

    <div class="flex items-start justify-between gap-2 text-[10px] text-muted">
      <p class="min-w-0 flex-1 leading-4 break-words">{{ ctx.panels.colorHintOkhcl }}</p>
      <span
        v-if="ctx.okhcl.previewColorSpace"
        class="shrink-0 rounded border border-border px-1 py-0.5 text-[10px] uppercase"
      >
        {{ ctx.okhcl.previewColorSpace }}
      </span>
    </div>
    <p v-if="ctx.okhcl.clipped" class="text-[10px] leading-4 text-[var(--color-warning-text)]">
      {{ ctx.panels.colorPreviewClipped({ space: ctx.okhcl.previewColorSpace ?? 'display-p3' }) }}
    </p>
  </div>
</template>

// src/components/color-picker-panel/OkhclFields.tsx
import React from 'react'

import { fromPercent, toPercent } from '@openweave/react'

import ColorSliderField from './ColorSliderField'
import { useColorPickerPanelContext } from './context'
import { HUE_RAINBOW_GRADIENT } from './helpers'

const formatDegrees = (value: number) => `${Math.round(value)}°`
const formatPercent = (value: number) => `${Math.round(toPercent(value))}%`

export function OkhclFields() {
  const ctx = useColorPickerPanelContext()
  if (!ctx.isOkHCLFormat) return null

  const { h, c, l, a } = ctx.okhcl

  return (
    <div className="flex flex-col gap-2">
      <ColorSliderField
        label="Hue"
        value={h}
        min={0}
        max={360}
        step={1}
        displayValue={Math.round(h)}
        displayMin={0}
        displayMax={360}
        gradient={HUE_RAINBOW_GRADIENT}
        thumbFill={ctx.thumbFills.okhclHue}
        formatValueText={formatDegrees}
        onValueChange={(value) => ctx.updateOkHCLChannel('h', value)}
        onDisplayChange={(value) => ctx.updateOkHCLChannel('h', value)}
        data-test-id="color-slider-okhcl-h"
      />

      <ColorSliderField
        label="Chroma"
        value={c}
        min={0}
        max={0.4}
        step={0.001}
        displayValue={toPercent(c)}
        displayMin={0}
        displayMax={40}
        suffix="%"
        gradient={ctx.gradients.okhclChroma}
        thumbFill={ctx.thumbFills.okhclChroma}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateOkHCLChannel('c', value)}
        onDisplayChange={(value) => ctx.updateOkHCLChannel('c', fromPercent(value))}
        data-test-id="color-slider-okhcl-c"
      />

      <ColorSliderField
        label="Lightness"
        value={l}
        min={0}
        max={1}
        step={0.001}
        displayValue={toPercent(l)}
        displayMin={0}
        displayMax={100}
        suffix="%"
        gradient={ctx.gradients.okhclLightness}
        thumbFill={ctx.thumbFills.okhclLightness}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateOkHCLChannel('l', value)}
        onDisplayChange={(value) => ctx.updateOkHCLChannel('l', fromPercent(value))}
        data-test-id="color-slider-okhcl-l"
      />

      <ColorSliderField
        label="Alpha"
        value={a ?? 1}
        min={0}
        max={1}
        step={0.001}
        displayValue={toPercent(a ?? 1)}
        displayMin={0}
        displayMax={100}
        suffix="%"
        checkerboard
        gradient={ctx.gradients.okhclAlpha}
        thumbFill={ctx.thumbFills.okhclAlpha}
        formatValueText={formatPercent}
        onValueChange={(value) => ctx.updateOkHCLChannel('a', value)}
        onDisplayChange={(value) => ctx.updateOkHCLChannel('a', fromPercent(value))}
        data-test-id="color-slider-okhcl-a"
      />

      <div className="flex items-start justify-between gap-2 text-[10px] text-muted">
        <p className="min-w-0 flex-1 leading-4 break-words">{ctx.panels.colorHintOkhcl}</p>
        {ctx.previewColorSpace ? (
          <span className="shrink-0 rounded border border-border px-1 py-0.5 text-[10px] uppercase">
            {ctx.previewColorSpace}
          </span>
        ) : null}
      </div>
      {ctx.clipped ? (
        <p className="text-[10px] leading-4 text-[var(--color-warning-text)]">
          {ctx.panels.colorPreviewClipped({ space: ctx.previewColorSpace ?? 'display-p3' })}
        </p>
      ) : null}
    </div>
  )
}

export default OkhclFields
