// packages/vue/src/primitives/Fill/FillSwatch.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'

import { useOptionalBindableValue } from '#vue/primitives/BindableValue/context'
import type { FillSwatchProps, FillSwatchSlots } from './types'
import { fillCategory, fillIsTransparent, fillSwatchBackground } from './useFill'

import type { Color } from '@openweave/scene-graph/primitives'

const { fill, label, as = 'span', asChild = false } = defineProps<FillSwatchProps>()
defineSlots<FillSwatchSlots>()
defineOptions({ inheritAttrs: false })

const binding = useOptionalBindableValue<Color>()
const bindingState = computed(() => binding?.state.value)
const boundColor = computed(() =>
  bindingState.value === 'bound' ? binding?.resolvedValue.value : undefined
)
const effectiveFill = computed(() =>
  fill.type === 'SOLID' && boundColor.value ? { ...fill, color: boundColor.value } : fill
)
const category = computed(() => fillCategory(effectiveFill.value))
const background = computed(() => fillSwatchBackground(effectiveFill.value))
const transparent = computed(() => fillIsTransparent(effectiveFill.value))
const accessibleLabel = computed(() => label ?? `${category.value.toLowerCase()} fill`)
const stateAttrs = computed(() => binding?.stateAttrs.value)
const slotProps = computed(() => ({
  fill: effectiveFill.value,
  color: effectiveFill.value.color,
  category: category.value,
  background: background.value,
  transparent: transparent.value,
  bindingState: bindingState.value,
  stateAttrs: stateAttrs.value
}))
</script>

<template>
  <Primitive
    v-bind="{ ...$attrs, ...stateAttrs }"
    :as="as"
    :as-child="asChild"
    :aria-label="accessibleLabel"
    :data-fill-type="effectiveFill.type"
    :data-fill-category="category"
    :data-transparent="transparent ? '' : undefined"
    :style="{ '--openweave-fill-swatch-background': background }"
    role="img"
    aria-roledescription="fill swatch"
    data-slot="swatch"
  >
    <slot v-bind="slotProps" />
  </Primitive>
</template>

// packages/react/src/primitives/Fill/FillSwatch.tsx
import React, { ElementType } from 'react'
import { Slot } from '@radix-ui/react-slot'

import { useBindingProvider } from '#react/controls/binding-provider/use'
import { useBindableValueState } from '#react/primitives/BindableValue/use'
import { useFill } from './useFill'

import type { FillSwatchProps } from './types'

export function FillSwatch({
  fill,
  label,
  as: Component = 'button',
  asChild = false,
  children,
  ...props
}: FillSwatchProps) {
  const provider = useBindingProvider()
  const { category, swatchBackground, transparent } = useFill(fill, () => {})
  
  const variableId = fill.type === 'SOLID' ? fill.boundVariables?.color?.id : undefined
  const state = useBindableValueState(variableId ? provider?.resolveVariable(variableId) : undefined)

  const Comp = asChild ? Slot : Component

  const renderedChildren = typeof children === 'function' ? children({
    fill,
    color: fill.color,
    category,
    background: swatchBackground,
    transparent,
    bindingState: state.bindingState,
    stateAttrs: state.stateAttrs
  }) : children

  return (
    <Comp
      aria-label={label ?? 'Color swatch'}
      title={label}
      {...state.stateAttrs}
      {...(props as any)}
    >
      {renderedChildren}
    </Comp>
  )
}

export default FillSwatch
