// src/components/properties/shared-style/SharedStyleField.vue
<script setup lang="ts">
import { computed } from 'vue'

import { MIXED, useI18n, useSharedStyleBinding } from '@openweave/vue'

import AppSelect from '@/components/ui/AppSelect.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'

import type { SharedStyleKind } from '@openweave/scene-graph'

interface SharedStyleFieldProps {
  kind: SharedStyleKind
  label: string
}

const { kind, label } = defineProps<SharedStyleFieldProps>()
const { panels } = useI18n()
const binding = useSharedStyleBinding(kind)
const { active, styleId, styles } = binding
const visible = computed(
  () =>
    active.value && (styles.value.length > 0 || styleId.value === MIXED || styleId.value !== null)
)
const options = computed(() => {
  const result: Array<{ value: string; label: string }> = [
    { value: 'NONE', label: panels.value.none }
  ]
  if (styleId.value === MIXED) result.unshift({ value: 'MIXED', label: panels.value.mixed })
  for (const style of styles.value) result.push({ value: style.id, label: style.name })
  if (
    typeof styleId.value === 'string' &&
    !styles.value.some((style) => style.id === styleId.value)
  ) {
    result.push({ value: styleId.value, label: panels.value.missingStyle({ id: styleId.value }) })
  }
  return result
})

function update(value: string) {
  if (value === 'MIXED') return
  if (value === 'NONE') binding.unbind()
  else binding.bind(value)
}
</script>

<template>
  <PanelGrid v-if="visible" class="mb-1.5">
    <PanelFieldGroup :label="label">
      <AppSelect
        :model-value="styleId === MIXED ? 'MIXED' : (styleId ?? 'NONE')"
        :options="options"
        :label="label"
        :data-property="`${kind}-style`"
        @update:model-value="update"
      />
    </PanelFieldGroup>
  </PanelGrid>
</template>

// src/components/properties/shared-style/SharedStyleField.tsx
import React from 'react'

import { MIXED, useI18n, useSharedStyleBinding } from '@openweave/react'

import { AppSelect } from '@/components/ui/AppSelect'
import { PanelFieldGroup, PanelGrid } from '@/components/ui/panel'

import type { SharedStyleKind } from '@openweave/scene-graph'

export interface SharedStyleFieldProps {
  kind: SharedStyleKind
  label: string
}

/**
 * Apply/detach selector for shared styles. Hidden until at least one style of
 * the kind exists or the selection references one; shows Mixed when the
 * selection diverges and a "missing style" entry when the referenced style no
 * longer exists. Editing the underlying property detaches the style
 * automatically via the editor core.
 */
export default function SharedStyleField({ kind, label }: SharedStyleFieldProps) {
  const { panels } = useI18n()
  const binding = useSharedStyleBinding(kind)
  const { active, styleId, styles } = binding
  const visible = active && (styles.length > 0 || styleId === MIXED || styleId !== null)

  if (!visible) return null

  const options: Array<{ value: string; label: string }> = [
    { value: 'NONE', label: panels.none }
  ]
  if (styleId === MIXED) options.unshift({ value: 'MIXED', label: panels.mixed })
  for (const style of styles) options.push({ value: style.id, label: style.name })
  if (typeof styleId === 'string' && !styles.some((style) => style.id === styleId)) {
    options.push({ value: styleId, label: panels.missingStyle({ id: styleId }) })
  }

  const value = styleId === MIXED ? 'MIXED' : typeof styleId === 'string' ? styleId : 'NONE'

  function update(next: string) {
    if (next === 'MIXED') return
    if (next === 'NONE') binding.unbind()
    else binding.bind(next)
  }

  return (
    <PanelGrid className="mb-1.5">
      <PanelFieldGroup label={label} data-property={`${kind}-style`}>
        <AppSelect value={value} options={options} label={label} onValueChange={update} />
      </PanelFieldGroup>
    </PanelGrid>
  )
}
