// src/components/chat/ChatMessage.tsx
import React from 'react'
import ReactMarkdown from 'react-markdown'
import type { UIMessage } from 'ai'

import ChatToolCall, { isToolPart } from '@/components/chat/ChatToolCall'
import type { ToolPartLike } from '@/components/chat/ChatToolCall'

/**
 * Minimal styling for assistant markdown inside the small chat bubble —
 * react-markdown ships no CSS of its own (unlike the old vue-stream-markdown).
 */
const MARKDOWN_CLASS =
  'chat-markdown min-w-0 break-words ' +
  '[&_a]:text-accent [&_a]:underline ' +
  '[&_blockquote]:border-l-2 [&_blockquote]:border-border [&_blockquote]:pl-2 [&_blockquote]:text-muted ' +
  '[&_code]:rounded [&_code]:bg-canvas [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-[11px] ' +
  '[&_:is(h1,h2,h3,h4,h5,h6)]:my-1 [&_:is(h1,h2,h3,h4,h5,h6)]:text-xs [&_:is(h1,h2,h3,h4,h5,h6)]:font-semibold ' +
  '[&_li]:my-0.5 [&_ol]:my-1 [&_ol]:list-decimal [&_ol]:pl-4 ' +
  '[&_p]:my-1 ' +
  '[&_pre]:my-1 [&_pre]:overflow-x-auto [&_pre]:rounded [&_pre]:bg-canvas [&_pre]:p-2 [&_pre_code]:bg-transparent [&_pre_code]:p-0 ' +
  '[&_strong]:font-semibold ' +
  '[&_ul]:my-1 [&_ul]:list-disc [&_ul]:pl-4'

function messageText(message: UIMessage): string {
  return message.parts.map((part) => (part.type === 'text' ? part.text : '')).join('')
}

function toolParts(message: UIMessage): ToolPartLike[] {
  return message.parts.filter(isToolPart)
}

/**
 * Single chat bubble, ported from ChatMessage.vue: assistant text renders as
 * markdown, tool calls render as expandable ChatToolCall rows, user text
 * stays plain (matching the Vue version, which never ran user text through
 * the markdown renderer).
 */
export default function ChatMessage({ message }: { message: UIMessage }) {
  const text = messageText(message)
  const tools = message.role === 'assistant' ? toolParts(message) : []

  return (
    <div
      data-test-id="chat-message"
      data-role={message.role}
      className={`flex gap-2 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}
    >
      <div className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted/20 text-[10px] font-bold text-muted">
        {message.role === 'user' ? 'You' : 'AI'}
      </div>
      <div
        className={`min-w-0 max-w-[85%] rounded-lg px-3 py-2 text-xs leading-5 ${
          message.role === 'user' ? 'bg-accent/10 text-surface' : 'bg-input/40 text-surface'
        }`}
      >
        {text ? (
          message.role === 'assistant' ? (
            <div className={MARKDOWN_CLASS}>
              <ReactMarkdown>{text}</ReactMarkdown>
            </div>
          ) : (
            <span className="whitespace-pre-wrap break-words">{text}</span>
          )
        ) : null}
        {tools.length > 0 ? (
          <div className="mt-1 flex flex-col gap-1">
            {tools.map((tool, i) => (
              <ChatToolCall key={tool.toolCallId ?? `tool-${i}`} part={tool} />
            ))}
          </div>
        ) : null}
      </div>
    </div>
  )
}

// src/components/chat/ChatMessage.vue
<script setup lang="ts">
import { isTextUIPart, isToolUIPart, getToolName } from 'ai'
import { CollapsibleContent, CollapsibleRoot, CollapsibleTrigger } from 'reka-ui'
import { Markdown } from 'vue-stream-markdown'
import { vTestId } from '@openweave/vue'
import 'vue-stream-markdown/index.css'

import type { UIDataTypes, UIMessage, UIMessagePart, UITools } from 'ai'

const { message } = defineProps<{ message: UIMessage }>()

type ToolPart = Extract<UIMessagePart<UIDataTypes, UITools>, { toolCallId: string }>

function toolDisplayName(part: ToolPart): string {
  return getToolName(part)
    .replace(/^mcp__[^_]+__/, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function hasErrorOutput(part: ToolPart): boolean {
  return (
    part.state === 'output-available' &&
    typeof part.output === 'object' &&
    part.output !== null &&
    'error' in part.output
  )
}

function toolState(part: ToolPart): 'pending' | 'done' | 'error' {
  if (part.state === 'output-error' || hasErrorOutput(part)) return 'error'
  if (part.state === 'output-available') return 'done'
  return 'pending'
}

function partKey(part: UIMessagePart<UIDataTypes, UITools>, index: number): string {
  if ('toolCallId' in part) return part.toolCallId
  return `part-${index}`
}
</script>

<template>
  <div
    v-test-id="`chat-message-${message.role}`"
    :class="message.role === 'user' ? 'flex justify-end' : ''"
  >
    <div class="min-w-0 space-y-1.5" :class="message.role === 'user' ? 'max-w-[85%]' : ''">
      <template v-if="message.role === 'assistant'">
        <template v-for="(part, i) in message.parts" :key="partKey(part, i)">
          <!-- Tool call -->
          <div v-if="isToolUIPart(part)" class="rounded-lg border border-border bg-canvas p-2">
            <CollapsibleRoot>
              <CollapsibleTrigger
                class="flex w-full items-center gap-2 rounded px-1 py-0.5 hover:bg-hover"
              >
                <div
                  class="flex size-4 items-center justify-center rounded-full"
                  :class="{
                    'bg-accent/20 text-accent': toolState(part) === 'pending',
                    'bg-green-500/20 text-green-400': toolState(part) === 'done',
                    'bg-red-500/20 text-red-400': toolState(part) === 'error'
                  }"
                >
                  <icon-lucide-loader-circle
                    v-if="toolState(part) === 'pending'"
                    class="size-3 animate-spin"
                  />
                  <icon-lucide-check v-else-if="toolState(part) === 'done'" class="size-3" />
                  <icon-lucide-triangle-alert v-else class="size-3" />
                </div>
                <span class="text-[11px] text-surface">
                  {{ toolDisplayName(part) }}
                </span>
                <span class="text-[10px] text-muted">
                  {{
                    toolState(part) === 'pending'
                      ? 'Running…'
                      : toolState(part) === 'done'
                        ? 'Done'
                        : 'Error'
                  }}
                </span>
                <icon-lucide-chevron-down
                  v-if="toolState(part) !== 'pending'"
                  class="ml-auto size-3 text-muted transition-transform [[data-state=open]>&]:rotate-180"
                />
              </CollapsibleTrigger>
              <CollapsibleContent
                v-if="toolState(part) !== 'pending'"
                class="data-[state=closed]:collapsible-up data-[state=open]:collapsible-down overflow-hidden text-[10px]"
              >
                <pre class="mt-1 overflow-x-auto rounded bg-input p-2 text-muted">{{
                  part.state === 'output-error' && part.errorText
                    ? part.errorText
                    : hasErrorOutput(part)
                      ? (part.output as { error: string }).error
                      : JSON.stringify(part.output, null, 2)
                }}</pre>
              </CollapsibleContent>
            </CollapsibleRoot>
          </div>

          <!-- Text -->
          <div
            v-else-if="isTextUIPart(part) && part.text"
            data-test-id="chat-text-bubble"
            class="rounded-xl rounded-tl-md bg-hover px-3 py-2 text-xs leading-relaxed text-surface"
          >
            <Markdown :content="part.text" :mermaid="false" class="chat-markdown" />
          </div>
        </template>
      </template>

      <!-- User message -->
      <div
        v-else-if="message.role === 'user'"
        data-test-id="chat-text-bubble"
        class="rounded-xl rounded-br-md bg-accent px-3 py-2 text-xs leading-relaxed whitespace-pre-wrap text-white"
      >
        {{
          message.parts
            .filter(isTextUIPart)
            .map((p) => p.text)
            .join('')
        }}
      </div>
    </div>
  </div>
</template>
