// src/components/editor/ZoomDropdown.vue
<script setup lang="ts">
import {
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from 'reka-ui'
import { nextTick, ref, watch } from 'vue'

import { useEditorCommands, useI18n, formatShortcut } from '@openweave/vue'
import AppShortcutText from '@/components/ui/AppShortcutText.vue'
import { menuItem, useMenuUI } from '@/components/ui/menu'
import { useEditorStore } from '@/app/editor/active-store'
import { appMenuShortcut, appMenuShortcutLabel } from '@/app/shell/menu/shortcut'

const store = useEditorStore()
const { getCommand } = useEditorCommands()
const { menu: menuText, commands, panels } = useI18n()

const open = ref(false)
const editing = ref(false)
const inputRef = ref<HTMLInputElement | null>()
const inputValue = ref('')

const menuCls = useMenuUI({ content: 'min-w-52' })
const itemCls = menuItem({ justify: 'start', class: 'relative pl-7' })

function zoomPercent() {
  return Math.round(store.state.zoom * 100)
}

function startEditing() {
  editing.value = true
  inputValue.value = String(zoomPercent())
  void nextTick(() => inputRef.value?.select())
}

function commitInput() {
  const parsed = Number.parseInt(inputValue.value, 10)
  if (!Number.isNaN(parsed) && parsed > 0) {
    store.zoomToLevel(parsed / 100)
  }
  editing.value = false
}

function cancelInput() {
  editing.value = false
}

function toggleRulers() {
  store.state.showRulers = !store.state.showRulers
  store.requestRepaint()
}

function toggleRemoteCursors() {
  store.state.showRemoteCursors = !store.state.showRemoteCursors
  store.requestRepaint()
}

function zoomIn() {
  const center = store.viewportScreenCenter()
  store.applyZoom(-100, center.x, center.y)
}

function zoomOut() {
  const center = store.viewportScreenCenter()
  store.applyZoom(100, center.x, center.y)
}

const ZOOM_PRESETS: ReadonlyArray<{ label: string; level: number; shortcut?: string }> = [
  { label: '50%', level: 0.5 },
  { label: '100%', level: 1, shortcut: appMenuShortcut('view.zoom100') },
  { label: '200%', level: 2 }
]

function isActivePreset(level: number) {
  return Math.abs(store.state.zoom - level) < 0.005
}

watch(open, (v) => {
  if (!v) editing.value = false
})
</script>

<template>
  <DropdownMenuRoot v-model:open="open">
    <DropdownMenuTrigger as-child>
      <button
        data-test-id="zoom-dropdown-trigger"
        class="ml-auto cursor-pointer rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover"
      >
        {{ zoomPercent() }}%
      </button>
    </DropdownMenuTrigger>

    <DropdownMenuPortal>
      <DropdownMenuContent
        side="bottom"
        :side-offset="4"
        align="end"
        :class="menuCls.content"
        @escape-key-down="cancelInput"
      >
        <div class="px-1 py-1">
          <input
            v-if="editing"
            ref="inputRef"
            v-model="inputValue"
            data-test-id="zoom-input"
            class="w-full rounded border border-accent bg-input px-2 py-1 text-xs text-surface outline-none"
            @blur="commitInput"
            @keydown.enter="commitInput"
            @keydown.escape.stop="cancelInput"
          />
          <button
            v-else
            data-test-id="zoom-input-trigger"
            class="w-full cursor-pointer rounded border border-border bg-input px-2 py-1 text-left text-xs text-surface hover:border-muted"
            @click="startEditing"
          >
            {{ zoomPercent() }}%
          </button>
        </div>

        <DropdownMenuSeparator :class="menuCls.separator" />

        <DropdownMenuItem :class="itemCls" @select="zoomIn">
          <span class="flex-1">{{ menuText.zoomIn }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('zoom-in') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select="zoomOut">
          <span class="flex-1">{{ menuText.zoomOut }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('zoom-out') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select="getCommand('view.zoomFit').run()">
          <span class="flex-1">{{ commands.zoomToFit }}</span>
          <AppShortcutText>{{ appMenuShortcutLabel('view.zoomFit') }}</AppShortcutText>
        </DropdownMenuItem>
        <DropdownMenuItem
          v-for="preset in ZOOM_PRESETS"
          :key="preset.level"
          :class="itemCls"
          @select="store.zoomToLevel(preset.level)"
        >
          <icon-lucide-check v-if="isActivePreset(preset.level)" class="absolute left-2 size-3.5" />
          <span class="flex-1">{{ preset.label }}</span>
          <AppShortcutText v-if="preset.shortcut">{{
            formatShortcut(preset.shortcut)
          }}</AppShortcutText>
        </DropdownMenuItem>

        <DropdownMenuSeparator :class="menuCls.separator" />

        <DropdownMenuItem :class="itemCls" @select.prevent="toggleRulers">
          <icon-lucide-check v-if="store.state.showRulers" class="absolute left-2 size-3.5" />
          <span class="flex-1">{{ panels.rulers }}</span>
        </DropdownMenuItem>
        <DropdownMenuItem :class="itemCls" @select.prevent="toggleRemoteCursors">
          <icon-lucide-check
            v-if="store.state.showRemoteCursors"
            class="absolute left-2 size-3.5"
          />
          <span class="flex-1">{{ panels.multiplayerCursors }}</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenuPortal>
  </DropdownMenuRoot>
</template>

// src/components/editor/ZoomDropdown.tsx
import React, { useRef, useState } from 'react'
import * as DropdownMenu from '@radix-ui/react-dropdown-menu'
import { Check } from 'lucide-react'

import { useI18n } from '@openweave/react'

import { useEditorState } from '@/app/editor/session/use-editor-state'
import { getActiveEditorStore } from '@/app/editor/active-store'

/**
 * Ported from src/components/editor/ZoomDropdown.vue.
 *
 * Zoom control shown in the properties-panel header: current zoom %, an editable
 * zoom field, zoom in/out, zoom-to-fit, presets, and ruler / remote-cursor
 * toggles. Reads/writes the editor store directly (zoom + toggles are Vue refs,
 * bridged to React with a `watch`).
 */
const ZOOM_PRESETS: ReadonlyArray<{ label: string; level: number }> = [
  { label: '50%', level: 0.5 },
  { label: '100%', level: 1 },
  { label: '200%', level: 2 }
]

const itemCls =
  'relative flex cursor-pointer items-center rounded px-2 py-1 pl-7 text-xs text-surface outline-none select-none data-[highlighted]:bg-hover'

export default function ZoomDropdown() {
  const { menu, commands, panels } = useI18n()
  const [editing, setEditing] = useState(false)
  const [inputValue, setInputValue] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  const zoom = useEditorState((s) => s.zoom, 1)
  useEditorState((s) => s.showRulers, true)
  useEditorState((s) => s.showRemoteCursors, true)

  const store = getActiveEditorStore()
  const zoomPercent = Math.round(zoom * 100)

  const startEditing = () => {
    setInputValue(String(zoomPercent))
    setEditing(true)
    requestAnimationFrame(() => inputRef.current?.select())
  }
  const commitInput = () => {
    const parsed = Number.parseInt(inputValue, 10)
    if (!Number.isNaN(parsed) && parsed > 0) store.zoomToLevel(parsed / 100)
    setEditing(false)
  }
  const zoomBy = (factor: number) => store.zoomToLevel(store.state.zoom * factor)
  const isActivePreset = (level: number) => Math.abs(store.state.zoom - level) < 0.005
  const toggleRulers = () => {
    store.state.showRulers = !store.state.showRulers
    store.requestRepaint()
  }
  const toggleRemoteCursors = () => {
    store.state.showRemoteCursors = !store.state.showRemoteCursors
    store.requestRepaint()
  }

  return (
    <DropdownMenu.Root
      onOpenChange={(open) => {
        if (!open) setEditing(false)
      }}
    >
      <DropdownMenu.Trigger asChild>
        <button
          type="button"
          data-test-id="zoom-dropdown-trigger"
          className="cursor-pointer rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover"
        >
          {zoomPercent}%
        </button>
      </DropdownMenu.Trigger>

      <DropdownMenu.Portal>
        <DropdownMenu.Content
          side="bottom"
          sideOffset={4}
          align="end"
          className="z-50 min-w-52 rounded-md border border-border bg-panel p-1 shadow-lg"
        >
          <div className="px-1 py-1">
            {editing ? (
              <input
                ref={inputRef}
                value={inputValue}
                data-test-id="zoom-input"
                className="w-full rounded border border-accent bg-input px-2 py-1 text-xs text-surface outline-none"
                onChange={(e) => setInputValue(e.target.value)}
                onBlur={commitInput}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') commitInput()
                  if (e.key === 'Escape') {
                    e.stopPropagation()
                    setEditing(false)
                  }
                }}
              />
            ) : (
              <button
                type="button"
                data-test-id="zoom-input-trigger"
                className="w-full cursor-pointer rounded border border-border bg-input px-2 py-1 text-left text-xs text-surface hover:border-muted"
                onClick={(e) => {
                  e.preventDefault()
                  startEditing()
                }}
              >
                {zoomPercent}%
              </button>
            )}
          </div>

          <DropdownMenu.Separator className="my-1 h-px bg-border" />

          <DropdownMenu.Item className={itemCls} onSelect={() => zoomBy(1.2)}>
            <span className="flex-1">{menu.zoomIn}</span>
          </DropdownMenu.Item>
          <DropdownMenu.Item className={itemCls} onSelect={() => zoomBy(1 / 1.2)}>
            <span className="flex-1">{menu.zoomOut}</span>
          </DropdownMenu.Item>
          <DropdownMenu.Item className={itemCls} onSelect={() => store.zoomToFit()}>
            <span className="flex-1">{commands.zoomToFit}</span>
          </DropdownMenu.Item>
          {ZOOM_PRESETS.map((preset) => (
            <DropdownMenu.Item
              key={preset.level}
              className={itemCls}
              onSelect={() => store.zoomToLevel(preset.level)}
            >
              {isActivePreset(preset.level) && <Check className="absolute left-2 size-3.5" />}
              <span className="flex-1">{preset.label}</span>
            </DropdownMenu.Item>
          ))}

          <DropdownMenu.Separator className="my-1 h-px bg-border" />

          <DropdownMenu.Item
            className={itemCls}
            onSelect={(e) => {
              e.preventDefault()
              toggleRulers()
            }}
          >
            {store.state.showRulers && <Check className="absolute left-2 size-3.5" />}
            <span className="flex-1">{panels.rulers}</span>
          </DropdownMenu.Item>
          <DropdownMenu.Item
            className={itemCls}
            onSelect={(e) => {
              e.preventDefault()
              toggleRemoteCursors()
            }}
          >
            {store.state.showRemoteCursors && <Check className="absolute left-2 size-3.5" />}
            <span className="flex-1">{panels.multiplayerCursors}</span>
          </DropdownMenu.Item>
        </DropdownMenu.Content>
      </DropdownMenu.Portal>
    </DropdownMenu.Root>
  )
}
