// packages/vue/src/primitives/BindableValue/BindableValueRoot.vue
<script setup lang="ts" generic="V">
import { computed, onBeforeUnmount, ref } from 'vue'

import { useBindingProvider } from '#vue/controls/binding-provider/context'
import type {
  BindingMutationSource,
  BindingProvider,
  BindingTarget
} from '#vue/controls/binding-provider/types'
import { provideBindableValue } from '#vue/primitives/BindableValue/context'
import type {
  BindableValueActions,
  BindableValueContext,
  BindableValueRootProps,
  BindableValueRootSlots,
  BindableValueSlotProps,
  BindableValueStateAttrs
} from '#vue/primitives/BindableValue/types'

const {
  provider: providerProp,
  targets: targetsProp,
  value: valueProp,
  policy: policyProp = 'detach-on-edit',
  batchLabel = 'Edit bound value'
} = defineProps<BindableValueRootProps<V>>()

defineSlots<BindableValueRootSlots<V>>()

const injectedProvider = useBindingProvider<V>()
const resolvedProvider = providerProp ?? injectedProvider
if (!resolvedProvider) {
  throw new Error(
    '[openweave] BindableValueRoot requires a provider prop or provideBindingProvider()'
  )
}
const provider: BindingProvider<V> = resolvedProvider
const beginProviderBatch = provider.beginBatch
const commitProviderBatch = provider.commitBatch
const rollbackProviderBatch = provider.rollbackBatch
const supportsInteractionBatch =
  beginProviderBatch !== undefined &&
  commitProviderBatch !== undefined &&
  rollbackProviderBatch !== undefined

const targets = computed(() => targetsProp)
const value = computed(() => valueProp)
const policy = computed(() => policyProp)
const open = ref(false)
const searchTerm = ref('')
const state = computed(() => {
  void provider.revision?.value
  return provider.getState(targets.value)
})
const variable = computed(() => {
  const target = targets.value[0]
  return state.value === 'bound' && target ? provider.getBound(target) : undefined
})
const resolvedValue = computed(() => {
  void provider.revision?.value
  const current = variable.value
  return current ? provider.resolve(current.id) : undefined
})
const variables = computed(() => {
  void provider.revision?.value
  return provider.filterVariables(searchTerm.value)
})
const stateAttrs = computed<BindableValueStateAttrs>(() => ({
  'data-unbound': state.value === 'unbound' ? '' : undefined,
  'data-bound': state.value === 'bound' ? '' : undefined,
  'data-mixed': state.value === 'mixed' ? '' : undefined,
  'data-picker-open': open.value ? '' : undefined,
  'data-policy': policy.value
}))

let interactionActive = false
let detachedForInteraction = false
let bindingSnapshot = new Map<BindingTarget, string>()
let resolvedSnapshot: V | undefined

function runImmediate(label: string, action: () => void) {
  if (provider.runBatch) provider.runBatch(label, action)
  else action()
}

function bind(variableId: string) {
  runImmediate('Bind variable', () => {
    for (const target of targets.value) provider.bind(target, variableId)
  })
  open.value = false
}

function unbind() {
  runImmediate('Unbind variable', () => {
    for (const target of targets.value) provider.unbind(target)
  })
}

function create(name: string) {
  const target = targets.value[0]
  if (!target || !provider.create) return
  runImmediate('Create and bind variable', () => provider.create?.(target, value.value, name))
  open.value = false
}

function openPicker() {
  open.value = true
}

function closePicker() {
  open.value = false
}

function togglePicker() {
  open.value = !open.value
}

function setSearchTerm(term: string) {
  searchTerm.value = term
}

function snapshotBindings() {
  bindingSnapshot = new Map()
  for (const target of targets.value) {
    const current = provider.getBound(target)
    if (current) bindingSnapshot.set(target, current.id)
  }
}

function beginMutation(source: BindingMutationSource): boolean {
  if (interactionActive) return true
  const startedUnbound = state.value === 'unbound'
  const startedMixed = state.value === 'mixed'
  if (!startedUnbound && !startedMixed && policy.value === 'readonly-when-bound') return false
  if (
    !startedUnbound &&
    !startedMixed &&
    policy.value === 'edit-variable' &&
    (!variable.value || !provider.setValue)
  ) {
    return false
  }

  interactionActive = true
  void source
  if (!startedUnbound) snapshotBindings()
  resolvedSnapshot = resolvedValue.value
  if (supportsInteractionBatch) beginProviderBatch(batchLabel)

  if (startedMixed || (!startedUnbound && policy.value === 'detach-on-edit')) {
    detachedForInteraction = true
    for (const target of targets.value) provider.unbind(target)
  }
  return true
}

function applyValue(nextValue: V): boolean {
  if (policy.value !== 'edit-variable' || !interactionActive) return false
  const current = variable.value
  if (!current || !provider.setValue) return false
  provider.setValue(current.id, nextValue)
  return true
}

function resetInteraction() {
  interactionActive = false
  detachedForInteraction = false
  bindingSnapshot.clear()
  resolvedSnapshot = undefined
}

function commitMutation() {
  if (!interactionActive) return
  if (supportsInteractionBatch) commitProviderBatch()
  resetInteraction()
}

function restoreWithoutRollback() {
  if (detachedForInteraction) {
    for (const [target, variableId] of bindingSnapshot) provider.bind(target, variableId)
  } else if (
    policy.value === 'edit-variable' &&
    variable.value &&
    resolvedSnapshot !== undefined &&
    provider.setValue
  ) {
    provider.setValue(variable.value.id, resolvedSnapshot)
  }
}

function cancelMutation() {
  if (!interactionActive) return
  if (supportsInteractionBatch) rollbackProviderBatch()
  else restoreWithoutRollback()
  resetInteraction()
}

const actions: BindableValueActions<V> = {
  bind,
  unbind,
  create,
  openPicker,
  closePicker,
  togglePicker,
  setSearchTerm,
  beginMutation,
  applyValue,
  commitMutation,
  cancelMutation
}

const slotProps = computed<BindableValueSlotProps<V>>(() => ({
  state: state.value,
  variable: variable.value,
  resolvedValue: resolvedValue.value,
  policy: policy.value,
  open: open.value,
  searchTerm: searchTerm.value,
  variables: variables.value,
  stateAttrs: stateAttrs.value,
  actions
}))

const context: BindableValueContext<V> = {
  provider,
  targets,
  value,
  state,
  variable,
  resolvedValue,
  policy,
  open,
  searchTerm,
  variables,
  stateAttrs,
  slotProps,
  actions
}

provideBindableValue(context)
onBeforeUnmount(cancelMutation)
</script>

<template>
  <slot v-bind="slotProps" />
</template>

// packages/react/src/primitives/bindable-value/BindableValueRoot.tsx
import type { BindingTarget } from '#react/controls/binding-provider/types'
import React, { useState, useMemo, useEffect, useRef } from 'react'

import { BindableValueProvider } from './context'
import type {
  BindableValueActions,
  BindableValueContext,
  BindableValueRootProps,
  BindableValueSlotProps,
  BindableValueStateAttrs
} from './types'

// Note: React Context provider must be passed via provider prop or a surrounding context if implemented
export function BindableValueRoot<V = unknown>({
  provider: providerProp,
  targets,
  value,
  policy = 'detach-on-edit',
  batchLabel = 'Edit bound value',
  children
}: BindableValueRootProps<V>) {
  // If providerProp is not provided, you should fall back to a nearest injected provider (e.g. from context)
  const provider = providerProp!
  if (!provider) {
    throw new Error('[openweave] BindableValueRoot requires a provider prop')
  }

  const [open, setOpen] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')

  // Because provider might use external reactivity, you may need a way to force update
  // For now, we compute state based on current props and provider calls.
  // When provider.revision changes, a re-render should be triggered externally.

  const state = provider.getState(targets)

  const variable = useMemo(() => {
    const target = targets[0]
    return state === 'bound' && target ? provider.getBound(target) : undefined
  }, [state, targets, provider])

  const resolvedValue = useMemo(() => {
    return variable ? provider.resolve(variable.id) : undefined
  }, [variable, provider])

  const variables = useMemo(() => {
    return provider.filterVariables(searchTerm)
  }, [searchTerm, provider])

  const stateAttrs = useMemo<BindableValueStateAttrs>(
    () => ({
      'data-unbound': state === 'unbound' ? '' : undefined,
      'data-bound': state === 'bound' ? '' : undefined,
      'data-mixed': state === 'mixed' ? '' : undefined,
      'data-picker-open': open ? '' : undefined,
      'data-policy': policy
    }),
    [state, open, policy]
  )

  const interactionRef = useRef({
    active: false,
    detached: false,
    bindingSnapshot: new Map<BindingTarget, string>(),
    resolvedSnapshot: undefined as V | undefined
  })

  const actions = useMemo<BindableValueActions<V>>(() => {
    const runImmediate = (label: string, action: () => void) => {
      if (provider.runBatch) provider.runBatch(label, action)
      else action()
    }

    return {
      bind: (variableId: string) => {
        runImmediate('Bind variable', () => {
          for (const target of targets) provider.bind(target, variableId)
        })
        setOpen(false)
      },
      unbind: () => {
        runImmediate('Unbind variable', () => {
          for (const target of targets) provider.unbind(target)
        })
      },
      create: (name: string) => {
        const target = targets[0]
        if (!target || !provider.create) return
        runImmediate('Create and bind variable', () => provider.create?.(target, value, name))
        setOpen(false)
      },
      openPicker: () => setOpen(true),
      closePicker: () => setOpen(false),
      togglePicker: () => setOpen((prev) => !prev),
      setSearchTerm,
      beginMutation: (_source) => {
        const iState = interactionRef.current
        if (iState.active) return true
        const startedUnbound = state === 'unbound'
        const startedMixed = state === 'mixed'

        if (!startedUnbound && !startedMixed && policy === 'readonly-when-bound') return false
        if (
          !startedUnbound &&
          !startedMixed &&
          policy === 'edit-variable' &&
          (!variable || !provider.setValue)
        ) {
          return false
        }

        iState.active = true
        if (!startedUnbound) {
          iState.bindingSnapshot.clear()
          for (const target of targets) {
            const current = provider.getBound(target)
            if (current) iState.bindingSnapshot.set(target, current.id)
          }
        }
        iState.resolvedSnapshot = resolvedValue

        if (provider.beginBatch) provider.beginBatch(batchLabel)

        if (startedMixed || (!startedUnbound && policy === 'detach-on-edit')) {
          iState.detached = true
          for (const target of targets) provider.unbind(target)
        }
        return true
      },
      applyValue: (nextValue: V) => {
        const iState = interactionRef.current
        if (policy !== 'edit-variable' || !iState.active) return false
        if (!variable || !provider.setValue) return false
        provider.setValue(variable.id, nextValue)
        return true
      },
      commitMutation: () => {
        const iState = interactionRef.current
        if (!iState.active) return
        if (provider.commitBatch) provider.commitBatch()
        iState.active = false
        iState.detached = false
        iState.bindingSnapshot.clear()
        iState.resolvedSnapshot = undefined
      },
      cancelMutation: () => {
        const iState = interactionRef.current
        if (!iState.active) return
        if (provider.rollbackBatch) {
          provider.rollbackBatch()
        } else {
          if (iState.detached) {
            for (const [target, variableId] of iState.bindingSnapshot) {
              provider.bind(target, variableId)
            }
          } else if (
            policy === 'edit-variable' &&
            variable &&
            iState.resolvedSnapshot !== undefined &&
            provider.setValue
          ) {
            provider.setValue(variable.id, iState.resolvedSnapshot)
          }
        }
        iState.active = false
        iState.detached = false
        iState.bindingSnapshot.clear()
        iState.resolvedSnapshot = undefined
      }
    }
  }, [targets, provider, value, state, policy, variable, resolvedValue, batchLabel])

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      actions.cancelMutation()
    }
  }, [actions])

  const slotProps = useMemo<BindableValueSlotProps<V>>(
    () => ({
      state,
      variable,
      resolvedValue,
      policy,
      open,
      searchTerm,
      variables,
      stateAttrs,
      actions
    }),
    [state, variable, resolvedValue, policy, open, searchTerm, variables, stateAttrs, actions]
  )

  const contextValue = useMemo<BindableValueContext<V>>(
    () => ({
      provider,
      targets,
      value,
      state,
      variable,
      resolvedValue,
      policy,
      open,
      searchTerm,
      variables,
      stateAttrs,
      slotProps,
      actions
    }),
    [
      provider,
      targets,
      value,
      state,
      variable,
      resolvedValue,
      policy,
      open,
      searchTerm,
      variables,
      stateAttrs,
      slotProps,
      actions
    ]
  )

  const renderedChildren = typeof children === 'function' ? children(slotProps) : children

  return <BindableValueProvider value={contextValue}>{renderedChildren}</BindableValueProvider>
}

export default BindableValueRoot
