// src/components/assets/AssetsPanel.tsx
import React, { useEffect, useMemo, useState } from 'react'
import * as ContextMenu from '@radix-ui/react-context-menu'
import { BookOpen, LayoutGrid, List, Loader2, Plus, Component as ComponentIcon } from 'lucide-react'
import { useI18n } from '@openweave/react'
import type { SceneNode } from '@openweave/scene-graph'

import { useEditorStore } from '@/app/editor/active-store'
import { useSceneComputed } from '@openweave/react'
import { nodeIcon } from '@/app/editor/icons'
import { findAssetPage } from '@/components/assets/page'
import { openExternalLink } from '@/app/shell/ui'
import { AppDialogRoot, AppDialogHeader } from '@/components/ui/dialog'
import { useButtonUI } from '@/components/ui/button'
import { useMenuUI } from '@/components/ui/menu'
import {
  ASSET_GRID_THUMBNAIL_SIZE,
  ASSET_LIST_THUMBNAIL_SIZE,
  ASSET_THUMBNAIL_RENDER_SCALE
} from '@/constants'

type AssetView = 'grid' | 'list'

type AssetVariantInfo = { name: string; values: string[] }

type LocalAsset = {
  id: string
  name: string
  node: SceneNode
  componentId: string | null
  variants: AssetVariantInfo[]
  variantCount: number
  sourceLibraryKey: string | null
  description: string
  docsUrl: string | null
  pageId: string
  pageName: string
}

type AssetGroup = {
  pageId: string
  pageName: string
  assets: LocalAsset[]
}

function AssetThumbnail({ nodeId, alt, size }: { nodeId: string; alt: string; size: number }) {
  const editor = useEditorStore()
  const [url, setUrl] = useState<string | null>(null)
  const sceneVersion = useSceneComputed(() => editor.state.sceneVersion)
  const isGrid = size === ASSET_GRID_THUMBNAIL_SIZE

  useEffect(() => {
    let active = true
    let objectUrl: string | null = null
    const node = editor.graph.getNode(nodeId)
    if (!node) {
      setUrl(null)
      return
    }
    const maxDimension = Math.max(node.width, node.height, 1)
    const scale = (size * ASSET_THUMBNAIL_RENDER_SCALE) / maxDimension
    const pageId = findAssetPage(node, editor.graph)?.id ?? editor.state.currentPageId
    void editor
      .renderExportImage([nodeId], scale, 'PNG', pageId)
      .then((data) => {
        if (!active) return
        if (data) {
          objectUrl = URL.createObjectURL(new Blob([new Uint8Array(data)], { type: 'image/png' }))
          setUrl(objectUrl)
        } else {
          setUrl(null)
        }
        return undefined
      })
      .catch(() => {
        if (active) setUrl(null)
      })
    return () => {
      active = false
      if (objectUrl) URL.revokeObjectURL(objectUrl)
    }
  }, [editor, nodeId, size, sceneVersion])

  return (
    <div
      data-slot="asset-thumbnail"
      className={`flex shrink-0 items-center justify-center overflow-hidden rounded bg-canvas/60 ${
        isGrid ? 'size-24' : 'size-10'
      }`}
    >
      {url ? (
        <img src={url} alt={alt} className="max-h-full max-w-full object-contain" draggable={false} />
      ) : (
        <ComponentIcon className="size-4 text-component" aria-hidden="true" />
      )}
    </div>
  )
}

export default function AssetsPanel() {
  const editor = useEditorStore()
  const { panels, dialogs } = useI18n()
  const [query, setQuery] = useState('')
  const [assetView, setAssetView] = useState<AssetView>('grid')
  const [detailsOpen, setDetailsOpen] = useState(false)
  const [selectedAssetId, setSelectedAssetId] = useState<string | null>(null)
  const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  const [previewLoading, setPreviewLoading] = useState(false)

  const insertButtonCls = useButtonUI({ tone: 'accent', size: 'md' }).base
  const contextMenuCls = useMenuUI({ content: 'min-w-44' })

  const sceneVersion = useSceneComputed(() => editor.state.sceneVersion)

  function componentSetVariantInfo(componentSetId: string): AssetVariantInfo[] {
    return [...editor.collectVariantOptions(componentSetId)].map(([name, values]) => ({
      name,
      values: [...values].sort((a, b) => a.localeCompare(b))
    }))
  }

  const assets = useSceneComputed<LocalAsset[]>(() => {
    const nodes = [...editor.graph.nodes.values()].filter(
      (node) => node.type === 'COMPONENT' || node.type === 'COMPONENT_SET'
    )
    return nodes
      .filter((node) => {
        if (node.type === 'COMPONENT_SET') return true
        const parent = node.parentId ? editor.graph.getNode(node.parentId) : null
        return parent?.type !== 'COMPONENT_SET'
      })
      .map((node) => {
        const defaultVariant =
          node.type === 'COMPONENT_SET'
            ? editor.getDefaultVariantForComponentSet(node.id)
            : node
        const page = findAssetPage(node, editor.graph)
        return {
          id: node.id,
          name: node.name,
          node,
          componentId: defaultVariant?.id ?? null,
          variants: node.type === 'COMPONENT_SET' ? componentSetVariantInfo(node.id) : [],
          variantCount: node.type === 'COMPONENT_SET' ? node.childIds.length : 0,
          sourceLibraryKey: node.sourceLibraryKey,
          description: node.symbolDescription,
          docsUrl: node.symbolLinks[0]?.uri ?? null,
          pageId: page?.id ?? editor.state.currentPageId,
          pageName: page?.name ?? panels.page
        }
      })
      .sort((a, b) => a.name.localeCompare(b.name))
  })

  const filteredAssets = useMemo(() => {
    const normalized = query.trim().toLowerCase()
    if (!normalized) return assets
    return assets.filter((asset) => asset.name.toLowerCase().includes(normalized))
  }, [assets, query])

  const assetGroups = useMemo<AssetGroup[]>(() => {
    const groups = new Map<string, AssetGroup>()
    for (const asset of filteredAssets) {
      const group = groups.get(asset.pageId) ?? {
        pageId: asset.pageId,
        pageName: asset.pageName,
        assets: []
      }
      group.assets.push(asset)
      groups.set(asset.pageId, group)
    }
    return [...groups.values()].sort((a, b) => a.pageName.localeCompare(b.pageName))
  }, [filteredAssets])

  const selectedAsset = useMemo(
    () => assets.find((asset) => asset.id === selectedAssetId) ?? null,
    [assets, selectedAssetId]
  )
  const SelectedAssetIcon = selectedAsset ? nodeIcon(selectedAsset.node) : null

  // Fetch a larger preview render for the details dialog whenever it opens or
  // the selected asset / scene changes. Mirrors AssetThumbnail's fetch pattern
  // but at a bigger, fixed box size matching the dialog layout.
  useEffect(() => {
    let active = true
    let objectUrl: string | null = null
    const nodeId = selectedAsset?.componentId ?? null
    if (!detailsOpen || !nodeId) {
      setPreviewUrl(null)
      return
    }
    const node = editor.graph.getNode(nodeId)
    if (!node) {
      setPreviewUrl(null)
      return
    }
    setPreviewLoading(true)
    const maxSize = Math.max(node.width, node.height, 1)
    const scale = Math.min(176 / maxSize, 2)
    void editor
      .renderExportImage([nodeId], scale, 'PNG', selectedAsset?.pageId)
      .then((data) => {
        if (!active) return
        if (data) {
          objectUrl = URL.createObjectURL(new Blob([new Uint8Array(data)], { type: 'image/png' }))
          setPreviewUrl(objectUrl)
        } else {
          setPreviewUrl(null)
        }
        return undefined
      })
      .catch(() => {
        if (active) setPreviewUrl(null)
      })
      .then(() => {
        if (active) setPreviewLoading(false)
      })
    return () => {
      active = false
      if (objectUrl) URL.revokeObjectURL(objectUrl)
    }
  }, [editor, detailsOpen, selectedAsset?.componentId, selectedAsset?.pageId, sceneVersion])

  function insertionPoint(component: SceneNode, parentId: string) {
    const canvasCenter = editor.viewportCanvasCenter()
    const center = editor.screenToCanvas(canvasCenter.x, canvasCenter.y)
    const parentOffset =
      parentId === editor.state.currentPageId
        ? { x: 0, y: 0 }
        : editor.graph.getAbsolutePosition(parentId)
    return {
      x: center.x - parentOffset.x - component.width / 2,
      y: center.y - parentOffset.y - component.height / 2
    }
  }

  function insertAsset(asset: LocalAsset) {
    if (!asset.componentId) return
    const component = editor.graph.getNode(asset.componentId)
    if (!component) return
    const parentId = editor.state.enteredContainerId ?? editor.state.currentPageId
    const point = insertionPoint(component, parentId)
    editor.createInstanceFromComponent(asset.componentId, point.x, point.y, parentId)
    editor.requestRender()
  }

  function onDragStart(event: React.DragEvent, asset: LocalAsset) {
    if (!event.dataTransfer || !asset.componentId) return
    event.dataTransfer.setData('application/x-openweave-component', asset.componentId)
    event.dataTransfer.effectAllowed = 'copy'
  }

  function openDetails(asset: LocalAsset) {
    setSelectedAssetId(asset.id)
    setDetailsOpen(true)
  }

  function focusAsset(asset: LocalAsset) {
    void editor.focusComponent(asset.id)
  }

  function onAssetKeydown(event: React.KeyboardEvent, asset: LocalAsset) {
    if ((event.metaKey || event.ctrlKey) && event.code === 'Enter') {
      event.preventDefault()
      openDetails(asset)
      return
    }
    if (event.code === 'Enter' || event.code === 'Space') {
      event.preventDefault()
      insertAsset(asset)
    }
  }

  function insertSelectedAsset() {
    if (!selectedAsset) return
    insertAsset(selectedAsset)
    setDetailsOpen(false)
  }

  return (
    <section
      data-test-id="assets-panel"
      className="flex min-h-0 flex-1 flex-col overflow-hidden"
    >
      <div className="flex shrink-0 items-center gap-2 px-2 py-2">
        <input
          type="search"
          data-test-id="assets-search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder={panels.searchLocalComponents}
          className="min-w-0 flex-1 rounded border border-border bg-input/50 px-2 py-1 text-xs text-surface outline-none placeholder:text-muted focus:border-accent"
        />
        <div className="flex shrink-0 rounded border border-border" role="group" aria-label={panels.assetView}>
          <button
            type="button"
            data-test-id="assets-view-grid"
            title={panels.gridView}
            aria-pressed={assetView === 'grid'}
            className={`flex size-6 items-center justify-center rounded-l ${
              assetView === 'grid' ? 'bg-hover text-surface' : 'text-muted hover:text-surface'
            }`}
            onClick={() => setAssetView('grid')}
          >
            <LayoutGrid className="size-3" />
          </button>
          <button
            type="button"
            data-test-id="assets-view-list"
            title={panels.listView}
            aria-pressed={assetView === 'list'}
            className={`flex size-6 items-center justify-center rounded-r ${
              assetView === 'list' ? 'bg-hover text-surface' : 'text-muted hover:text-surface'
            }`}
            onClick={() => setAssetView('list')}
          >
            <List className="size-3" />
          </button>
        </div>
      </div>

      <div className="scrollbar-thin flex min-h-0 flex-1 flex-col overflow-y-auto px-2 pb-2">
        {assetGroups.map((group) => (
          <section key={group.pageId} className="mb-3">
            <h2 className="mb-1 px-1 text-[10px] font-medium uppercase tracking-wide text-muted">
              {group.pageName}
            </h2>
            <div className={assetView === 'grid' ? 'grid grid-cols-2 gap-2' : 'flex flex-col gap-0.5'}>
              {group.assets.map((asset) => {
                const NodeIconComp = nodeIcon(asset.node)
                return (
                  <ContextMenu.Root key={asset.id} modal={false}>
                    <ContextMenu.Trigger asChild>
                      <div
                        role="button"
                        tabIndex={0}
                        data-test-id="asset-item"
                        data-asset-id={asset.id}
                        draggable={Boolean(asset.componentId)}
                        className={`group/asset rounded text-left text-xs text-surface outline-none hover:bg-hover focus-visible:ring-1 focus-visible:ring-accent ${
                          assetView === 'grid'
                            ? 'flex min-w-0 flex-col items-center gap-1 p-1.5'
                            : 'flex w-full items-center gap-2 px-1.5 py-1'
                        }`}
                        onClick={() => insertAsset(asset)}
                        onKeyDown={(e) => onAssetKeydown(e, asset)}
                        onDragStart={(e) => onDragStart(e, asset)}
                      >
                        {asset.componentId ? (
                          <AssetThumbnail
                            nodeId={asset.componentId}
                            alt={`${asset.name} preview`}
                            size={assetView === 'grid' ? ASSET_GRID_THUMBNAIL_SIZE : ASSET_LIST_THUMBNAIL_SIZE}
                          />
                        ) : (
                          <NodeIconComp className="size-4 shrink-0 text-component" aria-hidden="true" />
                        )}
                        <span className={assetView === 'grid' ? 'w-full min-w-0' : 'min-w-0 flex-1'}>
                          <span className="flex min-w-0 items-center gap-1">
                            <span data-test-id="asset-name" className="truncate">
                              {asset.name}
                            </span>
                            {asset.sourceLibraryKey ? (
                              <span
                                data-test-id="asset-library-badge"
                                className="shrink-0 rounded bg-component/15 px-1 py-px text-[9px] font-medium uppercase text-component"
                              >
                                {panels.assetLibraryBadge}
                              </span>
                            ) : null}
                          </span>
                          {assetView === 'list' && asset.variantCount > 0 ? (
                            <span className="mt-0.5 block truncate text-[10px] text-muted">
                              {panels.componentSet} · {asset.variantCount}
                            </span>
                          ) : null}
                        </span>
                        {assetView === 'list' ? (
                          <button
                            type="button"
                            data-test-id="asset-insert"
                            title={panels.insertInstance}
                            className="flex size-6 shrink-0 items-center justify-center rounded text-muted hover:bg-hover hover:text-surface"
                            onClick={(e) => {
                              e.stopPropagation()
                              insertAsset(asset)
                            }}
                          >
                            <Plus className="size-3" />
                          </button>
                        ) : null}
                      </div>
                    </ContextMenu.Trigger>
                    <ContextMenu.Portal>
                      <ContextMenu.Content className={contextMenuCls.content}>
                        <ContextMenu.Item
                          data-test-id="asset-context-go-to-main"
                          className={contextMenuCls.item}
                          onSelect={() => focusAsset(asset)}
                        >
                          {panels.goToMainComponent}
                        </ContextMenu.Item>
                        <ContextMenu.Item
                          data-test-id="asset-context-view-details"
                          className={contextMenuCls.item}
                          onSelect={() => openDetails(asset)}
                        >
                          {panels.viewDetails}
                        </ContextMenu.Item>
                      </ContextMenu.Content>
                    </ContextMenu.Portal>
                  </ContextMenu.Root>
                )
              })}
            </div>
          </section>
        ))}

        {filteredAssets.length === 0 ? (
          <div
            data-test-id="assets-empty"
            className="flex flex-1 flex-col items-center justify-center gap-2 p-6 text-center text-muted"
          >
            <ComponentIcon className="size-5" />
            <span className="text-xs">{panels.noLocalComponents}</span>
          </div>
        ) : null}
      </div>

      {selectedAsset ? (
        <AppDialogRoot
          size="lg"
          open={detailsOpen}
          onOpenChange={setDetailsOpen}
          data-test-id="asset-details-dialog"
        >
          <AppDialogHeader
            closeLabel={dialogs.close}
            heading={
              <span className="flex min-w-0 items-center gap-2">
                {SelectedAssetIcon ? (
                  <SelectedAssetIcon className="size-4 shrink-0 text-component" aria-hidden="true" />
                ) : null}
                <span className="truncate">{selectedAsset.name}</span>
              </span>
            }
            description={
              <>
                {selectedAsset.node.type === 'COMPONENT_SET' ? panels.componentSet : panels.component}
                {selectedAsset.variantCount > 0 ? ` · ${selectedAsset.variantCount} variants` : ''}
              </>
            }
          />

          <div className="grid min-h-0 flex-1 grid-cols-[260px_1fr] gap-0 overflow-y-auto">
            <div className="border-r border-border p-4">
              <div
                data-test-id="asset-details-preview"
                className="flex h-36 items-center justify-center overflow-hidden rounded-lg border border-border bg-canvas/60"
              >
                {previewUrl ? (
                  <img
                    data-test-id="asset-details-preview-image"
                    src={previewUrl}
                    alt={`${selectedAsset.name} preview`}
                    className="max-h-[120px] max-w-[210px] object-contain"
                  />
                ) : (
                  <div className="text-center">
                    {previewLoading ? (
                      <Loader2 className="mx-auto size-5 animate-spin text-muted" />
                    ) : (
                      SelectedAssetIcon && <SelectedAssetIcon className="mx-auto size-8 text-component" />
                    )}
                    <p className="mt-2 max-w-44 truncate text-xs font-medium text-surface">
                      {selectedAsset.name}
                    </p>
                  </div>
                )}
              </div>
              <button
                type="button"
                data-test-id="asset-details-insert"
                className={`mt-3 w-full ${insertButtonCls}`}
                onClick={insertSelectedAsset}
              >
                {panels.insertInstance}
              </button>
            </div>

            <div className="min-w-0 p-4">
              {selectedAsset.description ? (
                <section className="mb-4">
                  <h3 className="text-[11px] font-medium uppercase tracking-wider text-muted">
                    {panels.description}
                  </h3>
                  <p data-test-id="asset-details-description" className="mt-1 text-xs leading-5 text-surface">
                    {selectedAsset.description}
                  </p>
                </section>
              ) : null}

              {selectedAsset.sourceLibraryKey ? (
                <section className="mb-4">
                  <h3 className="text-[11px] font-medium uppercase tracking-wider text-muted">
                    {panels.assetLibraryBadge}
                  </h3>
                  <p data-test-id="asset-details-library" className="mt-1 break-all text-xs text-muted">
                    {selectedAsset.sourceLibraryKey}
                  </p>
                </section>
              ) : null}

              {selectedAsset.docsUrl ? (
                <section className="mb-4">
                  <h3 className="text-[11px] font-medium uppercase tracking-wider text-muted">
                    {panels.documentation}
                  </h3>
                  <button
                    type="button"
                    data-test-id="asset-details-docs"
                    className="mt-1 inline-flex items-center gap-1 rounded px-1 py-0.5 text-xs text-component hover:bg-component/10"
                    onClick={() => {
                      if (selectedAsset.docsUrl) void openExternalLink(selectedAsset.docsUrl)
                    }}
                  >
                    <BookOpen className="size-3" />
                    {panels.openDocs}
                  </button>
                </section>
              ) : null}

              {selectedAsset.variants.length > 0 ? (
                <section>
                  <h3 className="text-[11px] font-medium uppercase tracking-wider text-muted">
                    {panels.properties}
                  </h3>
                  <div className="mt-2 flex flex-col gap-2">
                    {selectedAsset.variants.map((variant) => (
                      <div
                        key={variant.name}
                        data-test-id="asset-details-property"
                        className="rounded border border-border bg-input/40 px-2 py-1.5"
                      >
                        <div className="text-xs font-medium text-surface">{variant.name}</div>
                        <div className="mt-1 text-[11px] text-muted">{variant.values.join(', ')}</div>
                      </div>
                    ))}
                  </div>
                </section>
              ) : null}
            </div>
          </div>
        </AppDialogRoot>
      ) : null}
    </section>
  )
}

// src/components/assets-panel/AssetsPanel.vue
<script setup lang="ts">
import { useObjectUrl } from '@vueuse/core'
import { computed, ref, shallowRef, watch } from 'vue'
import {
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuPortal,
  ContextMenuRoot,
  ContextMenuTrigger,
  DialogClose,
  DialogTitle
} from 'reka-ui'

import type { SceneNode } from '@openweave/scene-graph'
import { useI18n } from '@openweave/vue'

import { nodeIcon } from '@/app/editor/icons'
import { useEditorStore } from '@/app/editor/active-store'
import { openExternalLink } from '@/app/shell/ui'
import AssetThumbnail from '@/components/assets-panel/AssetThumbnail.vue'
import { findAssetPage } from '@/components/assets-panel/page'
import AppInput from '@/components/ui/AppInput.vue'
import AppPlaceholder from '@/components/ui/AppPlaceholder.vue'
import { useButtonUI } from '@/components/ui/button'
import { AppDialogRoot, useDialogUI } from '@/components/ui/dialog'
import { useMenuUI } from '@/components/ui/menu'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'
import { ASSET_GRID_THUMBNAIL_SIZE, ASSET_LIST_THUMBNAIL_SIZE } from '@/constants'

type AssetView = 'grid' | 'list'

type LocalAsset = {
  id: string
  name: string
  node: SceneNode
  componentId: string | null
  variants: Array<{ name: string; values: string[] }>
  variantCount: number
  hasConflicts: boolean
  sourceLibraryKey: string | null
  description: string
  docsUrl: string | null
  pageId: string
  pageName: string
}

type AssetGroup = {
  pageId: string
  pageName: string
  assets: LocalAsset[]
}

const editor = useEditorStore()
const { panels, commands } = useI18n()
const query = ref('')
const assetView = ref<AssetView>('grid')
const detailsOpen = ref(false)
const selectedAssetId = ref<string | null>(null)
const previewBlob = shallowRef<Blob | null>(null)
const previewUrl = useObjectUrl(previewBlob)
const previewLoading = ref(false)
let previewRequestId = 0
const insertButton = useButtonUI({ tone: 'ghost', size: 'iconSm' })
const primaryButton = useButtonUI({ tone: 'accent', size: 'md' })
const dialog = useDialogUI()
const contextMenu = useMenuUI({ content: 'min-w-44' })
const viewOptions = computed(() => [
  { value: 'grid', label: panels.value.gridView },
  { value: 'list', label: panels.value.listView }
])
const viewUI = { root: 'w-16', item: 'px-1' }

function componentSetVariantInfo(componentSetId: string) {
  return [...editor.collectVariantOptions(componentSetId)].map(([name, values]) => ({
    name,
    values: [...values].sort((a, b) => a.localeCompare(b))
  }))
}

const graphNodes = computed(() => ({
  sceneVersion: editor.state.sceneVersion,
  nodes: [...editor.graph.nodes.values()]
}))

const assetNodes = computed(() =>
  graphNodes.value.nodes.filter(
    (node) => node.type === 'COMPONENT' || node.type === 'COMPONENT_SET'
  )
)

const pageByNodeId = computed(() => {
  const pages = new Map<string, { id: string; name: string }>()
  for (const node of assetNodes.value) {
    const page = findAssetPage(node, editor.graph)
    if (page) pages.set(node.id, { id: page.id, name: page.name })
  }
  return pages
})

const assets = computed<LocalAsset[]>(() => {
  return assetNodes.value
    .filter((node) => {
      if (node.type === 'COMPONENT_SET') return true
      const parent = node.parentId ? editor.graph.getNode(node.parentId) : null
      return parent?.type !== 'COMPONENT_SET'
    })
    .map((node) => {
      const defaultVariant =
        node.type === 'COMPONENT_SET' ? editor.getDefaultVariantForComponentSet(node.id) : node
      const conflicts =
        node.type === 'COMPONENT_SET' ? editor.getComponentSetVariantConflicts(node.id) : []
      const variants = node.type === 'COMPONENT_SET' ? componentSetVariantInfo(node.id) : []
      const page = pageByNodeId.value.get(node.id)
      return {
        id: node.id,
        name: node.name,
        node,
        componentId: defaultVariant?.id ?? null,
        variants,
        variantCount: node.type === 'COMPONENT_SET' ? node.childIds.length : 0,
        hasConflicts: conflicts.length > 0,
        sourceLibraryKey: node.sourceLibraryKey,
        description: node.symbolDescription,
        docsUrl: node.symbolLinks[0]?.uri ?? null,
        pageId: page?.id ?? editor.state.currentPageId,
        pageName: page?.name ?? panels.value.page
      }
    })
    .sort((a, b) => a.name.localeCompare(b.name))
})

const filteredAssets = computed(() => {
  const normalized = query.value.trim().toLowerCase()
  if (!normalized) return assets.value
  return assets.value.filter((asset) => asset.name.toLowerCase().includes(normalized))
})

const assetGroups = computed<AssetGroup[]>(() => {
  const groups = new Map<string, AssetGroup>()
  for (const asset of filteredAssets.value) {
    const group = groups.get(asset.pageId) ?? {
      pageId: asset.pageId,
      pageName: asset.pageName,
      assets: []
    }
    group.assets.push(asset)
    groups.set(asset.pageId, group)
  }
  return [...groups.values()].sort((a, b) => a.pageName.localeCompare(b.pageName))
})

const selectedAsset = computed(
  () => assets.value.find((asset) => asset.id === selectedAssetId.value) ?? null
)
const selectedPreviewNodeId = computed(() => selectedAsset.value?.componentId ?? null)

function clearPreview() {
  previewBlob.value = null
}

async function updatePreview() {
  const requestId = ++previewRequestId
  const nodeId = selectedPreviewNodeId.value
  if (!detailsOpen.value || !nodeId) {
    clearPreview()
    return
  }

  const node = editor.getNode(nodeId)
  if (!node) {
    clearPreview()
    return
  }

  previewLoading.value = true
  try {
    const maxSize = Math.max(node.width, node.height, 1)
    const scale = Math.min(176 / maxSize, 2)
    const data = await editor.renderExportImage([nodeId], scale, 'PNG', selectedAsset.value?.pageId)
    if (requestId !== previewRequestId) return
    previewBlob.value = data ? new Blob([data], { type: 'image/png' }) : null
  } catch {
    if (requestId === previewRequestId) clearPreview()
  } finally {
    if (requestId === previewRequestId) previewLoading.value = false
  }
}

watch([detailsOpen, selectedPreviewNodeId, () => editor.state.sceneVersion], updatePreview, {
  flush: 'post'
})

function openDetails(asset: LocalAsset) {
  selectedAssetId.value = asset.id
  detailsOpen.value = true
}

function insertionPoint(component: SceneNode, parentId: string) {
  const canvasCenter = editor.viewportCanvasCenter()
  const center = editor.screenToCanvas(canvasCenter.x, canvasCenter.y)
  const parentOffset =
    parentId === editor.state.currentPageId
      ? { x: 0, y: 0 }
      : editor.graph.getAbsolutePosition(parentId)
  return {
    x: center.x - parentOffset.x - component.width / 2,
    y: center.y - parentOffset.y - component.height / 2
  }
}

function insertAsset(asset: LocalAsset) {
  if (!asset.componentId) return
  const component = editor.graph.getNode(asset.componentId)
  if (!component) return
  const parentId = editor.state.enteredContainerId ?? editor.state.currentPageId
  const point = insertionPoint(component, parentId)
  editor.createInstanceFromComponent(asset.componentId, point.x, point.y, parentId)
  editor.requestRender()
}

function onDragStart(event: DragEvent, asset: LocalAsset) {
  if (!event.dataTransfer || !asset.componentId) return
  event.dataTransfer.setData('application/x-openweave-component', asset.componentId)
  event.dataTransfer.effectAllowed = 'copy'
}

function focusAsset(asset: LocalAsset) {
  void editor.focusComponent(asset.id)
}

function onAssetKeydown(event: KeyboardEvent, asset: LocalAsset) {
  if ((event.metaKey || event.ctrlKey) && event.code === 'Enter') {
    event.preventDefault()
    openDetails(asset)
    return
  }
  if (event.code === 'Enter' || event.code === 'Space') {
    event.preventDefault()
    insertAsset(asset)
  }
}

function insertSelectedAsset() {
  if (!selectedAsset.value) return
  insertAsset(selectedAsset.value)
  detailsOpen.value = false
}
</script>

<template>
  <section data-test-id="assets-panel" class="flex min-h-0 flex-1 flex-col overflow-hidden">
    <div class="flex shrink-0 items-center gap-2 px-2 py-2">
      <AppInput
        v-model="query"
        type="search"
        data-test-id="assets-search"
        size="sm"
        class="min-w-0 flex-1"
        :placeholder="panels.searchLocalComponents"
      />
      <SegmentedControl
        v-model="assetView"
        data-test-id="assets-view-toggle"
        :options="viewOptions"
        :label="panels.assetView"
        :ui="viewUI"
      >
        <template #option="{ option }">
          <icon-lucide-layout-grid v-if="option.value === 'grid'" class="size-3" />
          <icon-lucide-list v-else class="size-3" />
        </template>
      </SegmentedControl>
    </div>

    <div class="scrollbar-thin flex min-h-0 flex-1 flex-col overflow-y-auto px-2 pb-2">
      <section v-for="group in assetGroups" :key="group.pageId" class="mb-3">
        <h2 class="mb-1 px-1 text-[10px] font-medium tracking-wide text-muted uppercase">
          {{ group.pageName }}
        </h2>
        <div :class="assetView === 'grid' ? 'grid grid-cols-2 gap-2' : 'flex flex-col gap-0.5'">
          <ContextMenuRoot v-for="asset in group.assets" :key="asset.id">
            <ContextMenuTrigger as-child>
              <div
                role="button"
                tabindex="0"
                data-test-id="asset-item"
                :data-asset-id="asset.id"
                :draggable="!!asset.componentId"
                :class="[
                  'group/asset rounded text-left text-xs text-surface outline-none hover:bg-hover focus-visible:ring-1 focus-visible:ring-accent',
                  assetView === 'grid'
                    ? 'flex min-w-0 flex-col items-center gap-1 p-1.5'
                    : 'flex w-full items-center gap-2 px-1.5 py-1'
                ]"
                @click="openDetails(asset)"
                @keydown="onAssetKeydown($event, asset)"
                @dragstart="onDragStart($event, asset)"
              >
                <AssetThumbnail
                  v-if="asset.componentId"
                  :node-id="asset.componentId"
                  :alt="`${asset.name} preview`"
                  :size="
                    assetView === 'grid' ? ASSET_GRID_THUMBNAIL_SIZE : ASSET_LIST_THUMBNAIL_SIZE
                  "
                />
                <component
                  :is="nodeIcon(asset.node)"
                  v-else
                  class="size-4 shrink-0 text-component"
                  aria-hidden="true"
                />
                <span :class="assetView === 'grid' ? 'w-full min-w-0' : 'min-w-0 flex-1'">
                  <span class="flex min-w-0 items-center gap-1">
                    <span data-test-id="asset-name" class="truncate">{{ asset.name }}</span>
                    <span
                      v-if="asset.sourceLibraryKey"
                      data-test-id="asset-library-badge"
                      class="shrink-0 rounded bg-component/15 px-1 py-px text-[9px] font-medium text-component uppercase"
                    >
                      {{ panels.assetLibraryBadge }}
                    </span>
                  </span>
                  <span
                    v-if="assetView === 'list' && asset.variants.length > 0"
                    data-test-id="asset-variant-summary"
                    class="mt-0.5 block truncate text-[10px] text-muted"
                  >
                    {{
                      panels.assetVariantSummary({
                        count: asset.variantCount,
                        names: asset.variants.map((variant) => variant.name).join(', ')
                      })
                    }}
                  </span>
                  <span
                    v-if="assetView === 'list' && asset.description"
                    data-test-id="asset-description"
                    class="mt-0.5 block truncate text-[10px] text-muted"
                  >
                    {{ asset.description }}
                  </span>
                  <span
                    v-if="assetView === 'list' && asset.hasConflicts"
                    data-test-id="asset-variant-conflict"
                    class="mt-0.5 block truncate text-[10px] text-[var(--color-warning-text)]"
                  >
                    {{ panels.duplicateVariantValues }}
                  </span>
                </span>
                <div v-if="assetView === 'list'" class="flex shrink-0 items-center">
                  <Tip v-if="asset.docsUrl" :label="panels.openDocumentation">
                    <button
                      type="button"
                      :class="insertButton.base"
                      data-test-id="asset-docs"
                      @pointerdown.stop
                      @click.stop="asset.docsUrl ? openExternalLink(asset.docsUrl) : undefined"
                    >
                      <icon-lucide-book-open class="size-3" />
                    </button>
                  </Tip>
                  <Tip :label="commands.createInstance">
                    <button
                      type="button"
                      :class="insertButton.base"
                      data-test-id="asset-insert"
                      @pointerdown.stop
                      @click.stop="insertAsset(asset)"
                    >
                      <icon-lucide-plus class="size-3" />
                    </button>
                  </Tip>
                </div>
              </div>
            </ContextMenuTrigger>
            <ContextMenuPortal>
              <ContextMenuContent :class="contextMenu.content">
                <ContextMenuItem
                  data-test-id="asset-context-go-to-main"
                  :class="contextMenu.item"
                  @select="focusAsset(asset)"
                >
                  {{ panels.goToMainComponent }}
                </ContextMenuItem>
                <ContextMenuItem
                  data-test-id="asset-context-view-details"
                  :class="contextMenu.item"
                  @select="openDetails(asset)"
                >
                  {{ panels.viewDetails }}
                </ContextMenuItem>
              </ContextMenuContent>
            </ContextMenuPortal>
          </ContextMenuRoot>
        </div>
      </section>

      <AppPlaceholder
        v-if="filteredAssets.length === 0"
        data-test-id="assets-empty"
        :label="panels.noLocalComponents"
        size="compact"
      >
        <template #icon>
          <icon-lucide-component class="size-4" />
        </template>
      </AppPlaceholder>
    </div>

    <AppDialogRoot
      v-if="selectedAsset"
      v-model:open="detailsOpen"
      size="lg"
      data-test-id="asset-details-dialog"
    >
      <div class="flex items-center justify-between border-b border-border px-4 py-3">
        <div class="flex min-w-0 items-center gap-2">
          <component :is="nodeIcon(selectedAsset.node)" class="size-4 shrink-0 text-component" />
          <div class="min-w-0">
            <DialogTitle :class="dialog.title" class="truncate">{{
              selectedAsset.name
            }}</DialogTitle>
            <p class="mt-0.5 text-[11px] text-muted">
              {{
                selectedAsset.node.type === 'COMPONENT_SET' ? panels.componentSet : panels.component
              }}
              <span v-if="selectedAsset.variantCount > 0">
                · {{ selectedAsset.variantCount }} variants</span
              >
            </p>
          </div>
        </div>
        <DialogClose
          data-test-id="asset-details-close"
          class="flex size-7 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
        >
          <icon-lucide-x class="size-4" />
        </DialogClose>
      </div>

      <div class="grid min-h-0 grid-cols-[260px_1fr] gap-0">
        <div class="border-r border-border p-4">
          <div
            data-test-id="asset-details-preview"
            class="flex h-36 items-center justify-center overflow-hidden rounded-lg border border-border bg-canvas/60"
          >
            <img
              v-if="previewUrl"
              data-test-id="asset-details-preview-image"
              :src="previewUrl"
              :alt="`${selectedAsset.name} preview`"
              class="max-h-[120px] max-w-[210px] object-contain"
            />
            <div v-else class="text-center">
              <icon-lucide-loader-2
                v-if="previewLoading"
                class="mx-auto size-5 animate-spin text-muted"
              />
              <component
                v-else
                :is="nodeIcon(selectedAsset.node)"
                class="mx-auto size-8 text-component"
              />
              <p class="mt-2 max-w-44 truncate text-xs font-medium text-surface">
                {{ selectedAsset.name }}
              </p>
            </div>
          </div>
          <button
            data-test-id="asset-details-insert"
            :class="primaryButton.base"
            class="mt-3 w-full"
            @click="insertSelectedAsset"
          >
            {{ panels.insertInstance }}
          </button>
        </div>

        <div class="min-w-0 p-4">
          <section v-if="selectedAsset.description" class="mb-4">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.description }}
            </h3>
            <p data-test-id="asset-details-description" class="mt-1 text-xs leading-5 text-surface">
              {{ selectedAsset.description }}
            </p>
          </section>

          <section v-if="selectedAsset.sourceLibraryKey" class="mb-4">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.assetLibraryBadge }}
            </h3>
            <p data-test-id="asset-details-library" class="mt-1 break-all text-xs text-muted">
              {{ selectedAsset.sourceLibraryKey }}
            </p>
          </section>

          <section v-if="selectedAsset.docsUrl" class="mb-4">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.documentation }}
            </h3>
            <button
              data-test-id="asset-details-docs"
              class="mt-1 inline-flex items-center gap-1 rounded px-1 py-0.5 text-xs text-component hover:bg-component/10"
              @click="selectedAsset.docsUrl ? openExternalLink(selectedAsset.docsUrl) : undefined"
            >
              <icon-lucide-book-open class="size-3" />
              {{ panels.openDocs }}
            </button>
          </section>

          <section v-if="selectedAsset.variants.length > 0">
            <h3 class="text-[11px] font-medium tracking-wider text-muted uppercase">
              {{ panels.properties }}
            </h3>
            <div class="mt-2 flex flex-col gap-2">
              <div
                v-for="variant in selectedAsset.variants"
                :key="variant.name"
                data-test-id="asset-details-property"
                class="rounded border border-border bg-input/40 px-2 py-1.5"
              >
                <div class="text-xs font-medium text-surface">{{ variant.name }}</div>
                <div class="mt-1 text-[11px] text-muted">{{ variant.values.join(', ') }}</div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </AppDialogRoot>
  </section>
</template>
