// src/components/toolbar/ToolbarActionGroup.tsx
import React from 'react'
import { tv } from 'tailwind-variants'

import type { ToolbarActionItem, ToolbarUI } from '@/components/toolbar/types'
import toolbarTheme from '@/theme/toolbar'

interface ToolbarActionGroupProps {
  actions: ToolbarActionItem[]
  testPrefix: string
  ui?: ToolbarUI
  onAction: (item: ToolbarActionItem) => void
}

const styles = tv(toolbarTheme)()

export default function ToolbarActionGroup({
  actions,
  testPrefix,
  ui,
  onAction
}: ToolbarActionGroupProps) {
  return (
    <>
      {actions.map((item) => {
        const ActionIcon = item.icon
        return (
          <button
            key={item.label}
            data-test-id={`${testPrefix}-${item.label.toLowerCase()}`}
            className={styles.action({ className: ui?.action })}
            onClick={() => onAction(item)}
          >
            <ActionIcon className={styles.actionIcon({ className: ui?.actionIcon })} />
          </button>
        )
      })}
    </>
  )
}

// src/components/Toolbar/ToolbarActionGroup.vue
<script setup lang="ts">
import { tv } from 'tailwind-variants'

import toolbarTheme from '@/theme/toolbar'
import { vTestId } from '@openweave/vue'

import type { ToolbarActionItem, ToolbarUI } from '@/components/Toolbar/types'

const { actions, testPrefix, ui } = defineProps<{
  actions: ToolbarActionItem[]
  testPrefix: string
  ui?: ToolbarUI
}>()

const styles = tv(toolbarTheme)()

const emit = defineEmits<{
  action: [item: ToolbarActionItem]
}>()
</script>

<template>
  <button
    v-for="item in actions"
    :key="item.label"
    v-test-id="`${testPrefix}-${item.label.toLowerCase()}`"
    :class="styles.action({ class: ui?.action })"
    @click="emit('action', item)"
  >
    <component :is="item.icon" :class="styles.actionIcon({ class: ui?.actionIcon })" />
  </button>
</template>
