// src/components/properties/AppearanceSection.tsx
import { Eye, EyeOff, SquareRoundCorner, Squircle, Blend } from 'lucide-react'
import React from 'react'

import {
  useAppearance,
  MIXED,
  useI18n,
  BindableValueRoot,
  useBooleanBindingProvider
} from '@openweave/react'
import type { BlendMode } from '@openweave/scene-graph'

import NumberField from '@/components/inputs/NumberField'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker'
import { useBlendModeOptions } from '@/components/properties/blend-mode/use'
import VariableNumberField from '@/components/properties/LayoutSection/VariableNumberField'

const labelClass = 'text-[10px] text-muted'
const iconButtonClass =
  'flex size-6 shrink-0 cursor-pointer items-center justify-center rounded text-muted transition-colors hover:bg-hover hover:text-surface data-[active=true]:bg-hover data-[active=true]:text-surface'

export function AppearanceSection() {
  const { panels, dialogs } = useI18n()
  const booleanProvider = useBooleanBindingProvider()
  const {
    node,
    active,
    isMulti,
    hasCornerRadius,
    independentCorners,
    showIndependentCorners,
    cornerRadiusValue,
    cornerSmoothingPercent,
    opacityPercent,
    blendModeValue,
    visibilityState,
    updateProp,
    commitProp,
    setBlendMode,
    toggleVisibility,
    toggleIndependentCorners,
    updateCornerProp,
    commitCornerProp
  } = useAppearance()

  const blendOptions = useBlendModeOptions(true)

  if (!active) return null

  const corners =
    !isMulti && node
      ? ([
          ['TL', 'topLeftRadius', node.topLeftRadius],
          ['TR', 'topRightRadius', node.topRightRadius],
          ['BL', 'bottomLeftRadius', node.bottomLeftRadius],
          ['BR', 'bottomRightRadius', node.bottomRightRadius]
        ] as const)
      : []

  return (
    <section
      aria-label={panels.appearance}
      className="space-y-1.5 border-b border-border px-3 pb-3"
      data-test-id="appearance-section"
    >
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-semibold text-muted uppercase tracking-wider">
          {panels.appearance}
        </span>

        {node && !isMulti && visibilityState !== 'mixed' ? (
          <BindableValueRoot
            provider={booleanProvider}
            targets={[{ nodeId: node.id, path: 'visible' }]}
            value={visibilityState === 'visible'}
            batchLabel="Change visibility"
          >
            {(binding) => (
              <div className="flex items-center gap-0.5">
                <button
                  type="button"
                  aria-label={panels.toggleVisibility}
                  data-active={visibilityState === 'hidden'}
                  className={`${iconButtonClass} ${binding.state === 'bound' ? 'bg-input/50 text-accent' : ''}`}
                  onClick={toggleVisibility}
                >
                  {visibilityState === 'visible' ? (
                    <Eye className="size-3.5" />
                  ) : (
                    <EyeOff className="size-3.5" />
                  )}
                </button>
                <VariableBindingPicker
                  triggerLabel={panels.applyVariable}
                  searchPlaceholder={dialogs.search}
                  emptyLabel={panels.noVariablesFound}
                  detachLabel={panels.detachVariable}
                  createLabel="Create boolean variable"
                  createNamePlaceholder={panels.variableName}
                  createSubmitLabel={panels.create}
                />
              </div>
            )}
          </BindableValueRoot>
        ) : (
          <button
            type="button"
            aria-label={panels.toggleVisibility}
            data-active={visibilityState === 'hidden'}
            className={iconButtonClass}
            onClick={toggleVisibility}
          >
            {visibilityState === 'visible' ? (
              <Eye className="size-3.5" />
            ) : visibilityState === 'hidden' ? (
              <EyeOff className="size-3.5" />
            ) : (
              <Eye className="size-3.5 opacity-50" />
            )}
          </button>
        )}
      </div>

      <div className="grid grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)] gap-1.5">
        <label className="flex min-w-0 flex-col gap-1">
          <span className={labelClass}>{panels.blendMode}</span>
          <select
            aria-label={panels.blendMode}
            className="h-6 w-full min-w-0 rounded border border-border bg-input/50 px-1.5 text-[11px] text-surface outline-none focus:border-accent"
            value={typeof blendModeValue === 'string' ? blendModeValue : 'MIXED'}
            onChange={(e) => {
              if (e.target.value !== 'MIXED') setBlendMode(e.target.value as BlendMode)
            }}
          >
            {blendModeValue === MIXED && <option value="MIXED">{panels.mixed}</option>}
            {blendOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </label>
        <label className="flex min-w-0 flex-col gap-1">
          <span className={labelClass}>{panels.opacity}</span>
          {typeof opacityPercent === 'number' && !isMulti && node ? (
            <VariableNumberField
              ariaLabel={panels.opacity}
              nodeId={node.id}
              bindingPath="opacity"
              value={opacityPercent}
              min={0}
              max={100}
              suffix="%"
              icon={<Blend className="size-3 shrink-0 text-muted" />}
              onChange={(v) => updateProp('opacity', v / 100)}
              onCommit={(v) => commitProp('opacity', v / 100, v / 100)}
            />
          ) : (
            <NumberField
              ariaLabel={panels.opacity}
              value={opacityPercent}
              min={0}
              max={100}
              suffix="%"
              icon={<Blend className="size-3 shrink-0 text-muted" />}
              onChange={(v) => updateProp('opacity', v / 100)}
              onCommit={(v) => commitProp('opacity', v / 100, v / 100)}
            />
          )}
        </label>
      </div>

      {hasCornerRadius && !showIndependentCorners && (
        <div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-1.5">
          <label className="flex min-w-0 flex-col gap-1">
            <span className={labelClass}>{panels.radius}</span>
            {typeof cornerRadiusValue === 'number' && !isMulti && node ? (
              <VariableNumberField
                ariaLabel={panels.radius}
                nodeId={node.id}
                bindingPath="cornerRadius"
                value={cornerRadiusValue}
                min={0}
                icon={<SquareRoundCorner className="size-3 shrink-0 text-muted" />}
                onChange={(v) => updateProp('cornerRadius', v)}
                onCommit={(v) => commitProp('cornerRadius', v, v)}
              />
            ) : (
              <NumberField
                ariaLabel={panels.radius}
                value={cornerRadiusValue}
                min={0}
                icon={<SquareRoundCorner className="size-3 shrink-0 text-muted" />}
                onChange={(v) => updateProp('cornerRadius', v)}
                onCommit={(v) => commitProp('cornerRadius', v, v)}
              />
            )}
          </label>
          <button
            type="button"
            aria-label={panels.independentCornerRadii}
            data-active={independentCorners === true}
            className={iconButtonClass}
            onClick={toggleIndependentCorners}
          >
            <SquareRoundCorner className="size-3" />
          </button>
        </div>
      )}

      {hasCornerRadius && showIndependentCorners && !isMulti && node && (
        <div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] gap-1.5" data-corner-grid>
          <div className="col-span-2 grid grid-cols-2 gap-1.5">
            {corners.map(([label, key, value]) => (
              <label key={key} className="flex min-w-0 flex-col gap-1">
                <span className={labelClass}>{label}</span>
                {typeof value === 'number' ? (
                  <VariableNumberField
                    ariaLabel={`${panels.radius} ${label}`}
                    nodeId={node.id}
                    bindingPath={key as any}
                    value={value}
                    min={0}
                    onChange={(v) => updateCornerProp(key, v)}
                    onCommit={(v) => commitCornerProp(key, v, v)}
                  />
                ) : (
                  <NumberField
                    ariaLabel={`${panels.radius} ${label}`}
                    value={value}
                    min={0}
                    onChange={(v) => updateCornerProp(key, v)}
                    onCommit={(v) => commitCornerProp(key, v, v)}
                  />
                )}
              </label>
            ))}
          </div>
          <button
            type="button"
            aria-label={panels.independentCornerRadii}
            data-active
            className={`${iconButtonClass} self-start`}
            onClick={toggleIndependentCorners}
          >
            <SquareRoundCorner className="size-3" />
          </button>
        </div>
      )}

      {hasCornerRadius && (
        <label className="flex w-1/2 min-w-0 flex-col gap-1 pr-1">
          <span className={labelClass}>{panels.cornerSmoothing}</span>
          <NumberField
            ariaLabel={panels.cornerSmoothing}
            dataProperty="corner-smoothing"
            value={cornerSmoothingPercent}
            min={0}
            max={100}
            suffix="%"
            icon={<Squircle className="size-3 shrink-0 text-muted" />}
            onChange={(v) => updateCornerProp('cornerSmoothing', v / 100)}
            onCommit={(v) => commitCornerProp('cornerSmoothing', v / 100, v / 100)}
          />
        </label>
      )}
    </section>
  )
}

export default AppearanceSection

// src/components/properties/AppearanceSection.vue
<script setup lang="ts">
import { AppearanceControlsRoot, MIXED, useI18n } from '@openweave/vue'

import NumberField from '@/components/inputs/NumberField.vue'
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import { useBlendModeOptions } from '@/components/properties/blend-mode/use'
import AppSelect from '@/components/ui/AppSelect.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

import type { BlendMode } from '@openweave/scene-graph'

const { panels } = useI18n()
type BlendModeSelectValue = BlendMode | 'MIXED'

const baseBlendModeOptions = useBlendModeOptions(true)

function blendModeOptions(value: BlendMode | typeof MIXED) {
  return value === MIXED
    ? [{ value: 'MIXED' as const, label: panels.value.mixed }, ...baseBlendModeOptions.value]
    : baseBlendModeOptions.value
}
</script>

<template>
  <AppearanceControlsRoot
    v-slot="{
      node,
      isMulti,
      active,
      hasCornerRadius,
      independentCorners,
      showIndependentCorners,
      cornerRadiusValue,
      cornerSmoothingPercent,
      opacityPercent,
      blendModeValue,
      visibilityState,
      actions
    }"
  >
    <PanelSection v-if="active" :label="panels.appearance">
      <template #actions>
        <IconButton
          :label="panels.toggleVisibility"
          :active="visibilityState === 'hidden'"
          @click="actions.toggleVisibility"
        >
          <icon-lucide-eye v-if="visibilityState === 'visible'" class="size-3.5" />
          <icon-lucide-eye-off v-else-if="visibilityState === 'hidden'" class="size-3.5" />
          <icon-lucide-eye v-else class="size-3.5 opacity-50" />
        </IconButton>
      </template>

      <PanelGrid :columns="2" distribution="wide-first">
        <PanelFieldGroup :label="panels.blendMode">
          <AppSelect
            :model-value="blendModeValue === MIXED ? 'MIXED' : blendModeValue"
            class="w-full"
            :label="panels.blendMode"
            :options="blendModeOptions(blendModeValue)"
            @update:model-value="
              (value: BlendModeSelectValue) => value !== 'MIXED' && actions.setBlendMode(value)
            "
          />
        </PanelFieldGroup>

        <PanelFieldGroup :label="panels.opacity">
          <VariableNumberField
            v-if="node && !isMulti"
            suffix="%"
            :aria-label="panels.opacity"
            :model-value="opacityPercent"
            :min="0"
            :max="100"
            :node-id="node.id"
            binding-path="opacity"
            @update:model-value="actions.updateProp('opacity', $event / 100)"
            @commit="(v: number, p: number) => actions.commitProp('opacity', v / 100, p / 100)"
          >
            <template #icon>
              <icon-lucide-blend class="size-3" />
            </template>
          </VariableNumberField>
          <NumberField
            v-else
            suffix="%"
            data-property="opacity"
            :aria-label="panels.opacity"
            :model-value="opacityPercent"
            :min="0"
            :max="100"
            @update:model-value="actions.updateProp('opacity', $event / 100)"
            @commit="(v: number, p: number) => actions.commitProp('opacity', v / 100, p / 100)"
          >
            <template #icon>
              <icon-lucide-blend class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
      </PanelGrid>

      <PanelGrid v-if="hasCornerRadius && !showIndependentCorners" :columns="2" class="mt-1.5">
        <PanelFieldGroup :label="panels.radius">
          <VariableNumberField
            v-if="node && !isMulti"
            :aria-label="panels.radius"
            :model-value="cornerRadiusValue"
            :min="0"
            :node-id="node.id"
            binding-path="cornerRadius"
            @update:model-value="actions.updateProp('cornerRadius', $event)"
            @commit="(v: number, p: number) => actions.commitProp('cornerRadius', v, p)"
          >
            <template #icon>
              <icon-lucide-square-round-corner class="size-3" />
            </template>
          </VariableNumberField>
          <NumberField
            v-else
            data-property="cornerRadius"
            :aria-label="panels.radius"
            :model-value="cornerRadiusValue"
            :min="0"
            @update:model-value="actions.updateProp('cornerRadius', $event)"
            @commit="(v: number, p: number) => actions.commitProp('cornerRadius', v, p)"
          >
            <template #icon>
              <icon-lucide-square-round-corner class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
        <div class="flex h-6 items-center justify-end">
          <IconButton
            :label="panels.independentCornerRadii"
            size="md"
            :active="independentCorners === true"
            @click="actions.toggleIndependentCorners"
          >
            <icon-lucide-square-round-corner class="size-3" />
          </IconButton>
        </div>
      </PanelGrid>

      <PanelGrid
        v-else-if="hasCornerRadius && !isMulti && node"
        :columns="2"
        class="mt-1.5 [&>[data-slot=actions]]:self-start"
        data-corner-grid
      >
        <VariableNumberField
          label="TL"
          :model-value="node.topLeftRadius"
          :min="0"
          :node-id="node.id"
          binding-path="topLeftRadius"
          @update:model-value="actions.updateCornerProp('topLeftRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('topLeftRadius', v, p)"
        />
        <VariableNumberField
          label="TR"
          :model-value="node.topRightRadius"
          :min="0"
          :node-id="node.id"
          binding-path="topRightRadius"
          @update:model-value="actions.updateCornerProp('topRightRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('topRightRadius', v, p)"
        />
        <VariableNumberField
          label="BL"
          :model-value="node.bottomLeftRadius"
          :min="0"
          :node-id="node.id"
          binding-path="bottomLeftRadius"
          @update:model-value="actions.updateCornerProp('bottomLeftRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('bottomLeftRadius', v, p)"
        />
        <VariableNumberField
          label="BR"
          :model-value="node.bottomRightRadius"
          :min="0"
          :node-id="node.id"
          binding-path="bottomRightRadius"
          @update:model-value="actions.updateCornerProp('bottomRightRadius', $event)"
          @commit="(v: number, p: number) => actions.commitCornerProp('bottomRightRadius', v, p)"
        />
        <template #actions>
          <IconButton
            :label="panels.independentCornerRadii"
            size="md"
            active
            @click="actions.toggleIndependentCorners"
          >
            <icon-lucide-square-round-corner class="size-3" />
          </IconButton>
        </template>
      </PanelGrid>

      <PanelGrid v-if="hasCornerRadius" :columns="2" class="mt-1.5">
        <PanelFieldGroup :label="panels.cornerSmoothing">
          <NumberField
            suffix="%"
            :model-value="cornerSmoothingPercent"
            :min="0"
            :max="100"
            :aria-label="panels.cornerSmoothing"
            data-property="corner-smoothing"
            @update:model-value="actions.updateCornerProp('cornerSmoothing', $event / 100)"
            @commit="
              (v: number, p: number) =>
                actions.commitCornerProp('cornerSmoothing', v / 100, p / 100)
            "
          >
            <template #icon>
              <icon-lucide-squircle class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
      </PanelGrid>
    </PanelSection>
  </AppearanceControlsRoot>
</template>
