// src/components/properties/FillSection.vue
<script setup lang="ts">
import {
  BindableValueRoot,
  useColorBindingProvider,
  useFillControls,
  useI18n,
  useOkHCL
} from '@openweave/vue'

import FillPicker from '@/components/fill-picker/FillPicker.vue'
import PropertyItemRow from '@/components/properties/item-list/PropertyItemRow.vue'
import PaintField from '@/components/properties/paint/PaintField.vue'
import PaintValue from '@/components/properties/paint/PaintValue.vue'
import {
  applyPaintMutation,
  cancelPaintMutation,
  commitPaintMutation,
  paintBindingTargets
} from '@/components/properties/paint/binding'
import { fillLabel } from '@/components/properties/fill-label'
import { createFillOkhclAdapter } from '@/components/properties/paint/okhcl'
import {
  commitDiscretePropertyListChange,
  useBlendModeOptions
} from '@/components/properties/blend-mode/use'
import PropertyListRoot from '@/components/properties/PropertyListRoot.vue'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField.vue'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

import { colorToHexRaw } from '@openweave/core/color'
import type { Fill } from '@openweave/scene-graph'
import type { Color } from '@openweave/scene-graph/primitives'
import type { BindableValueActions } from '@openweave/vue'

const fillCtx = useFillControls()
const okhcl = useOkHCL()
const colorProvider = useColorBindingProvider()
const { panels, dialogs } = useI18n()
const blendModeOptions = useBlendModeOptions()

function displayFill(fill: Fill, resolvedColor: Color | undefined): Fill {
  return fill.type === 'SOLID' && resolvedColor ? { ...fill, color: resolvedColor } : fill
}

function updatePickerFill(
  binding: BindableValueActions<Color>,
  flush: () => void,
  nextFill: Fill,
  update: (fill: Fill) => void
) {
  applyPaintMutation(binding, flush, () => update(nextFill))
}

function updateSolidColor(
  binding: BindableValueActions<Color>,
  flush: () => void,
  fill: Fill,
  color: Color,
  update: (fill: Fill) => void
) {
  if (fill.type !== 'SOLID') return
  if (applyPaintMutation(binding, flush, () => update({ ...fill, color })))
    commitPaintMutation(binding)
}
</script>

<template>
  <PropertyListRoot
    v-slot="{ items, isMixed, activeNode, selectedNodeIds, flush, actions }"
    prop-key="fills"
    :label="panels.fill"
  >
    <PanelSection :label="panels.fill" :empty="!isMixed && items.length === 0">
      <template #actions>
        <IconButton :label="panels.addFill" @click="actions.add({ ...fillCtx.defaultFill })">
          <icon-lucide-plus class="size-3.5" />
        </IconButton>
      </template>

      <SharedStyleField kind="fill" :label="panels.fillStyle" />

      <p v-if="isMixed" class="text-[11px] text-muted">{{ panels.mixedFillsHelp }}</p>

      <div v-for="(fill, index) in items" :key="`${index}:${fill.visible ? 'visible' : 'hidden'}`">
        <PropertyItemRow
          class="items-start"
          prop-key="fills"
          :index="index"
          :visibility-label="panels.toggleVisibility"
          :remove-label="panels.removeFill"
        >
          <BindableValueRoot
            v-slot="binding"
            :provider="colorProvider"
            :targets="paintBindingTargets(selectedNodeIds, 'fills', index)"
            :value="fill.color"
            batch-label="Change fill color"
          >
            <PaintField
              class="w-full flex-none"
              :opacity="fill.opacity"
              :opacity-label="panels.opacity"
              @update:opacity="actions.patch(index, { opacity: $event })"
            >
              <template #preview>
                <FillPicker
                  :fill="displayFill(fill, binding.resolvedValue)"
                  :okhcl="createFillOkhclAdapter(okhcl, activeNode, index)"
                  @update="
                    updatePickerFill(binding.actions, flush, $event, (next) =>
                      actions.update(index, next)
                    )
                  "
                  @open-change="!$event && commitPaintMutation(binding.actions)"
                  @cancel="cancelPaintMutation(binding.actions)"
                />
              </template>

              <template #value>
                <PaintValue
                  v-if="fill.type === 'SOLID'"
                  :color="fill.color"
                  :resolved-color="binding.resolvedValue"
                  :variable-name="binding.variable?.name"
                  :label="panels.fill"
                  @update="
                    updateSolidColor(binding.actions, flush, fill, $event, (next) =>
                      actions.update(index, next)
                    )
                  "
                />
                <span v-else class="min-w-0 flex-1 truncate font-mono text-xs text-surface">
                  {{ fillLabel(fill) }}
                </span>
              </template>

              <template v-if="fill.type === 'SOLID'" #binding>
                <VariableBindingPicker
                  :trigger-label="panels.applyVariable"
                  :search-placeholder="dialogs.search"
                  :empty-label="panels.noVariablesFound"
                  :detach-label="panels.detachVariable"
                  :create-label="
                    panels.createColorVariable({ value: `#${colorToHexRaw(fill.color)}` })
                  "
                  :create-name-placeholder="panels.variableName"
                  :create-submit-label="panels.create"
                />
              </template>
            </PaintField>
          </BindableValueRoot>

          <template #details>
            <PanelFieldGroup :label="panels.blendMode">
              <AppSelect
                :model-value="fill.blendMode ?? 'NORMAL'"
                :options="blendModeOptions"
                :label="panels.blendMode"
                data-property="fill-blend-mode"
                @update:model-value="
                  commitDiscretePropertyListChange(flush, () =>
                    actions.patch(index, { blendMode: $event as Fill['blendMode'] })
                  )
                "
              />
            </PanelFieldGroup>
          </template>
        </PropertyItemRow>
      </div>
    </PanelSection>
  </PropertyListRoot>
</template>

// src/components/properties/FillSection.tsx
import { Plus, Eye, EyeOff, Minus } from 'lucide-react'
import React from 'react'

import { colorToHexRaw } from '@openweave/core/color'
import { BLACK } from '@openweave/core/constants'
import {
  BindableValueRoot,
  useColorBindingProvider,
  useEditorPropertyList,
  useI18n,
  useOkHCL,
  useSelectionState
} from '@openweave/react'
import type { Fill } from '@openweave/scene-graph'

import NumberField from '@/components/inputs/NumberField'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker'
import {
  commitDiscretePropertyListChange,
  useBlendModeOptions
} from '@/components/properties/blend-mode/use'
import { FillRow as ComplexFillEditor } from '@/components/properties/FillEditor'
import { paintBindingTargets, usePaintMutation } from '@/components/properties/paint/binding'
import { createFillOkhclAdapter } from '@/components/properties/paint/okhcl'
import PaintSwatchPopover from '@/components/properties/paint/PaintSwatchPopover'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField'
import { AppSelect } from '@/components/ui/AppSelect'
import { BindingPill } from '@/components/ui/binding'
import IconButton from '@/components/ui/IconButton'
import PanelSection from '@/components/ui/panel/PanelSection'

export default function FillSection() {
  const {
    items: fills,
    isMixed,
    active,
    selectedNodeIds,
    flush,
    actions
  } = useEditorPropertyList('fills')
  const colorProvider = useColorBindingProvider()
  const paint = usePaintMutation()
  const { panels, dialogs } = useI18n()
  const okhcl = useOkHCL()
  const { selectedNode } = useSelectionState()
  const blendOptions = useBlendModeOptions()

  if (!active) return null

  const addFill = () => {
    // With a multi-selection this replaces every layer's fills (mixed included).
    actions.add({ type: 'SOLID', color: BLACK, opacity: 1, visible: true })
  }

  return (
    <PanelSection
      label="Fill"
      empty={!isMixed && fills.length === 0}
      actions={
        <IconButton label="Add fill" onClick={addFill}>
          <Plus className="size-3.5" />
        </IconButton>
      }
    >
      <div className="space-y-3">
        <SharedStyleField kind="fill" label={panels.fillStyle} />

        {isMixed && <p className="text-[11px] text-muted">{panels.mixedFillsHelp}</p>}

        {fills.map((fill, i) => (
          <div
            key={i}
            className="flex flex-col gap-2 relative group"
            data-property="fills"
            data-index={i}
          >
            <div className="flex items-center gap-1.5">
              <BindableValueRoot
                provider={colorProvider}
                targets={paintBindingTargets(selectedNodeIds, 'fills', i)}
                value={fill.color}
                batchLabel="Change fill color"
              >
                {(binding) => {
                  const displayColor = binding.resolvedValue ?? fill.color
                  return (
                    <div
                      data-slot="paint-field"
                      className="flex-1 flex items-center gap-1 bg-input/50 rounded px-1.5 h-6 border border-border focus-within:border-accent transition-colors"
                    >
                      {fill.type === 'SOLID' ? (
                        <>
                          <PaintSwatchPopover
                            label="Fill color"
                            dataTestId="fill-picker-swatch"
                            color={displayColor}
                            okhcl={createFillOkhclAdapter(okhcl, selectedNode, i)}
                            onChange={(c) =>
                              paint.apply(binding, flush, 'Change fill color', () =>
                                actions.patch(i, { color: c })
                              )
                            }
                            onOpenChange={(open) => {
                              if (!open) paint.commit()
                            }}
                            onCancel={() => paint.rollback()}
                          />
                          {binding.variable ? (
                            <BindingPill
                              className="w-14"
                              label={binding.variable.name}
                              tooltip={`${binding.variable.name} · #${colorToHexRaw(displayColor)}`}
                            />
                          ) : (
                            <input
                              type="text"
                              data-property="color-hex"
                              className="w-14 bg-transparent outline-none text-xs text-surface font-mono uppercase"
                              value={colorToHexRaw(fill.color)}
                              onChange={() => {}} // Let popover handle actual color changes for simplicity
                              readOnly
                            />
                          )}
                        </>
                      ) : (
                        <div className="flex-1 text-xs truncate">Multiple / Gradient</div>
                      )}
                      <div className="w-[1px] h-3 bg-border mx-1"></div>
                      <div className="w-14">
                        <NumberField
                          value={Math.round((fill.opacity ?? 1) * 100)}
                          min={0}
                          max={100}
                          suffix="%"
                          onChange={(v) => actions.patch(i, { opacity: v / 100 })}
                          onCommit={(v) =>
                            commitDiscretePropertyListChange(flush, () =>
                              actions.patch(i, { opacity: v / 100 })
                            )
                          }
                        />
                      </div>
                      {fill.type === 'SOLID' && (
                        <VariableBindingPicker
                          triggerLabel={panels.applyVariable}
                          searchPlaceholder={dialogs.search}
                          emptyLabel={panels.noVariablesFound}
                          detachLabel={panels.detachVariable}
                          createLabel={panels.createColorVariable({
                            value: `#${colorToHexRaw(fill.color)}`
                          })}
                          createNamePlaceholder={panels.variableName}
                          createSubmitLabel={panels.create}
                        />
                      )}
                    </div>
                  )
                }}
              </BindableValueRoot>
              <IconButton
                label={panels.toggleVisibility}
                onClick={() => actions.toggleVisibility(i)}
                className={!fill.visible ? 'opacity-50' : ''}
              >
                {fill.visible ? <Eye className="size-3.5" /> : <EyeOff className="size-3.5" />}
              </IconButton>
              <IconButton label="Remove fill" onClick={() => actions.remove(i)}>
                <Minus className="size-3.5" />
              </IconButton>
            </div>
            {/* Extended properties: Blend mode */}
            <div className="pl-1" data-property="fill-blend-mode">
              <div className="text-[10px] text-muted mb-1">Blend mode</div>
              <AppSelect
                label={panels.blendMode}
                options={blendOptions}
                value={fill.blendMode ?? 'NORMAL'}
                onValueChange={(value) =>
                  commitDiscretePropertyListChange(flush, () =>
                    actions.patch(i, { blendMode: value as Fill['blendMode'] })
                  )
                }
              />
            </div>
            {/* If it's not SOLID, render the advanced editor below */}
            {fill.type !== 'SOLID' && (
              <div className="mt-2 pl-1 border-l-2 border-border/50">
                <ComplexFillEditor
                  fill={fill}
                  onChange={(f) => actions.update(i, f)}
                  onRemove={() => actions.remove(i)}
                />
              </div>
            )}
          </div>
        ))}
      </div>
    </PanelSection>
  )
}
