// src/components/properties/LayoutSection/LayoutSection.vue
<script setup lang="ts">
import { LayoutControlsRoot, useI18n } from '@openweave/vue'

import AutoLayoutControls from '@/components/properties/LayoutSection/AutoLayoutControls.vue'
import ClipContentControl from '@/components/properties/LayoutSection/ClipContentControl.vue'
import FlexControls from '@/components/properties/LayoutSection/FlexControls.vue'
import GridControls from '@/components/properties/LayoutSection/GridControls.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PaddingControls from '@/components/properties/LayoutSection/PaddingControls.vue'
import SizeControls from '@/components/properties/LayoutSection/size/SizeControls.vue'
import TextResizingControl from '@/components/properties/LayoutSection/TextResizingControl.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'

const { panels } = useI18n()

const CONTAINER_TYPES = ['FRAME', 'COMPONENT', 'COMPONENT_SET', 'INSTANCE']
</script>

<template>
  <LayoutControlsRoot v-slot="ctx">
    <template v-if="ctx.node">
      <PanelSection :label="ctx.node.layoutMode === 'NONE' ? panels.layout : panels.autoLayout">
        <template v-if="CONTAINER_TYPES.includes(ctx.node.type)" #actions>
          <IconButton
            :label="ctx.node.layoutMode === 'NONE' ? panels.addAutoLayout : panels.removeAutoLayout"
            size="md"
            :active="ctx.node.layoutMode !== 'NONE'"
            class="data-[state=on]:bg-accent/15"
            @click="
              ctx.editor.setLayoutMode(
                ctx.node.id,
                ctx.node.layoutMode === 'NONE' ? 'VERTICAL' : 'NONE'
              )
            "
          >
            <icon-lucide-layout-panel-top class="size-3.5" />
          </IconButton>
        </template>

        <AutoLayoutControls v-if="CONTAINER_TYPES.includes(ctx.node.type)" />
        <div class="mt-2 mb-1 text-[11px] text-muted">{{ panels.dimensions }}</div>
        <TextResizingControl v-if="ctx.node.type === 'TEXT'" />
        <SizeControls />
        <ClipContentControl
          v-if="CONTAINER_TYPES.includes(ctx.node.type) && ctx.node.layoutMode === 'NONE'"
        />

        <template v-if="CONTAINER_TYPES.includes(ctx.node.type) && ctx.node.layoutMode !== 'NONE'">
          <FlexControls v-if="ctx.isFlex" />
          <template v-if="ctx.isGrid">
            <GridControls />
            <PaddingControls />
            <ClipContentControl />
          </template>
        </template>
      </PanelSection>
    </template>
  </LayoutControlsRoot>
</template>

// src/components/properties/LayoutSection.tsx
'use client'

import { LayoutPanelTop } from 'lucide-react'
import React from 'react'

import { LayoutControlsRoot, useI18n, useLayoutControlsContext } from '@openweave/react'
import type { LayoutMode, NodeType } from '@openweave/scene-graph'

import AutoLayoutControls from '@/components/properties/LayoutSection/AutoLayoutControls'
import ClipContentControl from '@/components/properties/LayoutSection/ClipContentControl'
import FlexControls from '@/components/properties/LayoutSection/FlexControls'
import GridControls from '@/components/properties/LayoutSection/GridControls'
import PaddingControls from '@/components/properties/LayoutSection/PaddingControls'
import SizeControls from '@/components/properties/LayoutSection/size/SizeControls'
import TextResizingControl from '@/components/properties/LayoutSection/TextResizingControl'
import IconButton from '@/components/ui/IconButton'
import PanelSection from '@/components/ui/panel/PanelSection'

const CONTAINER_TYPES = new Set<NodeType>([
  'FRAME',
  'COMPONENT',
  'COMPONENT_SET',
  'INSTANCE',
  'SECTION'
])

/**
 * Layout / Auto layout panel section.
 *
 * Renders for any selected node — only the auto-layout sub-controls (flow,
 * flex, grid, clip content) are gated to container types. Size (W/H, size
 * limits) and, for text, the resize mode apply to every node, mirroring the
 * old Vue LayoutSection's v-if structure.
 */
export default function LayoutSection() {
  return (
    <LayoutControlsRoot>
      <LayoutSectionContent />
    </LayoutControlsRoot>
  )
}

function LayoutSectionContent() {
  const ctx = useLayoutControlsContext()
  const { panels } = useI18n()
  const { node, editor, isFlex, isGrid } = ctx
  const isContainer = CONTAINER_TYPES.has(node.type)
  const hasAutoLayout = node.layoutMode !== 'NONE'

  return (
    <div data-test-id="layout-section">
      <PanelSection
        label={hasAutoLayout ? panels.autoLayout : panels.layout}
        actions={
          isContainer ? (
            <IconButton
              label={hasAutoLayout ? panels.removeAutoLayout : panels.addAutoLayout}
              size="md"
              active={hasAutoLayout}
              className="data-[state=on]:bg-accent/15"
              onClick={() =>
                editor.setLayoutMode(node.id, (hasAutoLayout ? 'NONE' : 'VERTICAL') as LayoutMode)
              }
            >
              <LayoutPanelTop className="size-3.5" />
            </IconButton>
          ) : undefined
        }
      >
        {isContainer && <AutoLayoutControls />}

        <div className="mt-2 mb-1 text-[11px] text-muted">{panels.dimensions}</div>
        {node.type === 'TEXT' && <TextResizingControl />}
        <SizeControls />
        {isContainer && node.layoutMode === 'NONE' && <ClipContentControl />}

        {isContainer && node.layoutMode !== 'NONE' && (
          <>
            {isFlex && <FlexControls />}
            {isGrid && (
              <>
                <GridControls />
                <PaddingControls />
                <ClipContentControl />
              </>
            )}
          </>
        )}
      </PanelSection>
    </div>
  )
}
