// src/components/properties/PageSection.vue
<script setup lang="ts">
import { computed } from 'vue'

import { useI18n } from '@openweave/vue'

import ColorPicker from '@/components/ColorPicker/ColorPicker.vue'
import PaintField from '@/components/properties/paint/PaintField.vue'
import PaintValue from '@/components/properties/paint/PaintValue.vue'
import FillSwatch from '@/components/ui/FillSwatch.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import { useEditorStore } from '@/app/editor/active-store'

import type { Color, Fill } from '@openweave/scene-graph'

const editor = useEditorStore()
const pageColor = computed(() => editor.state.pageColor)
const pageFill = computed<Fill>(() => ({
  type: 'SOLID',
  color: pageColor.value,
  opacity: 1,
  visible: true
}))
const { panels } = useI18n()

function updatePageAlpha(alpha: number) {
  editor.setPageColor({ ...pageColor.value, a: alpha })
}

function updatePageColor(color: Color) {
  editor.setPageColor(color)
}
</script>

<template>
  <PanelSection :label="panels.page">
    <PaintField
      :opacity="pageColor.a"
      :opacity-label="panels.opacity"
      @update:opacity="updatePageAlpha"
    >
      <template #preview>
        <ColorPicker :color="pageColor" @update="updatePageColor">
          <template #trigger>
            <button
              type="button"
              :aria-label="panels.pageBackground"
              class="size-5 shrink-0 cursor-pointer rounded border-0 bg-transparent p-0"
            >
              <FillSwatch :fill="pageFill" class="size-full" />
            </button>
          </template>
        </ColorPicker>
      </template>
      <template #value>
        <PaintValue :color="pageColor" :label="panels.pageBackground" @update="updatePageColor" />
      </template>
    </PaintField>
  </PanelSection>
</template>

// src/components/properties/PageSection.tsx
import React, { useState } from 'react'

import { colorToHexRaw, parseColor } from '@openweave/core/color'
import { useI18n } from '@openweave/react'
import type { Color } from '@openweave/scene-graph/primitives'

import { getActiveEditorStore } from '@/app/editor/active-store'
import ColorSwatchPopover from '@/components/color-picker/ColorSwatchPopover'
import NumberField from '@/components/inputs/NumberField'
import PanelSection from '@/components/ui/panel/PanelSection'

export default function PageSection() {
  const editor = getActiveEditorStore()
  const { panels } = useI18n()

  const pageColor = editor.state.pageColor
  const [hexDraft, setHexDraft] = useState<string | null>(null)

  const updatePageColor = (color: Color) => {
    editor.setPageColor(color)
  }

  const updatePageAlpha = (alpha: number) => {
    editor.setPageColor({ ...pageColor, a: alpha })
  }

  const commitHexDraft = () => {
    if (hexDraft !== null) updatePageColor({ ...parseColor(`#${hexDraft}`), a: pageColor.a })
    setHexDraft(null)
  }

  return (
    <PanelSection label={panels.page}>
      <div className="flex flex-col gap-2 relative group">
        <div className="flex items-center gap-1.5">
          <div className="flex-1 flex items-center gap-1 bg-input/50 rounded px-1.5 py-1 border border-border focus-within:border-accent transition-colors">
            <ColorSwatchPopover color={pageColor} onChange={updatePageColor} />
            <input
              type="text"
              aria-label={panels.pageBackground}
              className="w-14 bg-transparent outline-none text-xs text-surface font-mono uppercase"
              value={hexDraft ?? colorToHexRaw(pageColor)}
              onChange={(e) => setHexDraft(e.target.value)}
              onBlur={commitHexDraft}
              onKeyDown={(e) => {
                if (e.key === 'Enter') e.currentTarget.blur()
                if (e.key === 'Escape') setHexDraft(null)
              }}
            />
            <div className="w-[1px] h-3 bg-border mx-1"></div>
            <div className="w-14">
              <NumberField
                ariaLabel={panels.opacity}
                value={Math.round((pageColor.a ?? 1) * 100)}
                min={0}
                max={100}
                suffix="%"
                onChange={(v) => updatePageAlpha(v / 100)}
                onCommit={(v) => updatePageAlpha(v / 100)}
              />
            </div>
          </div>
        </div>
      </div>
    </PanelSection>
  )
}
