// src/components/properties/PositionSection.tsx
import {
  AlignStartVertical,
  AlignCenterVertical,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignCenterHorizontal,
  AlignEndHorizontal,
  RotateCw,
  FlipHorizontal2,
  FlipVertical2,
  RotateCwSquare
} from 'lucide-react'
/* eslint-disable openweave/no-hardcoded-tip-labels */
import React from 'react'

import { PositionControlsRoot, useI18n } from '@openweave/react'

import { useEditorStore } from '@/app/editor/active-store'
import NumberField from '@/components/inputs/NumberField'
import IconButton from '@/components/ui/IconButton'
import PanelGrid from '@/components/ui/panel/PanelGrid'
import PanelSection from '@/components/ui/panel/PanelSection'
import Tip from '@/components/ui/Tip'

export default function PositionSection() {
  const store = useEditorStore()
  const { panels } = useI18n()

  function handleAlign(
    nodeAlign: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void,
    axis: 'horizontal' | 'vertical',
    pos: 'min' | 'center' | 'max'
  ) {
    const editState = store.state?.nodeEditState
    if (editState && editState.selectedVertexIndices.size >= 2) {
      store.nodeEditAlignVertices(axis, pos)
    } else {
      nodeAlign(axis, pos)
    }
  }

  return (
    <PositionControlsRoot>
      {( { active, isMulti, xValue, yValue, wValue, hValue, rotationValue, actions }) =>
        active ? (
          <PanelSection label="Position">
            <div role="toolbar" aria-label="Position" className="mb-1.5 flex justify-between">
              <div className="flex gap-0.5">
                <IconButton
                  label="Align left"
                  size="md"
                  onClick={() => handleAlign(actions.align, 'horizontal', 'min')}
                >
                  <AlignStartVertical className="size-3.5" />
                </IconButton>
                <IconButton
                  label="Align horizontal centers"
                  size="md"
                  onClick={() => handleAlign(actions.align, 'horizontal', 'center')}
                >
                  <AlignCenterVertical className="size-3.5" />
                </IconButton>
                <IconButton
                  label="Align right"
                  size="md"
                  onClick={() => handleAlign(actions.align, 'horizontal', 'max')}
                >
                  <AlignEndVertical className="size-3.5" />
                </IconButton>
              </div>
              <div className="flex gap-0.5">
                <IconButton
                  label="Align top"
                  size="md"
                  onClick={() => handleAlign(actions.align, 'vertical', 'min')}
                >
                  <AlignStartHorizontal className="size-3.5" />
                </IconButton>
                <IconButton
                  label="Align vertical centers"
                  size="md"
                  onClick={() => handleAlign(actions.align, 'vertical', 'center')}
                >
                  <AlignCenterHorizontal className="size-3.5" />
                </IconButton>
                <IconButton
                  label="Align bottom"
                  size="md"
                  onClick={() => handleAlign(actions.align, 'vertical', 'max')}
                >
                  <AlignEndHorizontal className="size-3.5" />
                </IconButton>
              </div>
            </div>

            <PanelGrid columns={2}>
              <Tip label="X">
                <NumberField
                  icon="X"
                  ariaLabel={panels.xAxis}
                  dataProperty="x"
                  value={xValue}
                  onChange={(v) => actions.updateProp('x', v)}
                  onCommit={(v, p) => actions.commitProp('x', v, p)}
                />
              </Tip>
              <Tip label="Y">
                <NumberField
                  icon="Y"
                  ariaLabel={panels.yAxis}
                  dataProperty="y"
                  value={yValue}
                  onChange={(v) => actions.updateProp('y', v)}
                  onCommit={(v, p) => actions.commitProp('y', v, p)}
                />
              </Tip>
            </PanelGrid>

            {isMulti && (<PanelGrid columns={2} className="mt-1.5">
              <Tip label="Width">
                <NumberField
                  icon="W"
                  ariaLabel={panels.width}
                  dataProperty="width"
                  value={wValue}
                  min={1}
                  onChange={(v) => actions.updateProp('width', v)}
                  onCommit={(v, p) => actions.commitProp('width', v, p)}
                />
              </Tip>
              <Tip label="Height">
                <NumberField
                  icon="H"
                  ariaLabel={panels.height}
                  dataProperty="height"
                  value={hValue}
                  min={1}
                  onChange={(v) => actions.updateProp('height', v)}
                  onCommit={(v, p) => actions.commitProp('height', v, p)}
                />
              </Tip></PanelGrid>)}<PanelGrid columns={2} className="mt-1.5"><Tip label="Rotation">
                <NumberField
                  suffix="°"
                  ariaLabel={panels.rotation}
                  dataProperty="rotation"
                  value={rotationValue}
                  min={-360}
                  max={360}
                  onChange={(v) => actions.updateProp('rotation', v)}
                  onCommit={(v, p) => actions.commitProp('rotation', v, p)}
                  icon={<RotateCw className="size-3" />}
                />
              </Tip>
              <div className="flex h-6 items-center justify-end gap-0.5">
                <IconButton
                  label="Flip horizontal"
                  size="md"
                  onClick={() => actions.flip('horizontal')}
                >
                  <FlipHorizontal2 className="size-3.5" />
                </IconButton>
                <IconButton
                  label="Flip vertical"
                  size="md"
                  onClick={() => actions.flip('vertical')}
                >
                  <FlipVertical2 className="size-3.5" />
                </IconButton>
                <IconButton label="Rotate -90°" size="md" onClick={() => actions.rotate(90)}>
                  <RotateCwSquare className="size-3.5" />
                </IconButton>
              </div>
            </PanelGrid>
          </PanelSection>
        ) : null
      }
    </PositionControlsRoot>
  )
}

// src/components/properties/PositionSection.vue
<script setup lang="ts">
import { PositionControlsRoot, useI18n } from '@openweave/vue'

import { useEditorStore } from '@/app/editor/active-store'
import NumberField from '@/components/inputs/NumberField.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import Tip from '@/components/ui/Tip.vue'

const { panels } = useI18n()
const store = useEditorStore()

function handleAlign(
  nodeAlign: (axis: 'horizontal' | 'vertical', pos: 'min' | 'center' | 'max') => void,
  axis: 'horizontal' | 'vertical',
  pos: 'min' | 'center' | 'max'
) {
  const editState = store.state.nodeEditState
  if (editState && editState.selectedVertexIndices.size >= 2) {
    store.nodeEditAlignVertices(axis, pos)
  } else {
    nodeAlign(axis, pos)
  }
}
</script>

<template>
  <PositionControlsRoot
    v-slot="{ active, isMulti, xValue, yValue, wValue, hValue, rotationValue, actions }"
  >
    <PanelSection v-if="active" :label="panels.position">
      <div role="toolbar" :aria-label="panels.position" class="mb-1.5 flex justify-between">
        <div class="flex gap-0.5">
          <IconButton
            :label="panels.alignLeft"
            size="md"
            @click="handleAlign(actions.align, 'horizontal', 'min')"
          >
            <icon-lucide-align-start-vertical class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignCenterHorizontally"
            size="md"
            @click="handleAlign(actions.align, 'horizontal', 'center')"
          >
            <icon-lucide-align-center-vertical class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignRight"
            size="md"
            @click="handleAlign(actions.align, 'horizontal', 'max')"
          >
            <icon-lucide-align-end-vertical class="size-3.5" />
          </IconButton>
        </div>
        <div class="flex gap-0.5">
          <IconButton
            :label="panels.alignTop"
            size="md"
            @click="handleAlign(actions.align, 'vertical', 'min')"
          >
            <icon-lucide-align-start-horizontal class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignCenterVertically"
            size="md"
            @click="handleAlign(actions.align, 'vertical', 'center')"
          >
            <icon-lucide-align-center-horizontal class="size-3.5" />
          </IconButton>
          <IconButton
            :label="panels.alignBottom"
            size="md"
            @click="handleAlign(actions.align, 'vertical', 'max')"
          >
            <icon-lucide-align-end-horizontal class="size-3.5" />
          </IconButton>
        </div>
      </div>

      <PanelGrid :columns="2">
        <Tip :label="panels.xAxis">
          <NumberField
            icon="X"
            data-property="x"
            :aria-label="panels.xAxis"
            :model-value="xValue"
            @update:model-value="actions.updateProp('x', $event)"
            @commit="(v: number, p: number) => actions.commitProp('x', v, p)"
          />
        </Tip>
        <Tip :label="panels.yAxis">
          <NumberField
            icon="Y"
            data-property="y"
            :aria-label="panels.yAxis"
            :model-value="yValue"
            @update:model-value="actions.updateProp('y', $event)"
            @commit="(v: number, p: number) => actions.commitProp('y', v, p)"
          />
        </Tip>
      </PanelGrid>

      <PanelGrid v-if="isMulti" :columns="2" class="mt-1.5">
        <Tip :label="panels.width">
          <NumberField
            icon="W"
            data-property="width"
            :aria-label="panels.width"
            :model-value="wValue"
            :min="1"
            @update:model-value="actions.updateProp('width', $event)"
            @commit="(v: number, p: number) => actions.commitProp('width', v, p)"
          />
        </Tip>
        <Tip :label="panels.height">
          <NumberField
            icon="H"
            data-property="height"
            :aria-label="panels.height"
            :model-value="hValue"
            :min="1"
            @update:model-value="actions.updateProp('height', $event)"
            @commit="(v: number, p: number) => actions.commitProp('height', v, p)"
          />
        </Tip>
      </PanelGrid>

      <PanelGrid :columns="2" class="mt-1.5">
        <Tip :label="panels.rotation">
          <NumberField
            suffix="°"
            data-property="rotation"
            :aria-label="panels.rotation"
            :model-value="rotationValue"
            :min="-360"
            :max="360"
            @update:model-value="actions.updateProp('rotation', $event)"
            @commit="(v: number, p: number) => actions.commitProp('rotation', v, p)"
          >
            <template #icon>
              <icon-lucide-rotate-cw class="size-3" />
            </template>
          </NumberField>
        </Tip>
        <div class="flex h-6 items-center justify-end gap-0.5">
          <IconButton :label="panels.flipHorizontal" size="md" @click="actions.flip('horizontal')">
            <icon-lucide-flip-horizontal-2 class="size-3.5" />
          </IconButton>
          <IconButton :label="panels.flipVertical" size="md" @click="actions.flip('vertical')">
            <icon-lucide-flip-vertical-2 class="size-3.5" />
          </IconButton>
          <IconButton :label="panels.rotate90" size="md" @click="actions.rotate(90)">
            <icon-lucide-rotate-cw-square class="size-3.5" />
          </IconButton>
        </div>
      </PanelGrid>
    </PanelSection>
  </PositionControlsRoot>
</template>
