// src/components/properties/StrokeSection.vue
<script setup lang="ts">
import { ref } from 'vue'

import {
  applySolidStrokeColor,
  BindableValueRoot,
  MIXED,
  useColorBindingProvider,
  useI18n,
  useOkHCL,
  useStrokeControls
} from '@openweave/vue'

import ColorPicker from '@/components/ColorPicker/ColorPicker.vue'
import NumberField from '@/components/inputs/NumberField.vue'
import PropertyItemRow from '@/components/properties/item-list/PropertyItemRow.vue'
import PaintField from '@/components/properties/paint/PaintField.vue'
import PaintValue from '@/components/properties/paint/PaintValue.vue'
import {
  applyPaintMutation,
  cancelPaintMutation,
  commitPaintMutation,
  paintBindingTargets
} from '@/components/properties/paint/binding'
import { createStrokeOkhclAdapter } from '@/components/properties/paint/okhcl'
import PropertyListRoot from '@/components/properties/PropertyListRoot.vue'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField.vue'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import FillSwatch from '@/components/ui/FillSwatch.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'

import { colorToHexRaw } from '@openweave/core/color'
import type { Color, Fill, SceneNode, Stroke } from '@openweave/scene-graph'
import type { BindableValueActions } from '@openweave/vue'

const strokeCtx = useStrokeControls()
const { advancedActive, cap, join, miterLimit } = strokeCtx
const colorProvider = useColorBindingProvider()
const okhcl = useOkHCL()
const { panels, dialogs } = useI18n()
const expandedSides = ref(false)

function strokePreview(stroke: Stroke, color: Color): Fill {
  return {
    type: 'SOLID',
    color,
    opacity: stroke.opacity,
    visible: stroke.visible
  }
}

function updateStrokeColor(
  binding: BindableValueActions<Color>,
  flush: () => void,
  color: Color,
  patch: (changes: Partial<Stroke>) => void,
  commit: boolean
) {
  if (!applyPaintMutation(binding, flush, () => patch(applySolidStrokeColor(color)))) return
  if (commit) commitPaintMutation(binding)
}

function setCap(value: string) {
  if (value === 'NONE' || value === 'ROUND' || value === 'SQUARE') {
    strokeCtx.setCap(value)
  }
}

function setJoin(value: string) {
  if (value === 'MITER' || value === 'BEVEL' || value === 'ROUND') {
    strokeCtx.setJoin(value)
  }
}

function onToggleSides(activeNode: SceneNode | null) {
  if (!activeNode) return
  const next = !expandedSides.value
  expandedSides.value = next
  if (next && !activeNode.independentStrokeWeights) {
    const weight = activeNode.strokes[0]?.weight ?? 1
    strokeCtx.selectSide('CUSTOM', {
      ...activeNode,
      borderTopWeight: weight,
      borderRightWeight: weight,
      borderBottomWeight: weight,
      borderLeftWeight: weight
    })
  } else if (!next && activeNode.independentStrokeWeights) {
    strokeCtx.selectSide('ALL', activeNode)
  }
}
</script>

<template>
  <PropertyListRoot
    v-slot="{ items, isMixed, activeNode, selectedNodeIds, flush, actions }"
    prop-key="strokes"
    :label="panels.stroke"
  >
    <PanelSection :label="panels.stroke" :empty="!isMixed && items.length === 0">
      <template #actions>
        <IconButton :label="panels.addStroke" @click="actions.add(strokeCtx.defaultStroke)">
          <icon-lucide-plus class="size-3.5" />
        </IconButton>
      </template>

      <SharedStyleField kind="stroke" :label="panels.strokeStyle" />

      <p v-if="isMixed" class="text-[11px] text-muted">{{ panels.mixedStrokesHelp }}</p>

      <PropertyItemRow
        v-for="(stroke, index) in items"
        :key="`${index}:${stroke.visible ? 'visible' : 'hidden'}`"
        prop-key="strokes"
        :index="index"
        :visibility-label="panels.toggleVisibility"
        :remove-label="panels.removeStroke"
      >
        <BindableValueRoot
          v-slot="binding"
          :provider="colorProvider"
          :targets="paintBindingTargets(selectedNodeIds, 'strokes', index)"
          :value="stroke.color"
          batch-label="Change stroke color"
        >
          <PaintField
            :opacity="stroke.opacity"
            :opacity-label="panels.opacity"
            @update:opacity="actions.patch(index, { opacity: $event })"
          >
            <template #preview>
              <ColorPicker
                :color="binding.resolvedValue ?? stroke.color"
                :okhcl="createStrokeOkhclAdapter(okhcl, activeNode, index)"
                @update="
                  updateStrokeColor(
                    binding.actions,
                    flush,
                    $event,
                    (changes) => actions.patch(index, changes),
                    false
                  )
                "
                @open-change="!$event && commitPaintMutation(binding.actions)"
                @cancel="cancelPaintMutation(binding.actions)"
              >
                <template #trigger>
                  <button
                    type="button"
                    :aria-label="panels.stroke"
                    class="size-4 shrink-0 cursor-pointer rounded-sm border-0 bg-transparent p-0"
                  >
                    <FillSwatch
                      :fill="strokePreview(stroke, binding.resolvedValue ?? stroke.color)"
                      class="size-full"
                    />
                  </button>
                </template>
              </ColorPicker>
            </template>

            <template #value>
              <PaintValue
                :color="stroke.color"
                :resolved-color="binding.resolvedValue"
                :variable-name="binding.variable?.name"
                :label="panels.stroke"
                @update="
                  updateStrokeColor(
                    binding.actions,
                    flush,
                    $event,
                    (changes) => actions.patch(index, changes),
                    true
                  )
                "
              />
            </template>

            <template #binding>
              <VariableBindingPicker
                :trigger-label="panels.applyVariable"
                :search-placeholder="dialogs.search"
                :empty-label="panels.noVariablesFound"
                :detach-label="panels.detachVariable"
                :create-label="
                  panels.createColorVariable({ value: `#${colorToHexRaw(stroke.color)}` })
                "
                :create-name-placeholder="panels.variableName"
                :create-submit-label="panels.create"
              />
            </template>
          </PaintField>
        </BindableValueRoot>
      </PropertyItemRow>

      <div v-if="!isMixed && items.length > 0" class="mt-1 flex items-center gap-1.5">
        <AppSelect
          :label="panels.strokeType"
          :ui="{ trigger: 'w-[88px] flex-none' }"
          :model-value="strokeCtx.currentAlign(activeNode)"
          :options="strokeCtx.alignOptions"
          data-property="stroke-align"
          @update:model-value="strokeCtx.updateAlign($event as Stroke['align'], activeNode)"
        />
        <Tip :label="panels.strokeWeight">
          <NumberField
            v-if="!expandedSides"
            class="flex-1"
            icon="W"
            :model-value="items[0]?.weight ?? 1"
            :min="0"
            data-property="stroke-weight"
            @update:model-value="actions.patch(0, { weight: $event })"
          />
        </Tip>
        <IconButton
          :label="panels.strokeSides"
          size="md"
          class="size-[26px] shrink-0"
          :active="expandedSides"
          data-property="stroke-sides"
          @click="onToggleSides(activeNode)"
        >
          <icon-lucide-layout-grid class="size-3.5" />
        </IconButton>
      </div>

      <div v-if="!isMixed && items.length > 0" class="mt-1.5 flex items-center gap-1.5">
        <IconButton
          :label="panels.strokeDash"
          size="md"
          class="shrink-0"
          :active="strokeCtx.dashState(items[0]).on"
          data-property="stroke-dash"
          @click="actions.patch(0, strokeCtx.toggleDash(items[0]))"
        >
          <span class="flex items-center gap-0.5">
            <icon-lucide-minus class="size-2.5" />
            <icon-lucide-minus class="size-2.5" />
          </span>
        </IconButton>
        <template v-if="strokeCtx.dashState(items[0]).on">
          <NumberField
            class="flex-1"
            icon="D"
            :model-value="items[0]?.dashPattern?.[0] ?? 6"
            :min="1"
            data-property="stroke-dash-length"
            @update:model-value="actions.patch(0, strokeCtx.setDash(items[0], $event))"
          />
          <NumberField
            class="flex-1"
            icon="G"
            :model-value="items[0]?.dashPattern?.[1] ?? items[0]?.dashPattern?.[0] ?? 6"
            :min="1"
            data-property="stroke-dash-gap"
            @update:model-value="actions.patch(0, strokeCtx.setGap(items[0], $event))"
          />
        </template>
      </div>

      <PanelGrid v-if="advancedActive" :columns="3" class="mt-1.5">
        <PanelFieldGroup :label="panels.strokeCap">
          <SegmentedControl
            :model-value="cap === MIXED ? 'MIXED' : cap"
            :options="strokeCtx.capOptions"
            :label="panels.strokeCap"
            data-property="stroke-cap"
            @update:model-value="setCap"
          >
            <template #option="{ option }">
              <Tip :label="option.label">
                <icon-lucide-minus v-if="option.value === 'NONE'" class="size-3" />
                <icon-lucide-circle v-else-if="option.value === 'ROUND'" class="size-2.5" />
                <icon-lucide-square v-else class="size-2.5" />
              </Tip>
            </template>
          </SegmentedControl>
        </PanelFieldGroup>

        <PanelFieldGroup :label="panels.strokeJoin">
          <SegmentedControl
            :model-value="join === MIXED ? 'MIXED' : join"
            :options="strokeCtx.joinOptions"
            :label="panels.strokeJoin"
            data-property="stroke-join"
            @update:model-value="setJoin"
          >
            <template #option="{ option }">
              <Tip :label="option.label">
                <icon-lucide-corner-up-right v-if="option.value === 'MITER'" class="size-3" />
                <icon-lucide-triangle v-else-if="option.value === 'BEVEL'" class="size-2.5" />
                <icon-lucide-circle v-else class="size-2.5" />
              </Tip>
            </template>
          </SegmentedControl>
        </PanelFieldGroup>

        <PanelFieldGroup :label="panels.strokeMiterLimit">
          <NumberField
            :model-value="miterLimit"
            :min="1"
            data-property="stroke-miter-limit"
            :aria-label="panels.strokeMiterLimit"
            @update:model-value="strokeCtx.updateMiterLimit"
            @commit="strokeCtx.commitMiterLimit"
          >
            <template #icon>
              <icon-lucide-triangle-right class="size-3" />
            </template>
          </NumberField>
        </PanelFieldGroup>
      </PanelGrid>

      <div
        v-if="!isMixed && items.length > 0 && expandedSides"
        class="mt-1.5 grid grid-cols-2 gap-1.5"
      >
        <NumberField
          v-for="side in strokeCtx.borderSides"
          :key="side"
          :label="side[0].toUpperCase()"
          :model-value="strokeCtx.borderWeight(activeNode, side)"
          :min="0"
          :data-property="`stroke-${side}-weight`"
          @update:model-value="strokeCtx.updateBorderWeight(side, $event, activeNode)"
        />
      </div>
    </PanelSection>
  </PropertyListRoot>
</template>

// src/components/properties/StrokeSection.tsx
import React from 'react'
import {
  BindableValueRoot,
  useColorBindingProvider,
  useEditor,
  useEditorPropertyList,
  useI18n,
  useOkHCL,
  useStrokeControls
} from '@openweave/react'
import { BLACK } from '@openweave/core/constants'
import { colorToHexRaw } from '@openweave/core/color'
import type { SceneNode, Stroke, StrokeCap, StrokeJoin } from '@openweave/scene-graph'
import { Plus, Eye, EyeOff, Minus, AlignCenter, AlignLeft, AlignRight } from 'lucide-react'

import PanelSection from '@/components/ui/panel/PanelSection'
import IconButton from '@/components/ui/IconButton'
import NumberField from '@/components/inputs/NumberField'
import SegmentedControl from '@/components/ui/SegmentedControl'
import { BindingPill } from '@/components/ui/binding'
import PaintSwatchPopover from '@/components/properties/paint/PaintSwatchPopover'
import { paintBindingTargets, usePaintMutation } from '@/components/properties/paint/binding'
import { createStrokeOkhclAdapter } from '@/components/properties/paint/okhcl'
import { commitDiscretePropertyListChange } from '@/components/properties/blend-mode/use'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField'
import VariableBindingPicker from '@/components/properties/binding/VariableBindingPicker'

const inputClass = 'w-full bg-input/50 rounded px-2 py-1 border border-border text-surface text-xs outline-none focus:border-accent'

export default function StrokeSection() {
  const editor = useEditor()
  const { items: strokes, isMixed, active, activeNode: propertyNode, selectedNodeIds, flush, actions } =
    useEditorPropertyList('strokes')
  const strokeCtx = useStrokeControls()
  const colorProvider = useColorBindingProvider()
  const paint = usePaintMutation()
  const { panels, dialogs } = useI18n()
  const okhcl = useOkHCL()

  if (!active || !propertyNode) return null

  const node = propertyNode

  // Node-level stroke geometry; values can be mixed across a multi-selection.
  const capValue = typeof strokeCtx.cap === 'string' ? strokeCtx.cap : 'MIXED'
  const joinValue = typeof strokeCtx.join === 'string' ? strokeCtx.join : 'MIXED'
  const dashPattern = ('dashPattern' in node ? node.dashPattern : undefined) ?? []
  const sidesExpanded = node.independentStrokeWeights
  // ARROW_LINES/ARROW_EQUILATERAL have no SDK-provided options entry yet.
  const capOptions = [
    ...strokeCtx.capOptions,
    { value: 'ARROW_LINES', label: 'Arrow cap' },
    { value: 'ARROW_EQUILATERAL', label: 'Triangle cap' }
  ]

  /** Applies a node-level patch to every selected node as one undo step. */
  const updateNodeLevel = (patch: Partial<SceneNode>, label: string) => {
    flush()
    const apply = () => {
      for (const id of selectedNodeIds) editor.updateNodeWithUndo(id, patch, label)
    }
    if (selectedNodeIds.length > 1) editor.undo.runBatch(label, apply)
    else apply()
  }

  const setCap = (value: StrokeCap) => {
    flush()
    strokeCtx.setCap(value)
  }

  const setJoin = (value: StrokeJoin) => {
    flush()
    strokeCtx.setJoin(value)
  }

  const addStroke = () => {
    // With a multi-selection this replaces every layer's strokes (mixed included).
    actions.add({ color: BLACK, weight: 1, opacity: 1, visible: true, align: 'CENTER' })
  }

  return (
    <PanelSection
      label="Stroke"
      empty={!isMixed && strokes.length === 0}
      actions={
        <IconButton label="Add stroke" onClick={addStroke}>
          <Plus className="size-3.5" />
        </IconButton>
      }
    >
      <div className="space-y-3">
        <SharedStyleField kind="stroke" label={panels.strokeStyle} />

        {isMixed && <p className="text-[11px] text-muted">{panels.mixedStrokesHelp}</p>}

        {strokes.map((stroke, i) => (
          <div key={i} className="flex flex-col gap-2 relative group pb-2 border-b border-border/50 last:border-0 last:pb-0" data-property="strokes" data-index={i}>
            <div className="flex items-center gap-1.5">
              <BindableValueRoot
                provider={colorProvider}
                targets={paintBindingTargets(selectedNodeIds, 'strokes', i)}
                value={stroke.color}
                batchLabel="Change stroke color"
              >
                {(binding) => {
                  const displayColor = binding.resolvedValue ?? stroke.color
                  return (
                    <div className="flex-1 flex items-center gap-1 bg-input/50 rounded px-1.5 py-1 border border-border focus-within:border-accent transition-colors">
                      <PaintSwatchPopover
                        label="Stroke color"
                        color={displayColor}
                        okhcl={createStrokeOkhclAdapter(okhcl, node, i)}
                        onChange={(c) =>
                          paint.apply(binding, flush, 'Change stroke color', () =>
                            actions.patch(i, { color: c })
                          )
                        }
                        onOpenChange={(open) => {
                          if (!open) paint.commit()
                        }}
                        onCancel={() => paint.rollback()}
                      />
                      {binding.variable ? (
                        <BindingPill
                          className="w-14"
                          label={binding.variable.name}
                          tooltip={`${binding.variable.name} · #${colorToHexRaw(displayColor)}`}
                        />
                      ) : (
                        <input
                          type="text"
                          data-property="color-hex"
                          className="w-14 bg-transparent outline-none text-xs text-surface font-mono uppercase"
                          value={colorToHexRaw(stroke.color)}
                          onChange={() => {}} // Let popover handle actual color changes
                          readOnly
                        />
                      )}
                      <div className="w-[1px] h-3 bg-border mx-1"></div>
                      <div className="w-14">
                        <NumberField
                          value={Math.round((stroke.opacity ?? 1) * 100)}
                          min={0}
                          max={100}
                          suffix="%"
                          onChange={(v) => actions.patch(i, { opacity: v / 100 })}
                          onCommit={(v) =>
                            commitDiscretePropertyListChange(flush, () =>
                              actions.patch(i, { opacity: v / 100 })
                            )
                          }
                        />
                      </div>
                      <VariableBindingPicker
                        triggerLabel={panels.applyVariable}
                        searchPlaceholder={dialogs.search}
                        emptyLabel={panels.noVariablesFound}
                        detachLabel={panels.detachVariable}
                        createLabel={panels.createColorVariable({
                          value: `#${colorToHexRaw(stroke.color)}`
                        })}
                        createNamePlaceholder={panels.variableName}
                        createSubmitLabel={panels.create}
                      />
                    </div>
                  )
                }}
              </BindableValueRoot>
              <IconButton
                label={panels.toggleVisibility}
                onClick={() => actions.toggleVisibility(i)}
                className={!stroke.visible ? 'opacity-50' : ''}
              >
                {stroke.visible ? <Eye className="size-3.5" /> : <EyeOff className="size-3.5" />}
              </IconButton>
              <IconButton label="Remove stroke" onClick={() => actions.remove(i)}>
                <Minus className="size-3.5" />
              </IconButton>
            </div>

            <div className="flex items-center gap-2">
              <div className="flex-1">
                <div className="text-[10px] text-muted mb-1">Weight</div>
                <NumberField
                  value={stroke.weight ?? 1}
                  min={0}
                  onChange={(v) => actions.patch(i, { weight: Math.max(0, v) })}
                  onCommit={(v) =>
                    commitDiscretePropertyListChange(flush, () =>
                      actions.patch(i, { weight: Math.max(0, v) })
                    )
                  }
                />
              </div>
              <div className="flex-[2]">
                <div className="text-[10px] text-muted mb-1">Position</div>
                <SegmentedControl
                  value={stroke.align ?? 'CENTER'}
                  onChange={(v) =>
                    commitDiscretePropertyListChange(flush, () =>
                      actions.patch(i, { align: v as Stroke['align'] })
                    )
                  }
                  options={[
                    { value: 'INSIDE', label: 'Inside', icon: <AlignLeft className="size-3.5" /> },
                    { value: 'CENTER', label: 'Center', icon: <AlignCenter className="size-3.5" /> },
                    { value: 'OUTSIDE', label: 'Outside', icon: <AlignRight className="size-3.5" /> }
                  ]}
                />
              </div>
            </div>
          </div>
        ))}

        {strokes.length > 0 && 'strokeCap' in node && (
          <div className="pt-2 border-t border-border mt-2 space-y-3">
            <div data-property="stroke-cap">
              <div className="text-[10px] text-muted mb-1">Cap</div>
              <div className="flex flex-wrap gap-1">
                {capOptions.map((option) => (
                  <button
                    key={option.value}
                    type="button"
                    aria-label={option.label}
                    aria-pressed={capValue === option.value}
                    className={`rounded px-1.5 py-1 text-[10px] ${
                      capValue === option.value
                        ? 'bg-active text-surface'
                        : 'bg-input/50 text-muted hover:bg-hover hover:text-surface'
                    }`}
                    onClick={() => setCap(option.value as StrokeCap)}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>
            <div data-property="stroke-join">
              <div className="text-[10px] text-muted mb-1">Join</div>
              <div className="flex flex-wrap gap-1">
                {strokeCtx.joinOptions.map((option) => (
                  <button
                    key={option.value}
                    type="button"
                    aria-label={option.label}
                    aria-pressed={joinValue === option.value}
                    className={`rounded px-1.5 py-1 text-[10px] ${
                      joinValue === option.value
                        ? 'bg-active text-surface'
                        : 'bg-input/50 text-muted hover:bg-hover hover:text-surface'
                    }`}
                    onClick={() => setJoin(option.value as StrokeJoin)}
                  >
                    {option.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="flex items-center gap-2">
              <div className="flex-1">
                <div className="text-[10px] text-muted mb-1">{panels.strokeMiterLimit}</div>
                <NumberField
                  ariaLabel={panels.strokeMiterLimit}
                  dataProperty="stroke-miter-limit"
                  value={strokeCtx.miterLimit}
                  min={1}
                  onChange={(v) => strokeCtx.updateMiterLimit(v)}
                  onCommit={(v) => strokeCtx.commitMiterLimit(v)}
                />
              </div>
              <IconButton
                label={panels.strokeSides}
                onClick={() =>
                  strokeCtx.selectSide(sidesExpanded ? 'ALL' : 'CUSTOM', node)
                }
                className={sidesExpanded ? 'opacity-100' : ''}
                data-property="stroke-sides"
              >
                <span className="text-[10px] font-semibold">TRBL</span>
              </IconButton>
            </div>

            {sidesExpanded && (
              <div className="grid grid-cols-4 gap-1.5">
                {strokeCtx.borderSides.map((side) => (
                  <label key={side} className="flex flex-col gap-1">
                    <span className="text-[10px] text-muted capitalize">{side}</span>
                    <NumberField
                      ariaLabel={side}
                      min={0}
                      value={strokeCtx.borderWeight(node, side)}
                      onChange={(v) => strokeCtx.updateBorderWeight(side, v, node)}
                      onCommit={(v) => strokeCtx.updateBorderWeight(side, v, node)}
                    />
                  </label>
                ))}
              </div>
            )}

            <div className="flex-1">
              <div className="text-[10px] text-muted mb-1">Dashes (e.g. 5, 2)</div>
              <input
                type="text"
                className={inputClass}
                placeholder="None"
                value={dashPattern.join(', ')}
                data-property="stroke-dash"
                onChange={(e) => {
                  const val = e.target.value
                  const dashes = val.split(/[, ]+/).map(Number).filter(n => !isNaN(n))
                  updateNodeLevel({ dashPattern: dashes }, 'Change dash pattern')
                }}
              />
            </div>
          </div>
        )}
      </div>
    </PanelSection>
  )
}
