// src/components/properties/TypographySection.vue
<script setup lang="ts">
import { computed } from 'vue'

import { TypographyControlsRoot, useI18n } from '@openweave/vue'

import FontPicker from '@/components/font-picker/FontPicker.vue'
import FontSettingsPopover from '@/components/FontSettings/FontSettingsPopover.vue'
import NumberField from '@/components/inputs/NumberField.vue'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField.vue'
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import AppSwitch from '@/components/ui/AppSwitch.vue'
import IconButton from '@/components/ui/IconButton.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'
import { loadFont } from '@/app/editor/fonts'
import { appMenuShortcutLabel } from '@/app/shell/menu/shortcut'

const { panels, menu } = useI18n()
const fontLoader = { load: loadFont }
const alignmentOptions = computed(() => [
  { value: 'LEFT', label: panels.value.alignLeft },
  { value: 'CENTER', label: panels.value.alignCenterHorizontally },
  { value: 'RIGHT', label: panels.value.alignRight },
  { value: 'JUSTIFIED', label: panels.value.textAlignment }
])
const verticalAlignmentOptions = computed(() => [
  { value: 'TOP', label: panels.value.alignTop },
  { value: 'CENTER', label: panels.value.alignCenterVertically },
  { value: 'BOTTOM', label: panels.value.alignBottom }
])
const textCaseOptions = computed(() => [
  { value: 'ORIGINAL', label: panels.value.textCaseOriginal },
  { value: 'UPPER', label: panels.value.textCaseUpper },
  { value: 'LOWER', label: panels.value.textCaseLower },
  { value: 'TITLE', label: panels.value.textCaseTitle }
])
const truncationOptions = computed(() => [
  { value: 'DISABLED', label: panels.value.truncationDisabled },
  { value: 'ENDING', label: panels.value.truncationEnding }
])
const commonFeatures = computed(() => [
  { tag: 'LIGA', label: panels.value.standardLigatures },
  { tag: 'CALT', label: panels.value.contextualAlternates },
  { tag: 'KERN', label: panels.value.kerning }
])

function featureEnabled(features: Array<{ tag: string; enabled: boolean }>, tag: string) {
  return features.find((feature) => feature.tag === tag)?.enabled ?? true
}
</script>

<template>
  <TypographyControlsRoot v-slot="ctx" :font-loader="fontLoader">
    <PanelSection v-if="ctx.node.value" :label="panels.typography">
      <SharedStyleField kind="text" :label="panels.textStyle" />

      <div class="mb-1.5 flex min-w-0 items-center gap-1.5">
        <FontPicker
          class="min-w-0 flex-1"
          :model-value="ctx.node.value.fontFamily"
          :label="panels.fontFamily"
          @select="ctx.actions.setFamily"
        />
        <FontSettingsPopover />
        <Tip
          v-if="ctx.hasMissingFonts.value"
          :label="
            'Missing font' +
            (ctx.missingFonts.value.length > 1 ? 's' : '') +
            ': ' +
            ctx.missingFonts.value.join(', ')
          "
        >
          <icon-lucide-alert-triangle
            role="img"
            :aria-label="
              'Missing font' +
              (ctx.missingFonts.value.length > 1 ? 's' : '') +
              ': ' +
              ctx.missingFonts.value.join(', ')
            "
            class="size-3.5 shrink-0 text-[var(--color-warning-action)]"
          />
        </Tip>
      </div>

      <PanelGrid :columns="2" class="mb-3">
        <PanelFieldGroup :label="panels.fontWeight">
          <AppSelect
            :label="panels.fontWeight"
            :model-value="ctx.node.value.fontWeight"
            :options="ctx.weights"
            @update:model-value="ctx.actions.setWeight(+$event)"
          />
        </PanelFieldGroup>
        <PanelFieldGroup :label="panels.fontSize">
          <VariableNumberField
            :model-value="ctx.node.value.fontSize"
            :aria-label="panels.fontSize"
            :min="1"
            :max="1000"
            :node-id="ctx.node.value.id"
            binding-path="fontSize"
            @update:model-value="ctx.actions.updateProp('fontSize', $event)"
            @commit="(v: number, p: number) => ctx.actions.commitProp('fontSize', v, p)"
          />
        </PanelFieldGroup>
      </PanelGrid>

      <PanelGrid :columns="2" class="mb-3">
        <PanelFieldGroup :label="panels.lineHeight">
          <VariableNumberField
            :model-value="
              ctx.node.value.lineHeight ?? Math.round((ctx.node.value.fontSize || 14) * 1.2)
            "
            :aria-label="panels.lineHeight"
            :min="0"
            :node-id="ctx.node.value.id"
            binding-path="lineHeight"
            @update:model-value="ctx.actions.updateProp('lineHeight', $event)"
            @commit="(v: number, p: number) => ctx.actions.commitProp('lineHeight', v, p)"
          >
            <template #icon>
              <icon-lucide-baseline class="size-3" />
            </template>
          </VariableNumberField>
        </PanelFieldGroup>
        <PanelFieldGroup :label="panels.letterSpacing">
          <VariableNumberField
            suffix="%"
            :model-value="ctx.node.value.letterSpacing"
            :aria-label="panels.letterSpacing"
            :node-id="ctx.node.value.id"
            binding-path="letterSpacing"
            @update:model-value="ctx.actions.updateProp('letterSpacing', $event)"
            @commit="(v: number, p: number) => ctx.actions.commitProp('letterSpacing', v, p)"
          >
            <template #icon>
              <icon-lucide-a-large-small class="size-3" />
            </template>
          </VariableNumberField>
        </PanelFieldGroup>
      </PanelGrid>

      <PanelFieldGroup :label="panels.direction" class="mb-3">
        <AppSelect
          :label="panels.direction"
          :model-value="ctx.node.value.textDirection"
          :options="[
            { value: 'AUTO', label: panels.auto },
            { value: 'LTR', label: 'LTR' },
            { value: 'RTL', label: 'RTL' }
          ]"
          @update:model-value="ctx.actions.setDirection($event as 'AUTO' | 'LTR' | 'RTL')"
        />
      </PanelFieldGroup>

      <PanelFieldGroup :label="panels.textAlignment" class="mb-3">
        <SegmentedControl
          :model-value="ctx.node.value.textAlignHorizontal"
          :options="alignmentOptions"
          :label="panels.textAlignment"
          @change="ctx.actions.align($event as 'LEFT' | 'CENTER' | 'RIGHT' | 'JUSTIFIED')"
        >
          <template #option="{ option }">
            <icon-lucide-align-left v-if="option.value === 'LEFT'" class="size-3.5" />
            <icon-lucide-align-center v-else-if="option.value === 'CENTER'" class="size-3.5" />
            <icon-lucide-align-right v-else-if="option.value === 'RIGHT'" class="size-3.5" />
            <icon-lucide-align-justify v-else class="size-3.5" />
          </template>
        </SegmentedControl>
      </PanelFieldGroup>

      <PanelFieldGroup :label="panels.verticalTextAlignment" class="mb-3">
        <SegmentedControl
          :model-value="ctx.node.value.textAlignVertical"
          :options="verticalAlignmentOptions"
          :label="panels.verticalTextAlignment"
          @change="ctx.actions.setVerticalAlign($event as 'TOP' | 'CENTER' | 'BOTTOM')"
        >
          <template #option="{ option }">
            <icon-lucide-align-vertical-justify-start
              v-if="option.value === 'TOP'"
              class="size-3.5"
            />
            <icon-lucide-align-vertical-justify-center
              v-else-if="option.value === 'CENTER'"
              class="size-3.5"
            />
            <icon-lucide-align-vertical-justify-end v-else class="size-3.5" />
          </template>
        </SegmentedControl>
      </PanelFieldGroup>

      <PanelFieldGroup
        :label="panels.textFormatting"
        class="mb-3"
        :ui="{ container: 'flex-row gap-1.5' }"
      >
        <div
          class="inline-flex items-center gap-0.5 rounded bg-panel-field p-0.5 hover:bg-panel-field-hover"
          role="toolbar"
          :aria-label="panels.textFormatting"
        >
          <IconButton
            :label="`${menu.bold} (${appMenuShortcutLabel('text.bold')})`"
            size="md"
            :active="ctx.activeFormatting.value.includes('bold')"
            @click="ctx.actions.toggleBold"
          >
            <icon-lucide-bold class="size-3.5" />
          </IconButton>
          <IconButton
            :label="`${menu.italic} (${appMenuShortcutLabel('text.italic')})`"
            size="md"
            :active="ctx.activeFormatting.value.includes('italic')"
            @click="ctx.actions.toggleItalic"
          >
            <icon-lucide-italic class="size-3.5" />
          </IconButton>
          <IconButton
            :label="`${menu.underline} (${appMenuShortcutLabel('text.underline')})`"
            size="md"
            :active="ctx.activeFormatting.value.includes('underline')"
            @click="ctx.actions.toggleDecoration('UNDERLINE')"
          >
            <icon-lucide-underline class="size-3.5" />
          </IconButton>
          <IconButton
            :label="menu.strikethrough"
            size="md"
            :active="ctx.activeFormatting.value.includes('strikethrough')"
            @click="ctx.actions.toggleDecoration('STRIKETHROUGH')"
          >
            <icon-lucide-strikethrough class="size-3.5" />
          </IconButton>
        </div>
      </PanelFieldGroup>

      <PanelGrid :columns="2" class="mb-3">
        <PanelFieldGroup :label="panels.textCase">
          <AppSelect
            :label="panels.textCase"
            :model-value="ctx.node.value.textCase"
            :options="textCaseOptions"
            @update:model-value="
              ctx.actions.setTextCase($event as 'ORIGINAL' | 'UPPER' | 'LOWER' | 'TITLE')
            "
          />
        </PanelFieldGroup>
        <PanelFieldGroup :label="panels.truncation">
          <AppSelect
            :label="panels.truncation"
            :model-value="ctx.node.value.textTruncation"
            :options="truncationOptions"
            @update:model-value="ctx.actions.setTruncation($event as 'DISABLED' | 'ENDING')"
          />
        </PanelFieldGroup>
      </PanelGrid>

      <PanelFieldGroup
        v-if="ctx.node.value.textTruncation === 'ENDING'"
        :label="panels.maxLines"
        class="mb-3"
      >
        <NumberField
          :model-value="ctx.node.value.maxLines ?? 1"
          :aria-label="panels.maxLines"
          :min="1"
          :step="1"
          data-property="max-lines"
          @update:model-value="ctx.actions.updateProp('maxLines', Math.max(1, Math.round($event)))"
          @commit="
            (value: number, previous: number) => ctx.actions.commitProp('maxLines', value, previous)
          "
        />
      </PanelFieldGroup>

      <div class="mb-3 grid gap-2.5">
        <label
          v-for="feature in commonFeatures"
          :key="feature.tag"
          class="flex items-center justify-between gap-1.5 text-[11px] text-muted/70"
        >
          <span>{{ feature.label }}</span>
          <AppSwitch
            :model-value="featureEnabled(ctx.node.value.fontFeatures, feature.tag)"
            :label="feature.label"
            :data-property="`font-feature-${feature.tag.toLowerCase()}`"
            @update:model-value="ctx.actions.setFontFeature(feature.tag, $event)"
          />
        </label>
      </div>
    </PanelSection>
  </TypographyControlsRoot>
</template>

// src/components/properties/TypographySection.tsx
import React from 'react'
import { useTypography, useI18n } from '@openweave/react'
import type { SceneNode } from '@openweave/scene-graph'
import {
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Baseline,
  ALargeSmall,
  AlertTriangle
} from 'lucide-react'

import FontPicker from '@/components/font-picker/FontPicker'
import FontSettingsPopover from '@/components/font-settings/FontSettingsPopover'
import NumberField from '@/components/inputs/NumberField'
import IconButton from '@/components/ui/IconButton'
import PanelGrid from '@/components/ui/panel/PanelGrid'
import PanelSection from '@/components/ui/panel/PanelSection'
import { AppSwitch } from '@/components/ui/AppSwitch'
import { AppSelect } from '@/components/ui/AppSelect'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField'
import Tip from '@/components/ui/Tip'

type TextAlign = SceneNode['textAlignHorizontal']
type TextVerticalAlign = SceneNode['textAlignVertical']
type TextCase = SceneNode['textCase']
type TextDirection = SceneNode['textDirection']
type TextTruncation = SceneNode['textTruncation']

const inputClass = 'w-full bg-input/50 rounded px-2 py-1 border border-border text-surface text-xs outline-none focus:border-accent'

function PanelFieldGroup({ label, children, className = '' }: { label: string, children: React.ReactNode, className?: string }) {
  return (
    <label className={`flex flex-col gap-1.5 ${className}`}>
      <span className="text-muted text-[10px]">{label}</span>
      {children}
    </label>
  )
}

export default function TypographySection() {
  // Destructure properties from useTypography.
  // It provides standard properties and actions to interact with TextNode
  const {
    node,
    fontFamily,
    fontWeight,
    fontSize,
    weights,
    activeFormatting,
    setFamily,
    setWeight,
    setAlign,
    setVerticalAlign,
    setTextCase,
    setDirection,
    setTruncation,
    setFontFeature,
    toggleBold,
    toggleItalic,
    toggleDecoration,
    updateProp,
    commitProp,
    missingFonts,
    hasMissingFonts
  } = useTypography()
  const { panels } = useI18n()

  if (!node || !('textAlignHorizontal' in node)) return null

  const lineHeight = node.lineHeight ?? ''
  const letterSpacing = node.letterSpacing
  const textAlign = node.textAlignHorizontal
  const verticalAlign = node.textAlignVertical
  const textCase = node.textCase
  const textDirection = node.textDirection
  const textTruncation = node.textTruncation
  const maxLines = node.maxLines ?? 1

  function featureEnabled(features: Array<{ tag: string; enabled: boolean }> | undefined, tag: string) {
    return features?.find((feature) => feature.tag === tag)?.enabled ?? true
  }

  return (
    <PanelSection label="Typography">
      <SharedStyleField kind="text" label={panels.textStyle} />
      <div className="mb-2.5">
        <PanelFieldGroup label="Font">
          <div className="flex items-center gap-1.5">
            <FontPicker value={fontFamily} onSelect={(family) => { void setFamily(family) }} />
            <FontSettingsPopover />
            {hasMissingFonts && (
              <Tip label={`Missing font${missingFonts.length > 1 ? 's' : ''}: ${missingFonts.join(', ')}`}>
                <AlertTriangle
                  role="img"
                  aria-label={`Missing font${missingFonts.length > 1 ? 's' : ''}: ${missingFonts.join(', ')}`}
                  className="size-3.5 shrink-0 text-warning-text"
                />
              </Tip>
            )}
          </div>
        </PanelFieldGroup>
      </div>

      <PanelGrid columns={2} className="mb-3">
        <PanelFieldGroup label={panels.fontWeight}>
          <select
            className={inputClass + ' h-6'}
            aria-label={panels.fontWeight}
            value={fontWeight}
            onChange={(e) => { void setWeight(Number(e.target.value)) }}
          >
            {weights.map((w: any) => (
              <option key={w.value} value={w.value}>{w.label}</option>
            ))}
          </select>
        </PanelFieldGroup>
        <PanelFieldGroup label={panels.fontSize}>
          <NumberField
            ariaLabel={panels.fontSize}
            value={fontSize}
            min={1}
            max={1000}
            onChange={(v) => updateProp('fontSize', v)}
            onCommit={(v, p) => commitProp('fontSize', v, p)}
          />
        </PanelFieldGroup>
      </PanelGrid>

      <PanelGrid columns={2} className="mb-3">
        <PanelFieldGroup label={panels.lineHeight}>
          <NumberField
            ariaLabel={panels.lineHeight}
            value={typeof lineHeight === 'number' ? lineHeight : Math.round((fontSize || 14) * 1.2)}
            min={0}
            onChange={(v) => updateProp('lineHeight', v)}
            onCommit={(v, p) => commitProp('lineHeight', v, p)}
            icon={<Baseline className="size-3" />}
          />
        </PanelFieldGroup>
        <PanelFieldGroup label={panels.letterSpacing}>
          <NumberField
            ariaLabel={panels.letterSpacing}
            suffix="%"
            value={letterSpacing}
            onChange={(v) => updateProp('letterSpacing', v)}
            onCommit={(v, p) => commitProp('letterSpacing', v, p)}
            icon={<ALargeSmall className="size-3" />}
          />
        </PanelFieldGroup>
      </PanelGrid>

      <PanelFieldGroup label="Direction" className="mb-3">
        <select
          className={inputClass + ' h-6'}
          value={textDirection}
          onChange={(e) => setDirection(e.target.value as TextDirection)}
        >
          <option value="AUTO">Auto</option>
          <option value="LTR">LTR</option>
          <option value="RTL">RTL</option>
        </select>
      </PanelFieldGroup>

      <PanelFieldGroup label={panels.textAlignment} className="mb-3">
        <div
          role="group"
          aria-label={panels.textAlignment}
          className="inline-flex items-center gap-0.5 rounded bg-panel-field p-0.5"
        >
          {[
            { value: 'LEFT', label: panels.alignLeft, icon: <AlignLeft className="size-3.5" /> },
            { value: 'CENTER', label: panels.alignCenterHorizontally, icon: <AlignCenter className="size-3.5" /> },
            { value: 'RIGHT', label: panels.alignRight, icon: <AlignRight className="size-3.5" /> },
            { value: 'JUSTIFIED', label: panels.textAlignment, icon: <AlignJustify className="size-3.5" /> }
          ].map((option) => (
            <IconButton
              key={option.value}
              label={option.label}
              size="md"
              active={textAlign === option.value}
              onClick={() => setAlign(option.value as TextAlign)}
            >
              {option.icon}
            </IconButton>
          ))}
        </div>
      </PanelFieldGroup>

      <PanelFieldGroup label={panels.verticalTextAlignment} className="mb-3">
        <div
          role="group"
          aria-label={panels.verticalTextAlignment}
          className="inline-flex items-center gap-0.5 rounded bg-panel-field p-0.5"
        >
          {[
            { value: 'TOP', label: panels.alignTop, icon: <AlignVerticalJustifyStart className="size-3.5" /> },
            { value: 'CENTER', label: panels.alignCenterVertically, icon: <AlignVerticalJustifyCenter className="size-3.5" /> },
            { value: 'BOTTOM', label: panels.alignBottom, icon: <AlignVerticalJustifyEnd className="size-3.5" /> }
          ].map((option) => (
            <IconButton
              key={option.value}
              label={option.label}
              size="md"
              active={verticalAlign === option.value}
              onClick={() => setVerticalAlign(option.value as TextVerticalAlign)}
            >
              {option.icon}
            </IconButton>
          ))}
        </div>
      </PanelFieldGroup>

      <PanelFieldGroup label="Text formatting" className="mb-3">
        <div
          className="inline-flex items-center gap-0.5 rounded bg-panel-field p-0.5"
          role="toolbar"
        >
          <IconButton
            label="Bold"
            size="md"
            active={activeFormatting.includes('bold')}
            onClick={toggleBold}
          >
            <Bold className="size-3.5" />
          </IconButton>
          <IconButton
            label="Italic"
            size="md"
            active={activeFormatting.includes('italic')}
            onClick={toggleItalic}
          >
            <Italic className="size-3.5" />
          </IconButton>
          <IconButton
            label="Underline"
            size="md"
            active={activeFormatting.includes('underline')}
            onClick={() => toggleDecoration('UNDERLINE')}
          >
            <Underline className="size-3.5" />
          </IconButton>
          <IconButton
            label="Strikethrough"
            size="md"
            active={activeFormatting.includes('strikethrough')}
            onClick={() => toggleDecoration('STRIKETHROUGH')}
          >
            <Strikethrough className="size-3.5" />
          </IconButton>
        </div>
      </PanelFieldGroup>

      <PanelGrid columns={2} className="mb-3">
        <PanelFieldGroup label={panels.textCase}>
          <AppSelect
            label={panels.textCase}
            value={textCase}
            onValueChange={(v) => setTextCase(v as TextCase)}
            options={[
              { value: 'ORIGINAL', label: panels.textCaseOriginal },
              { value: 'UPPER', label: panels.textCaseUpper },
              { value: 'LOWER', label: panels.textCaseLower },
              { value: 'TITLE', label: panels.textCaseTitle }
            ]}
          />
        </PanelFieldGroup>
        <PanelFieldGroup label={panels.truncation}>
          <AppSelect
            label={panels.truncation}
            value={textTruncation}
            onValueChange={(v) => setTruncation(v as TextTruncation)}
            options={[
              { value: 'DISABLED', label: panels.truncationDisabled },
              { value: 'ENDING', label: panels.truncationEnding }
            ]}
          />
        </PanelFieldGroup>
      </PanelGrid>

      {textTruncation === 'ENDING' && (
        <PanelFieldGroup label={panels.maxLines} className="mb-3">
          <NumberField
            ariaLabel={panels.maxLines}
            value={maxLines}
            min={1}
            step={1}
            onChange={(v) => updateProp('maxLines', Math.max(1, Math.round(v)))}
            onCommit={(v, p) => commitProp('maxLines', v, p)}
          />
        </PanelFieldGroup>
      )}

      <div className="mb-3 grid gap-2.5">
        <label className="flex items-center justify-between gap-1.5 text-[11px] text-muted/70">
          <span>Standard ligatures</span>
          <AppSwitch
            value={featureEnabled(node.fontFeatures, 'LIGA')}
            onValueChange={(val: boolean) => setFontFeature('LIGA', val)}
          />
        </label>
        <label className="flex items-center justify-between gap-1.5 text-[11px] text-muted/70">
          <span>Contextual alternates</span>
          <AppSwitch
            value={featureEnabled(node.fontFeatures, 'CALT')}
            onValueChange={(val: boolean) => setFontFeature('CALT', val)}
          />
        </label>
        <label className="flex items-center justify-between gap-1.5 text-[11px] text-muted/70">
          <span>Kerning</span>
          <AppSwitch
            value={featureEnabled(node.fontFeatures, 'KERN')}
            onValueChange={(val: boolean) => setFontFeature('KERN', val)}
          />
        </label>
      </div>
    </PanelSection>
  )
}
