// src/components/properties/VariablesSection.vue
<script setup lang="ts">
import { computed } from 'vue'

import IconButton from '@/components/ui/IconButton.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import { useI18n, useSceneComputed } from '@openweave/vue'

import { useEditorStore } from '@/app/editor/active-store'

const emit = defineEmits<{ openDialog: [] }>()

const editor = useEditorStore()
const collectionCount = useSceneComputed(() => {
  void editor.state.sceneVersion
  return editor.getCollectionCount()
})
const variableCount = useSceneComputed(() => {
  void editor.state.sceneVersion
  return editor.getVariableCount()
})
const hasVariables = computed(() => variableCount.value > 0)
const { panels } = useI18n()
</script>

<template>
  <PanelSection :label="panels.variables" :empty="!hasVariables">
    <template #actions>
      <IconButton :label="panels.openVariables" @click="emit('openDialog')">
        <icon-lucide-settings-2 class="size-3.5" />
      </IconButton>
    </template>
    <div v-if="hasVariables" class="mt-1 text-[11px] text-muted">
      {{ variableCount }} / {{ collectionCount }}
    </div>
    <div v-else class="mt-1 text-[11px] text-muted">{{ panels.noLocalVariables }}</div>
  </PanelSection>
</template>

// src/components/properties/VariablesSection.tsx
import { Settings2 } from 'lucide-react'
import React, { useState } from 'react'

import { useI18n } from '@openweave/react'

import { getActiveEditorStore } from '@/app/editor/active-store'
import IconButton from '@/components/ui/IconButton'
import PanelSection from '@/components/ui/panel/PanelSection'
import VariablesDialog from '@/components/variables/VariablesDialog'

export default function VariablesSection() {
  const { panels } = useI18n()
  const editor = getActiveEditorStore()
  const [dialogOpen, setDialogOpen] = useState(false)

  // Note: Since this component isn't automatically reactive to the number of variables
  // via a hook (as useEditorStore doesn't return state), we'd typically need to subscribe
  // to editor events, but getting it directly for initial render is fine.
  // We can use the useVariablesEditor which has `collections` if needed,
  // or just read from editor store directly.
  const collectionCount = editor.getCollectionCount()
  const variableCount = editor.getVariableCount()
  const hasVariables = variableCount > 0

  return (
    <>
      <PanelSection label={panels.variables}>
        <div className="flex flex-col gap-1">
          <div className="flex items-center justify-between group">
            {hasVariables ? (
              <span className="text-[11px] text-muted">
                {variableCount} / {collectionCount}
              </span>
            ) : (
              <span className="text-[11px] text-muted">{panels.noLocalVariables}</span>
            )}

            <IconButton label={panels.openVariables} onClick={() => setDialogOpen(true)}>
              <Settings2 className="size-3.5" />
            </IconButton>
          </div>
        </div>
      </PanelSection>

      {dialogOpen && <VariablesDialog open={dialogOpen} onClose={() => setDialogOpen(false)} />}
    </>
  )
}
