// src/components/variables/VariablesDialog.tsx
import React, { useCallback, useState } from 'react'
import { createPortal } from 'react-dom'
import {
  Palette,
  Hash,
  Type,
  ToggleLeft,
  X,
  Plus,
  FolderPlus,
  Trash2,
  Search,
  ChevronDown
} from 'lucide-react'
import { flexRender } from '@tanstack/react-table'

import { useEventListener } from 'usehooks-ts'
import { useVariablesEditor, useI18n } from '@openweave/react'
import type { Color } from '@openweave/scene-graph/primitives'
import type { VariableType } from '@openweave/scene-graph'
import Tip from '@/components/ui/Tip'

import { ColorSwatchPopover } from '@/components/color-picker/ColorSwatchPopover'

// --- Color adapter ---------------------------------------------------------

interface VariableColorInputProps {
  color: Color
  onUpdate: (color: Color) => void
}

/**
 * Adapter that gives the variables table's expected `{ color, onUpdate }`
 * contract while reusing the shared swatch/popover picker.
 */
function VariableColorInput({ color, onUpdate }: VariableColorInputProps) {
  return <ColorSwatchPopover color={color} onChange={onUpdate} />
}

const variableTypeIcons: Record<VariableType, React.ElementType> = {
  COLOR: Palette,
  FLOAT: Hash,
  STRING: Type,
  BOOLEAN: ToggleLeft
}

// --- Dialog ----------------------------------------------------------------

export interface VariablesDialogProps {
  _brand?: 'VariablesDialog'
  open: boolean
  onClose: () => void
}

const iconButtonClass =
  'flex size-6 shrink-0 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted transition-colors hover:bg-hover hover:text-surface'

function modeIdOf(columnId: string): string | undefined {
  return columnId.startsWith('mode-') ? columnId.slice(5) : undefined
}

function VariablesEditor({ onClose }: { onClose: () => void }) {
  const ctx = useVariablesEditor({
    colorInput: VariableColorInput,
    icons: variableTypeIcons,
    fallbackIcon: ToggleLeft,
    deleteIcon: X
  })
  const { dialogs, panels, variableTypes } = useI18n()
  const [addOpen, setAddOpen] = useState(false)
  const activeCollection = ctx.collections.find((col) => col.id === ctx.activeCollectionId)

  const variableTypeOptions: { type: VariableType; label: string; description: string }[] = [
    { type: 'COLOR', label: variableTypes.color, description: dialogs.addVariableColorDescription },
    { type: 'FLOAT', label: variableTypes.number, description: dialogs.addVariableNumberDescription },
    { type: 'STRING', label: variableTypes.text, description: dialogs.addVariableTextDescription },
    { type: 'BOOLEAN', label: variableTypes.boolean, description: dialogs.addVariableBooleanDescription }
  ]

  if (!ctx.hasCollections) {
    return (
      <div className="flex flex-1 flex-col" data-test-id="variables-empty">
        <div className="flex shrink-0 items-center justify-between border-b border-border px-4 py-3">
          <h2 className="text-sm font-semibold text-surface">{dialogs.localVariables}</h2>
          <button type="button" className={iconButtonClass} aria-label={dialogs.close} onClick={onClose}>
            <X className="size-4" />
          </button>
        </div>
        <div className="flex flex-1 flex-col items-center justify-center gap-3 text-muted">
          <FolderPlus className="size-6" />
          <p className="text-xs">{dialogs.noVariableCollections}</p>
          <button
            type="button"
            data-test-id="variables-create-collection"
            className="cursor-pointer rounded bg-hover px-3 py-1.5 text-xs text-surface hover:bg-border"
            onClick={() => ctx.addCollection()}
          >
            {dialogs.createCollection}
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-1 flex-col overflow-hidden">
      {/* Collection tabs + toolbar */}
      <div className="flex shrink-0 items-center border-b border-border">
        <div className="flex flex-1 gap-0.5 overflow-x-auto px-3 py-1">
          {ctx.collections.map((col) =>
            ctx.collectionRename.editingId === col.id ? (
              <input
                key={col.id}
                ref={ctx.collectionRename.focusInput}
                className="w-24 rounded border border-accent bg-input px-2 py-0.5 text-xs text-surface outline-none"
                defaultValue={col.name}
                onBlur={(event) => ctx.collectionRename.commit(col.id, event)}
                onKeyDown={ctx.collectionRename.onKeydown}
              />
            ) : (
              <button
                key={col.id}
                type="button"
                data-test-id="variables-collection-tab"
                data-active={col.id === ctx.activeCollectionId}
                className="cursor-pointer rounded border-none px-2.5 py-1 text-xs whitespace-nowrap text-muted transition-colors data-[active=true]:bg-hover data-[active=true]:text-surface"
                onClick={() => ctx.setActiveCollectionId(col.id)}
                onDoubleClick={() => ctx.startRenameCollection(col.id)}
              >
                {col.name}
              </button>
            )
          )}
        </div>

        <div className="flex items-center gap-1.5 px-3">
          <div className="flex items-center gap-1 rounded border border-border px-2 py-0.5">
            <Search className="size-3 text-muted" />
            <input
              value={ctx.searchTerm}
              data-test-id="variables-search-input"
              className="w-24 border-none bg-transparent text-xs text-surface outline-none placeholder:text-muted"
              placeholder={dialogs.search}
              onChange={(event) => ctx.setSearchTerm(event.target.value)}
            />
          </div>
          <Tip label={dialogs.createCollection}>
            <button
              type="button"
              data-test-id="variables-add-collection"
              className={iconButtonClass}
              onClick={() => ctx.addCollection()}
            >
              <FolderPlus className="size-3.5" />
            </button>
          </Tip>
          <Tip label={dialogs.deleteCollection}>
            <button
              type="button"
              data-test-id="variables-delete-collection"
              className={iconButtonClass}
              onClick={() => ctx.removeCollection(ctx.activeCollectionId)}
            >
              <Trash2 className="size-3.5" />
            </button>
          </Tip>
          <button type="button" className={iconButtonClass} aria-label={dialogs.close} onClick={onClose}>
            <X className="size-4" />
          </button>
        </div>
      </div>

      {/* Table */}
      <div className="flex-1 overflow-auto">
        <table
          className="w-full border-collapse"
          style={{ width: `${ctx.table.getCenterTotalSize()}px` }}
        >
          <thead className="sticky top-0 z-10 bg-panel">
            {ctx.table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id} className="border-b border-border">
                {headerGroup.headers.map((header) => {
                  const modeId = modeIdOf(header.column.id)
                  return (
                    <th
                      key={header.id}
                      className="relative px-4 py-2 text-left text-[11px] font-medium text-muted"
                      style={{ width: `${header.getSize()}px` }}
                    >
                      {modeId && ctx.modeRename.editingId === modeId ? (
                        <input
                          ref={ctx.modeRename.focusInput}
                          className="-mx-1 w-full rounded border border-accent bg-input px-1 py-0 text-[11px] font-medium text-surface outline-none"
                          defaultValue={String(header.column.columnDef.header)}
                          onBlur={(event) => ctx.modeRename.commit(modeId, event)}
                          onKeyDown={ctx.modeRename.onKeydown}
                        />
                      ) : (
                        <span
                          className={modeId ? 'cursor-text' : undefined}
                          data-default={modeId === activeCollection?.defaultModeId || undefined}
                          onDoubleClick={
                            modeId ? () => ctx.startRenameMode(modeId) : undefined
                          }
                        >
                          {header.isPlaceholder
                            ? null
                            : flexRender(header.column.columnDef.header, header.getContext())}
                        </span>
                      )}
                    </th>
                  )
                })}
                <th className="w-8 px-1 py-2">
                  <Tip label={dialogs.addMode}>
                    <button
                      type="button"
                      data-test-id="variables-add-mode"
                      className="flex size-5 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                      onClick={() => ctx.addMode()}
                    >
                      <Plus className="size-3" />
                    </button>
                  </Tip>
                </th>
              </tr>
            ))}
          </thead>
          <tbody>
            {ctx.table.getRowModel().rows.map((row) => (
              <tr
                key={row.id}
                data-test-id="variable-row"
                className="group border-b border-border hover:bg-hover/40"
              >
                {row.getVisibleCells().map((cell) => (
                  <td
                    key={cell.id}
                    className="px-4 py-1.5"
                    style={{ width: `${cell.column.getSize()}px` }}
                  >
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
                <td />
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Add variable footer */}
      <div className="relative flex w-full shrink-0 items-center justify-between gap-2 border-t border-border px-4 py-2">
        <span className="text-xs text-muted">{panels.createVariable}</span>
        <div className="relative">
          <button
            type="button"
            data-test-id="variables-add-variable"
            className="flex cursor-pointer items-center gap-1.5 rounded bg-hover px-2.5 py-1.5 text-xs text-surface hover:bg-border"
            onClick={() => setAddOpen((open) => !open)}
          >
            <Plus className="size-3.5" />
            {panels.add}
            <ChevronDown className="size-3" />
          </button>
          {addOpen && (
            <div className="absolute right-0 bottom-full mb-2 w-48 rounded border border-border bg-surface py-1 shadow-lg">
              {variableTypeOptions.map((item) => {
                const Icon = variableTypeIcons[item.type]
                return (
                  <button
                    key={item.type}
                    type="button"
                    data-test-id={`variables-add-${item.type.toLowerCase()}`}
                    className="flex w-full items-center gap-2 px-2.5 py-1.5 text-left text-xs text-surface hover:bg-hover"
                    onClick={() => {
                      ctx.addVariable(item.type)
                      setAddOpen(false)
                    }}
                  >
                    <Icon className="size-3.5 text-muted" />
                    <span className="flex min-w-0 flex-1 flex-col">
                      <span>{item.label}</span>
                      <span className="truncate text-[10px] text-muted">{item.description}</span>
                    </span>
                  </button>
                )
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export function VariablesDialog({ open, onClose }: VariablesDialogProps) {
  const { dialogs } = useI18n()
  const onKey = useCallback(
    (event: KeyboardEvent) => {
      if (!open) return
      if (event.key === 'Escape') onClose()
    },
    [open, onClose]
  )
  useEventListener('keydown', onKey)

  if (!open) return null

  // Portal to <body> so the fixed overlay escapes panels that set
  // `contain: paint layout` (which would otherwise clamp it to the panel box).
  return createPortal(
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      data-test-id="variables-dialog"
      onClick={onClose}
    >
      <div
        className="flex h-[32rem] w-[50rem] max-w-[90vw] flex-col overflow-hidden rounded-lg border border-border bg-surface shadow-xl"
        role="dialog"
        aria-modal="true"
        aria-label={dialogs.localVariables}
        onClick={(event) => event.stopPropagation()}
      >
        <VariablesEditor onClose={onClose} />
      </div>
    </div>,
    document.body
  )
}

export default VariablesDialog

// src/components/variables/VariablesDialog.vue
<script setup lang="ts">
import { watch, type Component } from 'vue'
import { tv } from 'tailwind-variants'
import { templateRef } from '@vueuse/core'
import {
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuPortal,
  ContextMenuRoot,
  ContextMenuSeparator,
  ContextMenuTrigger,
  DialogClose,
  DialogTitle,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuPortal,
  DropdownMenuRoot,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  TabsContent,
  TabsList,
  TabsRoot,
  TabsTrigger
} from 'reka-ui'
import { FlexRender } from '@tanstack/vue-table'

import { variablesAddTestId, vTestId, useI18n, useVariablesEditor } from '@openweave/vue'

import IconHash from '~icons/lucide/hash'
import IconPalette from '~icons/lucide/palette'
import IconToggleLeft from '~icons/lucide/toggle-left'
import IconType from '~icons/lucide/type'
import IconX from '~icons/lucide/x'
import ColorInput from '@/components/ColorPicker/ColorInput.vue'
import AppPlaceholder from '@/components/ui/AppPlaceholder.vue'
import Tip from '@/components/ui/Tip.vue'
import { AppDialogRoot } from '@/components/ui/dialog'
import { useMenuUI } from '@/components/ui/menu'
import variableTableTheme from '@/theme/variable-table'

import type { VariableType } from '@openweave/scene-graph'

const open = defineModel<boolean>('open', { default: false })
const menuCls = useMenuUI({ content: 'w-40', item: 'justify-start gap-2' })
const addVariableMenuCls = useMenuUI({ content: 'w-48' })
const variableTable = tv(variableTableTheme)
const tableStyles = variableTable()

const variableTypeIcons: Record<VariableType, Component> = {
  COLOR: IconPalette,
  FLOAT: IconHash,
  STRING: IconType,
  BOOLEAN: IconToggleLeft
}

const { dialogs, panels, variableTypes: variableTypeText } = useI18n()

const variableTypes: Array<{
  type: VariableType
  label: () => string
  description: () => string
}> = [
  {
    type: 'COLOR',
    label: () => variableTypeText.value.color,
    description: () => variableTypeText.value.colorHint
  },
  {
    type: 'FLOAT',
    label: () => variableTypeText.value.number,
    description: () => variableTypeText.value.numberHint
  },
  {
    type: 'STRING',
    label: () => variableTypeText.value.text,
    description: () => variableTypeText.value.textHint
  },
  {
    type: 'BOOLEAN',
    label: () => variableTypeText.value.boolean,
    description: () => variableTypeText.value.booleanHint
  }
]

const ctx = useVariablesEditor({
  colorInput: ColorInput,
  icons: variableTypeIcons,
  fallbackIcon: IconToggleLeft,
  deleteIcon: IconX
})
const collectionInput = templateRef<HTMLInputElement>('collectionInput')
const modeInput = templateRef<HTMLInputElement>('modeInput')

watch(collectionInput, (input) => {
  void ctx.collectionRename.focusInput(input)
})
watch(modeInput, (input) => {
  void ctx.modeRename.focusInput(input)
})

function getModeId(columnId: string): string | undefined {
  return columnId.startsWith('mode-') ? columnId.slice(5) : undefined
}

function modeId(columnId: string): string {
  return columnId.slice(5)
}

function modeLabelClass(defaultMode: boolean) {
  return variableTable({ defaultMode }).modeLabel()
}

function resizeHandleClass(resizing: boolean) {
  return variableTable({ resizing }).resizeHandle()
}
</script>

<template>
  <AppDialogRoot
    v-model:open="open"
    height="tall"
    :ui="{ content: 'w-[800px] max-w-[90vw]' }"
    data-test-id="variables-dialog"
    :aria-describedby="undefined"
  >
    <DialogTitle class="sr-only">{{ dialogs.localVariables }}</DialogTitle>
    <div v-if="!ctx.hasCollections.value" class="flex flex-1 flex-col">
      <div class="flex shrink-0 items-center justify-between border-b border-border px-4 py-3">
        <h2 class="text-sm font-semibold text-surface">{{ dialogs.localVariables }}</h2>
        <DialogClose
          :aria-label="dialogs.close"
          class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
        >
          <icon-lucide-x class="size-4" />
        </DialogClose>
      </div>
      <AppPlaceholder :label="dialogs.noVariableCollections">
        <template #icon>
          <icon-lucide-folder class="size-5" />
        </template>
        <template #action>
          <button
            data-test-id="variables-create-collection"
            class="cursor-pointer rounded bg-hover px-3 py-1.5 text-xs text-surface hover:bg-border"
            @click="ctx.addCollection"
          >
            {{ dialogs.createCollection }}
          </button>
        </template>
      </AppPlaceholder>
    </div>

    <template v-else>
      <TabsRoot v-model="ctx.activeCollectionId.value" class="flex flex-1 flex-col overflow-hidden">
        <div class="flex shrink-0 items-center border-b border-border">
          <TabsList class="flex flex-1 gap-0.5 overflow-x-auto px-3 py-1">
            <template v-for="col in ctx.collections.value" :key="col.id">
              <input
                v-if="ctx.collectionRename.editingId.value === col.id"
                ref="collectionInput"
                class="w-24 rounded border border-accent bg-input px-2 py-0.5 text-xs text-surface outline-none"
                :value="col.name"
                @blur="ctx.collectionRename.commit(col.id, $event)"
                @keydown="ctx.collectionRename.onKeydown"
              />
              <TabsTrigger
                v-else
                :value="col.id"
                data-test-id="variables-collection-tab"
                class="cursor-pointer rounded border-none px-2.5 py-1 text-xs whitespace-nowrap text-muted data-[state=active]:bg-hover data-[state=active]:text-surface"
                @dblclick="ctx.startRenameCollection(col.id)"
              >
                {{ col.name }}
              </TabsTrigger>
            </template>
          </TabsList>

          <div class="flex items-center gap-1.5 px-3">
            <DropdownMenuRoot>
              <DropdownMenuTrigger as-child>
                <button
                  data-test-id="variables-collection-menu"
                  class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                >
                  <icon-lucide-ellipsis class="size-3.5" />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuPortal>
                <DropdownMenuContent
                  side="bottom"
                  :side-offset="4"
                  align="start"
                  :class="menuCls.content"
                >
                  <DropdownMenuItem
                    :class="menuCls.item"
                    @select="ctx.startRenameCollection(ctx.activeCollectionId.value)"
                  >
                    <icon-lucide-pencil :class="menuCls.icon" />
                    {{ dialogs.renameCollection }}
                  </DropdownMenuItem>
                  <DropdownMenuSeparator class="mx-1.5 my-1 h-px bg-border" />
                  <DropdownMenuItem
                    :class="menuCls.item"
                    class="text-red-500"
                    data-test-id="variables-delete-collection"
                    @select="ctx.removeCollection(ctx.activeCollectionId.value)"
                  >
                    <icon-lucide-trash-2 :class="menuCls.icon" />
                    {{ dialogs.deleteCollection }}
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenuPortal>
            </DropdownMenuRoot>
            <div class="flex items-center gap-1 rounded border border-border px-2 py-0.5">
              <icon-lucide-search class="size-3 text-muted" />
              <input
                v-model="ctx.searchTerm.value"
                data-test-id="variables-search-input"
                class="w-24 border-none bg-transparent text-xs text-surface outline-none placeholder:text-muted"
                :placeholder="dialogs.search"
              />
            </div>
            <Tip :label="dialogs.createCollection">
              <button
                data-test-id="variables-add-collection"
                class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                @click="ctx.addCollection"
              >
                <icon-lucide-folder-plus class="size-3.5" />
              </button>
            </Tip>
            <DialogClose
              :aria-label="dialogs.close"
              class="flex size-6 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
            >
              <icon-lucide-x class="size-4" />
            </DialogClose>
          </div>
        </div>

        <TabsContent
          v-for="col in ctx.collections.value"
          :key="col.id"
          :value="col.id"
          class="flex flex-1 flex-col overflow-hidden outline-none"
        >
          <div class="flex-1 overflow-auto">
            <table
              class="w-full min-w-full border-collapse"
              :style="{ width: `${ctx.table.getCenterTotalSize()}px` }"
            >
              <thead class="sticky top-0 z-10 bg-panel">
                <tr
                  v-for="headerGroup in ctx.table.getHeaderGroups()"
                  :key="headerGroup.id"
                  class="border-b border-border"
                >
                  <th
                    v-for="header in headerGroup.headers"
                    :key="header.id"
                    class="relative px-4 py-2 text-left text-[11px] font-medium text-muted"
                    :style="{ width: `${header.getSize()}px` }"
                  >
                    <template v-if="getModeId(header.column.id)">
                      <input
                        v-if="ctx.modeRename.editingId.value === getModeId(header.column.id)"
                        ref="modeInput"
                        class="-mx-1 w-full rounded border border-accent bg-input px-1 py-0 text-[11px] font-medium text-surface outline-none"
                        :value="header.column.columnDef.header"
                        @blur="ctx.modeRename.commit(modeId(header.column.id), $event)"
                        @keydown="ctx.modeRename.onKeydown"
                      />
                      <ContextMenuRoot v-else>
                        <ContextMenuTrigger as-child>
                          <span
                            :data-default="
                              getModeId(header.column.id) === col.defaultModeId || undefined
                            "
                            :class="
                              modeLabelClass(getModeId(header.column.id) === col.defaultModeId)
                            "
                            @dblclick="ctx.startRenameMode(modeId(header.column.id))"
                          >
                            {{ header.column.columnDef.header }}
                          </span>
                        </ContextMenuTrigger>
                        <ContextMenuPortal>
                          <ContextMenuContent :class="menuCls.content">
                            <ContextMenuItem
                              :class="menuCls.item"
                              @select="ctx.startRenameMode(modeId(header.column.id))"
                            >
                              <icon-lucide-pencil :class="menuCls.icon" />
                              {{ dialogs.renameMode }}
                            </ContextMenuItem>
                            <ContextMenuItem
                              :class="menuCls.item"
                              @select="ctx.duplicateMode(modeId(header.column.id))"
                            >
                              <icon-lucide-copy :class="menuCls.icon" />
                              {{ dialogs.duplicateMode }}
                            </ContextMenuItem>
                            <ContextMenuItem
                              v-if="getModeId(header.column.id) !== col.defaultModeId"
                              :class="menuCls.item"
                              @select="ctx.setDefaultMode(modeId(header.column.id))"
                            >
                              <icon-lucide-pin :class="menuCls.icon" />
                              {{ dialogs.setDefaultMode }}
                            </ContextMenuItem>
                            <ContextMenuSeparator :class="menuCls.separator" />
                            <ContextMenuItem
                              :class="[menuCls.item, 'text-red-500']"
                              :disabled="col.modes.length <= 1"
                              @select="ctx.removeMode(modeId(header.column.id))"
                            >
                              <icon-lucide-trash-2 :class="menuCls.icon" />
                              {{ dialogs.deleteMode }}
                            </ContextMenuItem>
                          </ContextMenuContent>
                        </ContextMenuPortal>
                      </ContextMenuRoot>
                    </template>
                    <FlexRender
                      v-else-if="!header.isPlaceholder"
                      :render="header.column.columnDef.header"
                      :props="header.getContext()"
                    />
                    <div
                      v-if="header.column.getCanResize()"
                      :data-resizing="header.column.getIsResizing() || undefined"
                      :class="resizeHandleClass(header.column.getIsResizing())"
                      @mousedown="header.getResizeHandler()?.($event)"
                      @touchstart="header.getResizeHandler()?.($event)"
                      @dblclick="header.column.resetSize()"
                    />
                  </th>
                  <th class="w-8 px-1 py-2">
                    <Tip :label="dialogs.addMode">
                      <button
                        data-test-id="variables-add-mode"
                        class="flex size-5 cursor-pointer items-center justify-center rounded border-none bg-transparent text-muted hover:bg-hover hover:text-surface"
                        @click="ctx.addMode"
                      >
                        <icon-lucide-plus class="size-3" />
                      </button>
                    </Tip>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="row in ctx.table.getRowModel().rows"
                  :key="row.id"
                  data-test-id="variable-row"
                  :class="tableStyles.row()"
                >
                  <td
                    v-for="cell in row.getVisibleCells()"
                    :key="cell.id"
                    class="px-4 py-1.5"
                    :style="{ width: `${cell.column.getSize()}px` }"
                  >
                    <FlexRender :render="cell.column.columnDef.cell" :props="cell.getContext()" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <div
            class="flex w-full shrink-0 items-center justify-between gap-2 border-t border-border px-4 py-2"
          >
            <span class="text-xs text-muted">{{ panels.createVariable }}</span>
            <DropdownMenuRoot>
              <DropdownMenuTrigger as-child>
                <button
                  data-test-id="variables-add-variable"
                  class="flex cursor-pointer items-center gap-1.5 rounded bg-hover px-2.5 py-1.5 text-xs text-surface hover:bg-border"
                >
                  <icon-lucide-plus class="size-3.5" />
                  {{ panels.add }}
                  <icon-lucide-chevron-down class="size-3" />
                </button>
              </DropdownMenuTrigger>
              <DropdownMenuPortal>
                <DropdownMenuContent
                  side="top"
                  :side-offset="8"
                  align="end"
                  :class="addVariableMenuCls.content"
                >
                  <DropdownMenuItem
                    v-for="item in variableTypes"
                    :key="item.type"
                    :class="menuCls.item"
                    v-test-id="variablesAddTestId(item.type)"
                    @select="ctx.addVariable(item.type)"
                  >
                    <component :is="variableTypeIcons[item.type]" :class="menuCls.icon" />
                    <span class="flex min-w-0 flex-1 flex-col">
                      <span>{{ item.label() }}</span>
                      <span class="truncate text-[10px] text-muted">{{ item.description() }}</span>
                    </span>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenuPortal>
            </DropdownMenuRoot>
          </div>
        </TabsContent>
      </TabsRoot>
    </template>
  </AppDialogRoot>
</template>
