// src/components/properties/LayoutSection/AutoLayoutControls.vue
<script setup lang="ts">
import { computed } from 'vue'

import { useI18n, useLayoutControlsContext } from '@openweave/vue'

import IconButton from '@/components/ui/IconButton.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'

import type { LayoutMode } from '@openweave/scene-graph'

const ctx = useLayoutControlsContext()
const { panels } = useI18n()

const layoutModes = computed<Array<{ value: LayoutMode; label: string }>>(() => [
  { value: 'NONE', label: panels.value.freeform },
  { value: 'VERTICAL', label: panels.value.layoutVertical },
  { value: 'HORIZONTAL', label: panels.value.layoutHorizontal },
  { value: 'GRID', label: panels.value.layoutGrid }
])

function setLayoutMode(mode: string) {
  ctx.editor.setLayoutMode(ctx.node.id, mode as LayoutMode)
}
</script>

<template>
  <div>
    <label class="mb-1 block text-[11px] text-muted">{{ panels.flow }}</label>
    <div class="flex items-center gap-1.5">
      <SegmentedControl
        :model-value="ctx.node.layoutMode"
        :options="layoutModes"
        :label="panels.flow"
        :ui="{ root: 'flex min-w-0 flex-1' }"
        @change="setLayoutMode"
      >
        <template #option="{ option }">
          <Tip :label="option.label" class="flex items-center justify-center">
            <icon-lucide-move v-if="option.value === 'NONE'" class="size-3.5" />
            <icon-lucide-rows-2 v-else-if="option.value === 'VERTICAL'" class="size-3.5" />
            <icon-lucide-columns-2 v-else-if="option.value === 'HORIZONTAL'" class="size-3.5" />
            <icon-lucide-layout-grid v-else class="size-3.5" />
          </Tip>
        </template>
      </SegmentedControl>

      <IconButton
        v-if="ctx.isFlex"
        :label="panels.layoutWrap"
        size="md"
        :active="ctx.node.layoutWrap === 'WRAP'"
        @click="ctx.updateProp('layoutWrap', ctx.node.layoutWrap === 'WRAP' ? 'NO_WRAP' : 'WRAP')"
      >
        <icon-lucide-wrap-text class="size-3.5" />
      </IconButton>
    </div>
  </div>
</template>

// src/components/properties/LayoutSection/AutoLayoutControls.tsx
import React from 'react'
import { tv } from 'tailwind-variants'
import { useI18n, useLayoutControlsContext } from '@openweave/react'
import type { LayoutMode } from '@openweave/scene-graph'
import { Columns2, LayoutGrid, Move, Rows2, WrapText } from 'lucide-react'

import IconButton from '@/components/ui/IconButton'
import Tip from '@/components/ui/Tip'
import segmentedControlTheme from '@/theme/segmented-control'

const segmentedControl = tv(segmentedControlTheme)

const LAYOUT_MODE_ICONS: Record<LayoutMode, React.ReactNode> = {
  NONE: <Move className="size-3.5" />,
  VERTICAL: <Rows2 className="size-3.5" />,
  HORIZONTAL: <Columns2 className="size-3.5" />,
  GRID: <LayoutGrid className="size-3.5" />
}

/**
 * Flow selector (Freeform/Vertical/Horizontal/Grid) shown for any container
 * node regardless of its current layout mode, plus the wrap toggle for flex
 * containers. Always visible for containers — this is what lets a freeform
 * frame switch directly into auto layout.
 *
 * Hand-rolled with plain buttons (reusing the shared segmented-control
 * theme for visuals) rather than the shared SegmentedControl primitive,
 * which renders role="radio" items — the auto-layout E2E suite exercises
 * these as role="button".
 */
export default function AutoLayoutControls() {
  const ctx = useLayoutControlsContext()
  const { panels } = useI18n()
  const { node, editor, isFlex } = ctx
  const styles = segmentedControl({ size: 'sm' })

  const layoutModes: { value: LayoutMode; label: string }[] = [
    { value: 'NONE', label: panels.freeform },
    { value: 'VERTICAL', label: panels.layoutVertical },
    { value: 'HORIZONTAL', label: panels.layoutHorizontal },
    { value: 'GRID', label: panels.layoutGrid }
  ]

  return (
    <div>
      <label className="mb-1 block text-[11px] text-muted">{panels.flow}</label>
      <div className="flex items-center gap-1.5">
        <div role="group" aria-label={panels.flow} className={`${styles.root()} min-w-0 flex-1`}>
          {layoutModes.map((mode) => (
            <Tip key={mode.value} label={mode.label}>
              <button
                type="button"
                aria-label={mode.label}
                data-state={node.layoutMode === mode.value ? 'on' : 'off'}
                className={styles.item()}
                onClick={() => editor.setLayoutMode(node.id, mode.value)}
              >
                {LAYOUT_MODE_ICONS[mode.value]}
              </button>
            </Tip>
          ))}
        </div>
        {isFlex && (
          <IconButton
            label={panels.layoutWrap}
            size="md"
            active={node.layoutWrap === 'WRAP'}
            onClick={() =>
              ctx.updateProp('layoutWrap', node.layoutWrap === 'WRAP' ? 'NO_WRAP' : 'WRAP')
            }
          >
            <WrapText className="size-3.5" />
          </IconButton>
        )}
      </div>
    </div>
  )
}
