// src/components/properties/LayoutSection/GridControls.vue
<script setup lang="ts">
import AppSelect from '@/components/ui/AppSelect.vue'
import NumberField from '@/components/inputs/NumberField.vue'
import IconButton from '@/components/ui/IconButton.vue'
import { useI18n, useLayoutControlsContext } from '@openweave/vue'

import type { GridTrackProp } from '@/components/properties/LayoutSection/types'
import type { GridTrackSizing } from '@openweave/scene-graph'

const ctx = useLayoutControlsContext()

const { panels } = useI18n()
const trackProps: GridTrackProp[] = ['gridTemplateColumns', 'gridTemplateRows']

function defaultTrackValue(sizing: GridTrackSizing): number {
  if (sizing === 'FR') return 1
  if (sizing === 'FIXED') return 100
  return 0
}
</script>

<template>
  <template v-for="trackProp in trackProps" :key="trackProp">
    <div class="mt-2">
      <div class="mb-1 flex items-center justify-between">
        <label class="text-[11px] text-muted">
          {{ trackProp === 'gridTemplateColumns' ? panels.columns : panels.rows }}
        </label>
        <IconButton @click="ctx.addTrack(trackProp)">
          <icon-lucide-plus class="size-3.5" />
        </IconButton>
      </div>
      <div class="flex flex-col gap-1">
        <div v-for="(track, i) in ctx.node[trackProp]" :key="i" class="flex items-center gap-1">
          <NumberField
            v-if="track.sizing !== 'AUTO'"
            class="flex-1"
            :icon="`${trackProp === 'gridTemplateColumns' ? 'C' : 'R'}${i + 1}`"
            :model-value="track.value"
            :min="track.sizing === 'FR' ? 1 : 0"
            :suffix="track.sizing === 'FR' ? 'fr' : 'px'"
            @update:model-value="ctx.updateGridTrack(trackProp, i, { value: $event })"
          />
          <span v-else class="flex-1 px-1 text-xs text-muted">{{ ctx.trackLabel(track) }}</span>
          <AppSelect
            :model-value="track.sizing"
            :options="ctx.trackSizingOptions"
            @update:model-value="
              ctx.updateGridTrack(trackProp, i, {
                sizing: $event as GridTrackSizing,
                value: defaultTrackValue($event as GridTrackSizing)
              })
            "
          />
          <IconButton v-if="ctx.node[trackProp].length > 1" @click="ctx.removeTrack(trackProp, i)">
            <icon-lucide-x class="size-3.5" />
          </IconButton>
        </div>
      </div>
    </div>
  </template>

  <div class="mt-2 grid grid-cols-2 gap-1.5">
    <NumberField
      :model-value="Math.round(ctx.node.gridColumnGap)"
      :min="0"
      @update:model-value="ctx.updateProp('gridColumnGap', $event)"
      @commit="(v: number, p: number) => ctx.commitProp('gridColumnGap', v, p)"
    >
      <template #icon>
        <icon-lucide-move-horizontal class="size-3" />
      </template>
    </NumberField>
    <NumberField
      :model-value="Math.round(ctx.node.gridRowGap)"
      :min="0"
      @update:model-value="ctx.updateProp('gridRowGap', $event)"
      @commit="(v: number, p: number) => ctx.commitProp('gridRowGap', v, p)"
    >
      <template #icon>
        <icon-lucide-move-vertical class="size-3" />
      </template>
    </NumberField>
  </div>
</template>

// src/components/properties/LayoutSection/GridControls.tsx
import { MoveHorizontal, MoveVertical, Plus, X } from 'lucide-react'
import React from 'react'

import { useI18n, useLayoutControlsContext } from '@openweave/react'
import type { GridTrackSizing } from '@openweave/scene-graph'

import NumberField from '@/components/inputs/NumberField'
import type { GridTrackProp } from '@/components/properties/LayoutSection/types'
import { AppSelect } from '@/components/ui/AppSelect'
import IconButton from '@/components/ui/IconButton'

const TRACK_PROPS: GridTrackProp[] = ['gridTemplateColumns', 'gridTemplateRows']

function defaultTrackValue(sizing: GridTrackSizing): number {
  if (sizing === 'FR') return 1
  if (sizing === 'FIXED') return 100
  return 0
}

/** Grid-mode controls: column/row track editor plus column/row gap. */
export default function GridControls() {
  const ctx = useLayoutControlsContext()
  const { panels } = useI18n()
  const { node } = ctx

  return (
    <>
      {TRACK_PROPS.map((trackProp) => (
        <div className="mt-2" key={trackProp}>
          <div className="mb-1 flex items-center justify-between">
            <label className="text-[11px] text-muted">
              {trackProp === 'gridTemplateColumns' ? panels.columns : panels.rows}
            </label>
            <IconButton onClick={() => ctx.addTrack(trackProp)}>
              <Plus className="size-3.5" />
            </IconButton>
          </div>
          <div className="flex flex-col gap-1">
            {node[trackProp].map((track, i) => (
              <div className="flex items-center gap-1" key={i}>
                {track.sizing !== 'AUTO' ? (
                  <NumberField
                    className="flex-1"
                    icon={`${trackProp === 'gridTemplateColumns' ? 'C' : 'R'}${i + 1}`}
                    value={track.value}
                    min={track.sizing === 'FR' ? 1 : 0}
                    suffix={track.sizing === 'FR' ? 'fr' : 'px'}
                    onChange={(v) => ctx.updateGridTrack(trackProp, i, { value: v })}
                  />
                ) : (
                  <span className="flex-1 px-1 text-xs text-muted">{ctx.trackLabel(track)}</span>
                )}
                <AppSelect
                  value={track.sizing}
                  options={ctx.trackSizingOptions}
                  onValueChange={(sizing) =>
                    ctx.updateGridTrack(trackProp, i, {
                      sizing: sizing as GridTrackSizing,
                      value: defaultTrackValue(sizing as GridTrackSizing)
                    })
                  }
                />
                {node[trackProp].length > 1 && (
                  <IconButton onClick={() => ctx.removeTrack(trackProp, i)}>
                    <X className="size-3.5" />
                  </IconButton>
                )}
              </div>
            ))}
          </div>
        </div>
      ))}

      <div className="mt-2 grid grid-cols-2 gap-1.5">
        <NumberField
          icon={<MoveHorizontal className="size-3" />}
          value={Math.round(node.gridColumnGap)}
          min={0}
          onChange={(v) => ctx.updateProp('gridColumnGap', v)}
          onCommit={(v, p) => ctx.commitProp('gridColumnGap', v, p)}
        />
        <NumberField
          icon={<MoveVertical className="size-3" />}
          value={Math.round(node.gridRowGap)}
          min={0}
          onChange={(v) => ctx.updateProp('gridRowGap', v)}
          onCommit={(v, p) => ctx.commitProp('gridRowGap', v, p)}
        />
      </div>
    </>
  )
}
