// src/components/properties/LayoutGridSection.tsx
import {
  Plus,
  Eye,
  EyeOff,
  Minus,
  Columns3,
  Rows3,
  LayoutGrid as LayoutGridIcon
} from 'lucide-react'
import React from 'react'

import { useEditor, useSelectionState, useI18n } from '@openweave/react'
import type { LayoutGrid } from '@openweave/scene-graph'

import NumberField from '@/components/inputs/NumberField'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField'
import IconButton from '@/components/ui/IconButton'
import PanelSection from '@/components/ui/panel/PanelSection'
import SegmentedControl from '@/components/ui/SegmentedControl'

export default function LayoutGridSection() {
  const editor = useEditor()
  const { selectedNode: node } = useSelectionState()
  const { panels } = useI18n()

  if (!node) return null

  const grids = ('layoutGrids' in node ? node.layoutGrids : undefined) ?? []

  const commit = (next: LayoutGrid[], label: string) => {
    editor.updateNodeWithUndo(node.id, { layoutGrids: next }, label)
  }

  const defaultGrid = (): LayoutGrid => ({
    visible: true,
    color: { r: 1, g: 0, b: 0, a: 0.1 },
    pattern: 'COLUMNS',
    alignment: 'STRETCH',
    count: 5,
    gutterSize: 20,
    offset: 0,
    sectionSize: 0
  })

  const add = () => {
    commit([...grids, defaultGrid()], 'Add layout guide')
  }

  const remove = (index: number) => {
    commit(
      grids.filter((_, i) => i !== index),
      'Remove layout guide'
    )
  }

  const patch = (index: number, changes: Partial<LayoutGrid>, label = 'Edit layout guide') => {
    commit(
      grids.map((grid, i) => (i === index ? { ...grid, ...changes } : grid)),
      label
    )
  }

  const gridPattern = (grid: LayoutGrid): 'COLUMNS' | 'ROWS' | 'GRID' => {
    if (grid.pattern) return grid.pattern
    return grid.axis === 'Y' ? 'ROWS' : 'COLUMNS'
  }

  const isGrid = (grid: LayoutGrid): boolean => {
    return gridPattern(grid) === 'GRID'
  }

  return (
    <PanelSection
      label={panels.layoutGrids}
      actions={
        <IconButton label={panels.addLayoutGrid} onClick={add}>
          <Plus className="size-3.5" />
        </IconButton>
      }
    >
      <div className="space-y-3">
        <SharedStyleField kind="grid" label={panels.gridStyle} />
        {grids.map((grid, index) => (
          <div
            key={index}
            className="flex gap-2 relative group items-start border-b border-border/50 pb-3 last:border-0 last:pb-0"
          >
            <div className="flex-1 space-y-2">
              <SegmentedControl
                value={gridPattern(grid)}
                onChange={(val) => patch(index, { pattern: val as any }, 'Change grid pattern')}
                options={[
                  {
                    value: 'COLUMNS',
                    label: panels.gridColumns,
                    icon: <Columns3 className="size-3.5" />
                  },
                  { value: 'ROWS', label: panels.gridRows, icon: <Rows3 className="size-3.5" /> },
                  {
                    value: 'GRID',
                    label: panels.gridGrid,
                    icon: <LayoutGridIcon className="size-3.5" />
                  }
                ]}
              />

              <div className="grid grid-cols-2 gap-2">
                <div className="flex flex-col gap-1">
                  <span className="text-[10px] text-muted">{panels.gridCount}</span>
                  <div className="bg-input/50 rounded px-1.5 py-1 border border-border focus-within:border-accent transition-colors">
                    <NumberField
                      value={grid.count ?? grid.numSections ?? 1}
                      min={1}
                      onChange={(v) => patch(index, { count: v })}
                    />
                  </div>
                </div>

                {!isGrid(grid) && (
                  <div className="flex flex-col gap-1">
                    <span className="text-[10px] text-muted">{panels.gridGutter}</span>
                    <div className="bg-input/50 rounded px-1.5 py-1 border border-border focus-within:border-accent transition-colors">
                      <NumberField
                        value={grid.gutterSize ?? 0}
                        min={0}
                        onChange={(v) => patch(index, { gutterSize: v })}
                      />
                    </div>
                  </div>
                )}

                {isGrid(grid) && (
                  <div className="flex flex-col gap-1">
                    <span className="text-[10px] text-muted">{panels.gridSectionSize}</span>
                    <div className="bg-input/50 rounded px-1.5 py-1 border border-border focus-within:border-accent transition-colors">
                      <NumberField
                        value={grid.sectionSize ?? 0}
                        min={1}
                        onChange={(v) => patch(index, { sectionSize: v })}
                      />
                    </div>
                  </div>
                )}

                <div className="flex flex-col gap-1">
                  <span className="text-[10px] text-muted">{panels.gridMargin}</span>
                  <div className="bg-input/50 rounded px-1.5 py-1 border border-border focus-within:border-accent transition-colors">
                    <NumberField
                      value={grid.offset ?? 0}
                      onChange={(v) => patch(index, { offset: v })}
                    />
                  </div>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-0.5 pt-1">
              <IconButton
                label={panels.toggleVisibility}
                onClick={() =>
                  patch(index, { visible: grid.visible === false }, 'Toggle layout guide')
                }
                className={grid.visible === false ? 'opacity-50' : ''}
              >
                {grid.visible !== false ? (
                  <Eye className="size-3.5" />
                ) : (
                  <EyeOff className="size-3.5" />
                )}
              </IconButton>
              <IconButton label={panels.removeLayoutGrid} onClick={() => remove(index)}>
                <Minus className="size-3.5" />
              </IconButton>
            </div>
          </div>
        ))}
      </div>
    </PanelSection>
  )
}

// src/components/properties/LayoutSection/LayoutGridSection.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useEditor, useI18n, useSceneComputed } from '@openweave/vue'

import NumberField from '@/components/inputs/NumberField.vue'
import IconButton from '@/components/ui/IconButton.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import Tip from '@/components/ui/Tip.vue'
import PanelFieldGroup from '@/components/ui/panel/PanelFieldGroup.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'
import PanelItemRow from '@/components/ui/panel/PanelItemRow.vue'
import PanelSection from '@/components/ui/panel/PanelSection.vue'
import SharedStyleField from '@/components/properties/shared-style/SharedStyleField.vue'

import type { LayoutGrid } from '@openweave/scene-graph'

const editor = useEditor()
const { panels } = useI18n()

const selectedNode = useSceneComputed(() => editor.getSelectedNode() ?? null)
const grids = computed<LayoutGrid[]>(() => selectedNode.value?.layoutGrids ?? [])

const patternOptions = computed(() => [
  { value: 'COLUMNS' as const, label: panels.value.gridColumns },
  { value: 'ROWS' as const, label: panels.value.gridRows },
  { value: 'GRID' as const, label: panels.value.gridGrid }
])

function defaultGrid(): LayoutGrid {
  return {
    visible: true,
    color: { r: 1, g: 0, b: 0, a: 0.1 },
    pattern: 'COLUMNS',
    alignment: 'STRETCH',
    count: 5,
    gutterSize: 20,
    offset: 0,
    sectionSize: 0
  }
}

function commit(next: LayoutGrid[], label: string) {
  const node = selectedNode.value
  if (!node) return
  editor.updateNodeWithUndo(node.id, { layoutGrids: next }, label)
}

function add() {
  commit([...grids.value, defaultGrid()], 'Add layout guide')
}

function remove(index: number) {
  commit(
    grids.value.filter((_, i) => i !== index),
    'Remove layout guide'
  )
}

function patch(index: number, changes: Partial<LayoutGrid>, label = 'Edit layout guide') {
  commit(
    grids.value.map((grid, i) => (i === index ? { ...grid, ...changes } : grid)),
    label
  )
}

function gridPattern(grid: LayoutGrid): 'COLUMNS' | 'ROWS' | 'GRID' {
  if (grid.pattern) return grid.pattern
  return grid.axis === 'Y' ? 'ROWS' : 'COLUMNS'
}

function isGrid(grid: LayoutGrid): boolean {
  return gridPattern(grid) === 'GRID'
}
</script>

<template>
  <PanelSection :label="panels.layoutGrids" :empty="grids.length === 0">
    <SharedStyleField kind="grid" :label="panels.gridStyle" />
    <template #actions>
      <IconButton :label="panels.addLayoutGrid" @click="add">
        <icon-lucide-plus class="size-3.5" />
      </IconButton>
    </template>

    <PanelItemRow v-for="(grid, index) in grids" :key="index" class="items-start">
      <div class="flex min-w-0 flex-1 flex-col gap-1.5">
        <SegmentedControl
          :model-value="gridPattern(grid)"
          :options="patternOptions"
          :label="panels.layoutGrids"
          @change="
            patch(index, { pattern: $event as LayoutGrid['pattern'] }, 'Change grid pattern')
          "
        >
          <template #option="{ option }">
            <Tip :label="option.label" class="flex items-center justify-center">
              <icon-lucide-columns-3 v-if="option.value === 'COLUMNS'" class="size-3.5" />
              <icon-lucide-rows-3 v-else-if="option.value === 'ROWS'" class="size-3.5" />
              <icon-lucide-layout-grid v-else class="size-3.5" />
            </Tip>
          </template>
        </SegmentedControl>
        <PanelGrid :columns="2">
          <PanelFieldGroup :label="panels.gridCount">
            <NumberField
              :model-value="grid.count ?? grid.numSections ?? 1"
              :min="1"
              :aria-label="panels.gridCount"
              @update:model-value="patch(index, { count: $event })"
            />
          </PanelFieldGroup>
          <PanelFieldGroup v-if="!isGrid(grid)" :label="panels.gridGutter">
            <NumberField
              :model-value="grid.gutterSize ?? 0"
              :min="0"
              :aria-label="panels.gridGutter"
              @update:model-value="patch(index, { gutterSize: $event })"
            />
          </PanelFieldGroup>
          <PanelFieldGroup v-if="isGrid(grid)" :label="panels.gridSectionSize">
            <NumberField
              :model-value="grid.sectionSize ?? 0"
              :min="1"
              :aria-label="panels.gridSectionSize"
              @update:model-value="patch(index, { sectionSize: $event })"
            />
          </PanelFieldGroup>
          <PanelFieldGroup :label="panels.gridMargin">
            <NumberField
              :model-value="grid.offset ?? 0"
              :aria-label="panels.gridMargin"
              @update:model-value="patch(index, { offset: $event })"
            />
          </PanelFieldGroup>
        </PanelGrid>
      </div>
      <template #rail>
        <IconButton
          :label="panels.toggleVisibility"
          :active="grid.visible === false"
          @click="patch(index, { visible: grid.visible === false }, 'Toggle layout guide')"
        >
          <icon-lucide-eye-off v-if="grid.visible === false" class="size-3.5" />
          <icon-lucide-eye v-else class="size-3.5" />
        </IconButton>
        <IconButton :label="panels.removeLayoutGrid" @click="remove(index)">
          <icon-lucide-minus class="size-3.5" />
        </IconButton>
      </template>
    </PanelItemRow>
  </PanelSection>
</template>
