// src/components/properties/LayoutSection/PaddingControls.tsx
import {
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelTop,
  SeparatorHorizontal,
  SeparatorVertical
} from 'lucide-react'
import React from 'react'

import { useLayoutControlsContext } from '@openweave/react'

import type { PaddingProp } from '@/components/properties/LayoutSection/types'
import VariableNumberField from '@/components/properties/LayoutSection/VariableNumberField'
import PanelGrid from '@/components/ui/panel/PanelGrid'

const PADDING_SIDES: { prop: PaddingProp; icon: React.ReactNode }[] = [
  { prop: 'paddingTop', icon: <PanelTop className="size-3.5" /> },
  { prop: 'paddingRight', icon: <PanelRight className="size-3.5" /> },
  { prop: 'paddingBottom', icon: <PanelBottom className="size-3.5" /> },
  { prop: 'paddingLeft', icon: <PanelLeft className="size-3.5" /> }
]

/**
 * Padding editor: a combined horizontal/vertical pair while padding is
 * symmetric and not expanded, or four independent side fields once expanded
 * (via the flex gap row's toggle button) or for grid containers.
 */
export default function PaddingControls() {
  const ctx = useLayoutControlsContext()
  const { node } = ctx

  if (!ctx.showIndividualPadding && ctx.hasSymmetricPadding) {
    return (
      <PanelGrid columns={2} className="mt-1.5">
        <VariableNumberField
          dataTestId="layout-horizontal-padding-input"
          value={Math.round(node.paddingLeft)}
          min={0}
          nodeId={node.id}
          bindingPath="paddingLeft"
          icon={<SeparatorVertical className="size-3.5" />}
          onChange={ctx.setHorizontalPadding}
          onCommit={ctx.commitHorizontalPadding}
        />
        <VariableNumberField
          dataTestId="layout-vertical-padding-input"
          value={Math.round(node.paddingTop)}
          min={0}
          nodeId={node.id}
          bindingPath="paddingTop"
          icon={<SeparatorHorizontal className="size-3.5" />}
          onChange={ctx.setVerticalPadding}
          onCommit={ctx.commitVerticalPadding}
        />
      </PanelGrid>
    )
  }

  if (ctx.isGrid || ctx.isFlex) {
    return (
      <PanelGrid columns={2} className="mt-1.5">
        {PADDING_SIDES.map((side) => (
          <VariableNumberField
            key={side.prop}
            value={Math.round(node[side.prop])}
            min={0}
            nodeId={node.id}
            bindingPath={side.prop}
            icon={side.icon}
            onChange={(v) => ctx.updateProp(side.prop, v)}
            onCommit={(v, p) => ctx.commitProp(side.prop, v, p)}
          />
        ))}
      </PanelGrid>
    )
  }

  return null
}

// src/components/properties/LayoutSection/PaddingControls.vue
<script setup lang="ts">
import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import { useLayoutControlsContext } from '@openweave/vue'

import type { PaddingProp } from '@/components/properties/LayoutSection/types'

const ctx = useLayoutControlsContext()

const paddingSides: Array<{ prop: PaddingProp; icon: string }> = [
  { prop: 'paddingTop', icon: 'top' },
  { prop: 'paddingRight', icon: 'right' },
  { prop: 'paddingBottom', icon: 'bottom' },
  { prop: 'paddingLeft', icon: 'left' }
]
</script>

<template>
  <div
    v-if="!ctx.showIndividualPadding && ctx.hasSymmetricPadding"
    class="mt-1.5 grid grid-cols-2 gap-1.5"
  >
    <VariableNumberField
      data-test-id="layout-horizontal-padding-input"
      :model-value="Math.round(ctx.node.paddingLeft)"
      :min="0"
      :node-id="ctx.node.id"
      binding-path="paddingLeft"
      @update:model-value="ctx.setHorizontalPadding"
      @commit="ctx.commitHorizontalPadding"
    >
      <template #icon>
        <icon-lucide-separator-vertical class="size-3.5" />
      </template>
    </VariableNumberField>
    <VariableNumberField
      data-test-id="layout-vertical-padding-input"
      :model-value="Math.round(ctx.node.paddingTop)"
      :min="0"
      :node-id="ctx.node.id"
      binding-path="paddingTop"
      @update:model-value="ctx.setVerticalPadding"
      @commit="ctx.commitVerticalPadding"
    >
      <template #icon>
        <icon-lucide-separator-horizontal class="size-3.5" />
      </template>
    </VariableNumberField>
  </div>

  <div v-else-if="ctx.isGrid || ctx.isFlex" class="mt-1.5 grid grid-cols-2 gap-1.5">
    <VariableNumberField
      v-for="side in paddingSides"
      :key="side.prop"
      :model-value="Math.round(ctx.node[side.prop])"
      :min="0"
      :node-id="ctx.node.id"
      :binding-path="side.prop"
      @update:model-value="ctx.updateProp(side.prop, $event)"
      @commit="(v: number, p: number) => ctx.commitProp(side.prop, v, p)"
    >
      <template #icon>
        <icon-lucide-panel-top v-if="side.icon === 'top'" class="size-3.5" />
        <icon-lucide-panel-right v-else-if="side.icon === 'right'" class="size-3.5" />
        <icon-lucide-panel-bottom v-else-if="side.icon === 'bottom'" class="size-3.5" />
        <icon-lucide-panel-left v-else class="size-3.5" />
      </template>
    </VariableNumberField>
  </div>
</template>
