// src/components/properties/LayoutSection/size/SizeControls.tsx
import React from 'react'

import { useI18n, useLayoutControlsContext } from '@openweave/react'

import SizeAxisField from '@/components/properties/LayoutSection/size/SizeAxisField'
import SizeLimitField from '@/components/properties/LayoutSection/size/SizeLimitField'
import type { SizeLimitItem } from '@/components/properties/LayoutSection/size/types'
import PanelGrid from '@/components/ui/panel/PanelGrid'

/**
 * W/H fields plus any active size limits (min/max W/H). Rendered for every
 * selected node, not just containers — matches the old Vue SizeControls,
 * which applied to leaf shapes too.
 */
export default function SizeControls() {
  const ctx = useLayoutControlsContext()
  const { panels } = useI18n()
  const { node } = ctx

  const sizeLimits: SizeLimitItem[] = [
    {
      prop: 'minWidth',
      icon: panels.minWidthShort,
      label: panels.minWidthShort,
      setLabel: panels.setToCurrentWidth,
      removeLabel: panels.removeMinWidth
    },
    {
      prop: 'maxWidth',
      icon: panels.maxWidthShort,
      label: panels.maxWidthShort,
      setLabel: panels.setToCurrentWidth,
      removeLabel: panels.removeMaxWidth
    },
    {
      prop: 'minHeight',
      icon: panels.minHeightShort,
      label: panels.minHeightShort,
      setLabel: panels.setToCurrentHeight,
      removeLabel: panels.removeMinHeight
    },
    {
      prop: 'maxHeight',
      icon: panels.maxHeightShort,
      label: panels.maxHeightShort,
      setLabel: panels.setToCurrentHeight,
      removeLabel: panels.removeMaxHeight
    }
  ]

  const visibleSizeLimits = sizeLimits.filter((item) => node[item.prop] != null)

  return (
    <>
      <PanelGrid columns={2}>
        <SizeAxisField axis="width" icon="W" label={panels.width} />
        <SizeAxisField axis="height" icon="H" label={panels.height} />
      </PanelGrid>

      {visibleSizeLimits.length > 0 && (
        <PanelGrid columns={2} className="mt-1.5">
          {visibleSizeLimits.map((item) => (
            <SizeLimitField key={item.prop} item={item} />
          ))}
        </PanelGrid>
      )}
    </>
  )
}

// src/components/properties/LayoutSection/size/SizeControls.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n, useLayoutControlsContext } from '@openweave/vue'

import SizeAxisField from '@/components/properties/LayoutSection/size/SizeAxisField.vue'
import SizeLimitField from '@/components/properties/LayoutSection/size/SizeLimitField.vue'
import PanelGrid from '@/components/ui/panel/PanelGrid.vue'

import type { SizeLimitItem } from '@/components/properties/LayoutSection/size/types'

const ctx = useLayoutControlsContext()
const { panels } = useI18n()

const sizeLimits = computed<SizeLimitItem[]>(() => [
  {
    prop: 'minWidth',
    icon: panels.value.minWidthShort,
    label: panels.value.minWidthShort,
    setLabel: panels.value.setToCurrentWidth,
    removeLabel: panels.value.removeMinWidth
  },
  {
    prop: 'maxWidth',
    icon: panels.value.maxWidthShort,
    label: panels.value.maxWidthShort,
    setLabel: panels.value.setToCurrentWidth,
    removeLabel: panels.value.removeMaxWidth
  },
  {
    prop: 'minHeight',
    icon: panels.value.minHeightShort,
    label: panels.value.minHeightShort,
    setLabel: panels.value.setToCurrentHeight,
    removeLabel: panels.value.removeMinHeight
  },
  {
    prop: 'maxHeight',
    icon: panels.value.maxHeightShort,
    label: panels.value.maxHeightShort,
    setLabel: panels.value.setToCurrentHeight,
    removeLabel: panels.value.removeMaxHeight
  }
])

const visibleSizeLimits = computed(() =>
  sizeLimits.value.filter((item) => ctx.node[item.prop] != null)
)
</script>

<template>
  <PanelGrid :columns="2">
    <SizeAxisField axis="width" icon="W" :label="panels.width" />
    <SizeAxisField axis="height" icon="H" :label="panels.height" />
  </PanelGrid>

  <PanelGrid v-if="visibleSizeLimits.length" :columns="2" class="mt-1.5">
    <SizeLimitField v-for="item in visibleSizeLimits" :key="item.prop" :item="item" />
  </PanelGrid>
</template>
