// src/components/properties/LayoutSection/size/SizeLimitField.tsx
import React from 'react'

import { useLayoutControlsContext } from '@openweave/react'

import FieldSelectMenu from '@/components/properties/LayoutSection/FieldSelectMenu'
import type { SizeLimitFieldProps } from '@/components/properties/LayoutSection/size/types'
import VariableNumberField from '@/components/properties/LayoutSection/VariableNumberField'
import Tip from '@/components/ui/Tip'

/** A single size-limit field (min/max W/H): value plus "set to current" / "remove" menu. */
export default function SizeLimitField({ item }: SizeLimitFieldProps) {
  const ctx = useLayoutControlsContext()
  const { node } = ctx

  function handleSelect(value: string) {
    if (value === 'CURRENT') ctx.setSizeLimitToCurrent(item.prop)
    else if (value === 'REMOVE') ctx.removeSizeLimit(item.prop)
  }

  return (
    <Tip label={item.label}>
      <VariableNumberField
        icon={item.icon}
        ariaLabel={item.label}
        value={Math.round(node[item.prop] ?? 0)}
        min={0}
        nodeId={node.id}
        bindingPath={item.prop}
        onChange={(v) => ctx.updateSizeLimit(item.prop, v)}
        onCommit={(v, p) => ctx.commitSizeLimit(item.prop, v, p)}
        trailing={
          <FieldSelectMenu
            ariaLabel={item.label}
            value="VALUE"
            onValueChange={handleSelect}
            options={[
              { value: 'CURRENT', label: item.setLabel },
              { value: 'REMOVE', label: item.removeLabel }
            ]}
          />
        }
      />
    </Tip>
  )
}

// src/components/properties/LayoutSection/size/SizeLimitField.vue
<script setup lang="ts">
import {
  SelectContent,
  SelectItem,
  SelectItemText,
  SelectPortal,
  SelectRoot,
  SelectTrigger,
  SelectViewport
} from 'reka-ui'
import { useLayoutControlsContext } from '@openweave/vue'

import VariableNumberField from '@/components/properties/VariableNumberField.vue'
import { useSelectUI } from '@/components/ui/select'
import Tip from '@/components/ui/Tip.vue'

import type { SizeLimitFieldProps } from '@/components/properties/LayoutSection/size/types'

const { item } = defineProps<SizeLimitFieldProps>()

const ctx = useLayoutControlsContext()
const selectUI = useSelectUI({ item: 'rounded py-1.5 px-2 text-xs' })

function handleSelect(value: string) {
  if (value === 'CURRENT') ctx.setSizeLimitToCurrent(item.prop)
  else if (value === 'REMOVE') ctx.removeSizeLimit(item.prop)
}
</script>

<template>
  <Tip :label="item.label">
    <VariableNumberField
      :icon="item.icon"
      :aria-label="item.label"
      :model-value="Math.round(ctx.node[item.prop] ?? 0)"
      :min="0"
      :node-id="ctx.node.id"
      :binding-path="item.prop"
      @update:model-value="ctx.updateSizeLimit(item.prop, $event)"
      @commit="(value: number, previous: number) => ctx.commitSizeLimit(item.prop, value, previous)"
    >
      <template #after-variable>
        <SelectRoot :model-value="'VALUE'" @update:model-value="handleSelect($event as string)">
          <SelectTrigger
            data-slot="limit-trigger"
            :aria-label="item.label"
            class="flex shrink-0 cursor-pointer items-center self-stretch border-none bg-transparent px-1 text-muted outline-none data-[state=open]:text-foreground"
            @pointerdown.stop
          >
            <icon-lucide-chevron-down class="size-3" />
          </SelectTrigger>
          <SelectPortal>
            <SelectContent
              position="popper"
              align="start"
              :side-offset="4"
              :class="selectUI.content"
            >
              <SelectViewport class="p-0.5">
                <SelectItem value="CURRENT" :class="selectUI.item">
                  <SelectItemText>{{ item.setLabel }}</SelectItemText>
                </SelectItem>
                <SelectItem value="REMOVE" :class="selectUI.item">
                  <SelectItemText>{{ item.removeLabel }}</SelectItemText>
                </SelectItem>
              </SelectViewport>
            </SelectContent>
          </SelectPortal>
        </SelectRoot>
      </template>
    </VariableNumberField>
  </Tip>
</template>
