// src/components/LayersPanel.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { SplitterGroup, SplitterPanel, SplitterResizeHandle } from 'reka-ui'

import { useI18n } from '@openweave/vue'

import AppMenu from '@/components/Shell/AppMenu.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import AssetsPanel from './assets-panel/AssetsPanel.vue'
import LayerTree from './LayerTree/LayerTree.vue'
import PagesPanel from './PagesPanel.vue'

const { menu, panels } = useI18n()
const activePanel = ref<'file' | 'assets'>('file')
const panelModel = computed({
  get: () => activePanel.value,
  set: (value: string) => {
    if (value === 'file' || value === 'assets') activePanel.value = value
  }
})
const panelOptions = computed(() => [
  { value: 'file', label: menu.value.file },
  { value: 'assets', label: panels.value.assets }
])
const panelTabsUI = { root: 'w-full' }
</script>

<template>
  <aside
    data-test-id="layers-panel"
    class="flex min-w-0 flex-1 flex-col overflow-hidden border-r border-border bg-panel"
    style="contain: paint layout style"
  >
    <AppMenu />
    <div class="shrink-0 border-b border-border px-2 py-1.5">
      <SegmentedControl
        v-model="panelModel"
        :options="panelOptions"
        :label="panels.layers"
        :ui="panelTabsUI"
      >
        <template #option="{ option }">
          <span
            :data-test-id="
              option.value === 'file' ? 'left-panel-layers-tab' : 'left-panel-assets-tab'
            "
            class="truncate"
          >
            {{ option.label }}
          </span>
        </template>
      </SegmentedControl>
    </div>
    <AssetsPanel v-if="activePanel === 'assets'" />
    <SplitterGroup
      v-else
      direction="vertical"
      auto-save-id="layers-layout"
      class="flex-1 overflow-hidden"
    >
      <SplitterPanel
        :default-size="30"
        :min-size="10"
        :max-size="60"
        class="flex flex-col overflow-hidden"
      >
        <PagesPanel />
      </SplitterPanel>
      <SplitterResizeHandle class="group relative z-10 -my-1 h-2 cursor-row-resize">
        <div
          class="pointer-events-none absolute inset-x-0 top-1/2 h-px -translate-y-1/2 bg-border"
        />
      </SplitterResizeHandle>
      <SplitterPanel :default-size="70" :min-size="20" class="flex flex-col overflow-hidden">
        <header
          data-test-id="layers-header"
          class="shrink-0 px-3 py-2 text-[11px] font-semibold text-surface"
        >
          {{ panels.layers }}
        </header>
        <LayerTree data-test-id="layers-tree" />
      </SplitterPanel>
    </SplitterGroup>
  </aside>
</template>

// src/components/LayersPanel.tsx
import React, { useState } from 'react'
import { Panel, Group, Separator } from 'react-resizable-panels'
import AppMenu from '@/components/shell/AppMenu'
import PagesPanel from '@/components/PagesPanel'
import LayerTree from '@/components/layer-tree/layer-tree'
import AssetsPanel from '@/components/assets/AssetsPanel'
import VariablesButton from '@/components/variables/VariablesButton'
import { useI18n } from '@openweave/react'

export default function LayersPanel() {
  const { menu, panels } = useI18n()
  const [activeTab, setActiveTab] = useState<'file' | 'assets'>('file')

  return (
    <aside
      data-test-id="layers-panel"
      className="flex min-w-0 flex-1 flex-col overflow-hidden border-r border-border bg-panel h-full"
      style={{ contain: 'paint layout style' }}
    >
      <AppMenu />
      <div className="shrink-0 border-b border-border px-2 py-1.5 flex gap-1">
        <button
          type="button"
          data-test-id="left-panel-layers-tab"
          className={`flex-1 rounded py-1 text-center text-xs transition-colors ${
            activeTab === 'file'
              ? 'bg-hover font-semibold text-surface'
              : 'text-muted hover:bg-hover/50 hover:text-surface'
          }`}
          onClick={() => setActiveTab('file')}
        >
          {menu.file}
        </button>
        <button
          type="button"
          data-test-id="left-panel-assets-tab"
          className={`flex-1 rounded py-1 text-center text-xs transition-colors ${
            activeTab === 'assets'
              ? 'bg-hover font-semibold text-surface'
              : 'text-muted hover:bg-hover/50 hover:text-surface'
          }`}
          onClick={() => setActiveTab('assets')}
        >
          {panels.assets}
        </button>
      </div>

      {activeTab === 'assets' ? (
        <AssetsPanel />
      ) : (
        <Group orientation="vertical" className="flex-1 overflow-hidden">
          <Panel defaultSize={30} minSize={10} maxSize={60} className="flex flex-col overflow-hidden">
            <PagesPanel />
          </Panel>

          <Separator className="h-px w-full bg-border hover:h-1 transition-all" />

          <Panel defaultSize={70} minSize={20} className="flex flex-col overflow-hidden">
            <header
              data-test-id="layers-header"
              className="flex shrink-0 items-center justify-between px-3 py-2 text-[11px] font-semibold text-surface"
            >
              {panels.layers}
              <VariablesButton />
            </header>
            <LayerTree />
          </Panel>
        </Group>
      )}
    </aside>
  )
}
