// src/components/pages-panel/PagesPanel.tsx
import * as ContextMenu from '@radix-ui/react-context-menu'
import {
  File as IconLucideFile,
  Pencil as IconLucidePencil,
  Trash2 as IconLucideTrash2
} from 'lucide-react'
import React, { useRef, useCallback, useEffect } from 'react'
import { tv } from 'tailwind-variants'

import { PageListRoot, useFlatReorderDrag, useI18n, useInlineRename } from '@openweave/react'

import Tip from '@/components/ui/Tip'
import pageListTheme from '@/theme/page-list'

interface PageItem {
  id: string
  name: string
  childIds: string[]
}

const pageListStyles = tv(pageListTheme)
const baseStyles = pageListStyles()

export default function PagesPanel() {
  const { panels, pages: pageMessages } = useI18n()
  const pageInputRef = useRef<HTMLInputElement>(null)

  const currentPagesRef = useRef<readonly PageItem[]>([])
  const currentMovePageRef = useRef<((id: string, index: number) => void) | null>(null)

  const getPages = useCallback(() => currentPagesRef.current, [])
  const handleMove = useCallback((id: string, index: number) => {
    currentMovePageRef.current?.(id, index)
  }, [])

  const pageReorder = useFlatReorderDrag<PageItem>({
    items: getPages,
    onMove: handleMove
  })

  // Inline `ref={(el) => pageReorder.setupItem(el, ...)}` creates a new
  // function every render, so React detaches+reattaches the drag
  // registration (and its `draggable` attribute) on every re-render, not
  // just mount/unmount. Cache one stable ref-callback per page id instead.
  const rowRefsRef = useRef<Map<string, (el: HTMLElement | null) => void>>(new Map())
  const getRowRef = useCallback(
    (id: string) => {
      let ref = rowRefsRef.current.get(id)
      if (!ref) {
        ref = (el) => pageReorder.setupItem(el, () => ({ id }))
        rowRefsRef.current.set(id, ref)
      }
      return ref
    },
    [pageReorder]
  )

  const handleRenameCommit = useCallback((_id: string, _name: string) => {
    // Handled in input onBlur/onKeyDown via actions.rename
  }, [])

  const rename = useInlineRename(handleRenameCommit)

  useEffect(() => {
    if (rename.editingId && pageInputRef.current) {
      rename.focusInput(pageInputRef.current)
    }
  }, [rename])

  function pageDropPosition(pg: PageItem): 'before' | 'after' | undefined {
    if (pageReorder.instructionTargetId !== pg.id) return undefined
    if (pageReorder.instruction?.operation === 'reorder-before') return 'before'
    if (pageReorder.instruction?.operation === 'reorder-after') return 'after'
    return undefined
  }

  function getPageStyles(pg: PageItem, currentPageId: string) {
    return pageListStyles({
      active: pg.id === currentPageId,
      dragging: pageReorder.draggingId === pg.id,
      dropPosition: pageDropPosition(pg)
    })
  }

  return (
    <PageListRoot>
      {({ pages, currentPageId, isDivider, actions }) => {
        currentPagesRef.current = pages
        currentMovePageRef.current = actions.move

        return (
          <div data-test-id="pages-panel" className={baseStyles.panel()}>
            <div className={baseStyles.header()}>
              <span data-test-id="pages-header" className={baseStyles.title()}>
                {panels.pages}
              </span>
              <Tip label={panels.addPage}>
                <button data-test-id="pages-add" className={baseStyles.add()} onClick={actions.add}>
                  +
                </button>
              </Tip>
            </div>
            <div className={baseStyles.body()}>
              <div data-test-id="pages-scroll" className={baseStyles.viewport()}>
                {pages.map((pg) => {
                  const styles = getPageStyles(pg, currentPageId)
                  const isEditing = rename.editingId === pg.id
                  const dropPos = pageDropPosition(pg)

                  return (
                    <ContextMenu.Root key={pg.id} modal={false}>
                      <ContextMenu.Trigger asChild>
                        <div
                          data-test-id="pages-row"
                          ref={getRowRef(pg.id)}
                          className={styles.row()}
                          data-page-id={pg.id}
                          data-active={pg.id === currentPageId || undefined}
                          data-dragging={pageReorder.draggingId === pg.id || undefined}
                          data-drop-position={dropPos}
                        >
                          {dropPos === 'before' && (
                            <div
                              data-test-id="pages-drop-indicator"
                              className={styles.dropIndicator()}
                            />
                          )}

                          {isEditing ? (
                            <div className={styles.renameRow()}>
                              <IconLucideFile className={styles.icon()} />
                              <input
                                ref={pageInputRef}
                                data-test-id="pages-item-input"
                                className={styles.renameInput()}
                                defaultValue={pg.name}
                                onBlur={(e) => {
                                  actions.rename(pg.id, e.target.value.trim() || pg.name)
                                  rename.commit(pg.id, e)
                                }}
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter') {
                                    actions.rename(pg.id, e.currentTarget.value.trim() || pg.name)
                                    rename.commit(pg.id, e)
                                  } else if (e.key === 'Escape') {
                                    rename.cancel()
                                  }
                                }}
                              />
                            </div>
                          ) : isDivider(pg) ? (
                            <div
                              data-test-id="pages-divider"
                              className={styles.divider()}
                              onDoubleClick={() => rename.start(pg.id, pg.name)}
                            >
                              <div className={styles.dividerLine()} />
                            </div>
                          ) : (
                            <button
                              data-test-id="pages-item"
                              className={styles.item()}
                              onClick={() => actions.switch(pg.id)}
                              onDoubleClick={() => rename.start(pg.id, pg.name)}
                            >
                              <IconLucideFile className={styles.icon()} />
                              <span className={styles.label()}>{pg.name}</span>
                            </button>
                          )}

                          {dropPos === 'after' && (
                            <div
                              data-test-id="pages-drop-indicator"
                              className={styles.dropIndicator()}
                            />
                          )}
                        </div>
                      </ContextMenu.Trigger>

                      <ContextMenu.Portal>
                        <ContextMenu.Content className="z-50 min-w-36 rounded-md bg-panel p-1 shadow-lg border border-border">
                          <ContextMenu.Item
                            data-test-id="pages-context-rename"
                            className="flex cursor-pointer items-center gap-2 rounded px-2 py-1 text-xs outline-none hover:bg-hover hover:text-surface"
                            onSelect={() => rename.start(pg.id, pg.name)}
                          >
                            <IconLucidePencil className="size-3" />
                            <span>{pageMessages.rename}</span>
                          </ContextMenu.Item>
                          <ContextMenu.Item
                            data-test-id="pages-context-delete"
                            disabled={pages.length <= 1}
                            className="flex cursor-pointer items-center gap-2 rounded px-2 py-1 text-xs outline-none hover:bg-hover hover:text-surface data-[disabled]:opacity-50 data-[disabled]:pointer-events-none"
                            onSelect={() => actions.delete(pg.id)}
                          >
                            <IconLucideTrash2 className="size-3" />
                            <span>{pageMessages.delete}</span>
                          </ContextMenu.Item>
                        </ContextMenu.Content>
                      </ContextMenu.Portal>
                    </ContextMenu.Root>
                  )
                })}
              </div>
            </div>
          </div>
        )
      }}
    </PageListRoot>
  )
}

// src/components/PagesPanel.vue
<script setup lang="ts">
import { ref, watch, type ComponentPublicInstance } from 'vue'
import { templateRef } from '@vueuse/core'
import { tv } from 'tailwind-variants'
import {
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuPortal,
  ContextMenuRoot,
  ContextMenuTrigger
} from 'reka-ui'

import type { SceneNode } from '@openweave/scene-graph'
import { PageListRoot, useFlatReorderDrag, useI18n, useInlineRename } from '@openweave/vue'

import Tip from '@/components/ui/Tip.vue'
import { useMenuUI } from '@/components/ui/menu'
import pageListTheme from '@/theme/page-list'

type PageItem = Pick<SceneNode, 'id' | 'name' | 'childIds'>

interface PageActions {
  rename: (pageId: string, name: string) => void
  delete: (pageId: string) => void
  move: (pageId: string, index: number) => void
}

const pageInput = templateRef<HTMLInputElement>('pageInput')
const rename = useInlineRename((id, name) => pageActions.value?.rename(id, name))
const { panels, pages: pageMessages } = useI18n()
const menuCls = useMenuUI({
  content: 'min-w-36 shadow-[0_8px_30px_rgb(0_0_0/0.4)]',
  item: 'justify-start gap-2'
})
const pageListStyles = tv(pageListTheme)
const baseStyles = pageListStyles()

const pageActions = ref<Pick<PageActions, 'rename'> | null>(null)
const currentPages = ref<readonly PageItem[]>([])
const currentMovePage = ref<PageActions['move'] | null>(null)
const pageReorder = useFlatReorderDrag<PageItem>({
  items: () => currentPages.value,
  onMove: (pageId, index) => currentMovePage.value?.(pageId, index)
})

function setPageActions(renamePage: (pageId: string, name: string) => void) {
  pageActions.value = { rename: renamePage }
}

watch(pageInput, (input) => {
  if (input) void rename.focusInput(input)
})

function startRename(pg: PageItem, renamePage: (pageId: string, name: string) => void) {
  setPageActions(renamePage)
  rename.start(pg.id, pg.name)
}

function pageDropPosition(pg: PageItem): 'before' | 'after' | undefined {
  if (pageReorder.instructionTargetId.value !== pg.id) return undefined
  if (pageReorder.instruction.value?.operation === 'reorder-before') return 'before'
  if (pageReorder.instruction.value?.operation === 'reorder-after') return 'after'
  return undefined
}

function pageStyles(pg: PageItem, currentPageId: string) {
  return pageListStyles({
    active: pg.id === currentPageId,
    dragging: pageReorder.draggingId.value === pg.id,
    dropPosition: pageDropPosition(pg)
  })
}

function setupPageRowRef(
  value: Element | ComponentPublicInstance | null,
  pg: PageItem,
  pages: readonly PageItem[],
  movePage: PageActions['move']
) {
  currentPages.value = pages
  currentMovePage.value = movePage
  pageReorder.setupItem(value instanceof HTMLElement ? value : null, () => ({ id: pg.id }))
}
</script>

<template>
  <PageListRoot v-slot="{ pages, currentPageId, isDivider, actions }">
    <div data-test-id="pages-panel" :class="baseStyles.panel()">
      <div :class="baseStyles.header()">
        <span data-test-id="pages-header" :class="baseStyles.title()">{{ panels.pages }}</span>
        <Tip :label="panels.addPage">
          <button data-test-id="pages-add" :class="baseStyles.add()" @click="actions.add()">
            +
          </button>
        </Tip>
      </div>
      <div :class="baseStyles.body()">
        <div data-test-id="pages-scroll" :class="baseStyles.viewport()">
          <ContextMenuRoot v-for="pg in pages" :key="pg.id" :modal="false">
            <ContextMenuTrigger as-child>
              <div
                data-test-id="pages-row"
                :ref="(value) => setupPageRowRef(value, pg, pages, actions.move)"
                :class="pageStyles(pg, currentPageId).row()"
                :data-page-id="pg.id"
                :data-active="pg.id === currentPageId || undefined"
                :data-dragging="pageReorder.draggingId.value === pg.id || undefined"
                :data-drop-position="pageDropPosition(pg)"
              >
                <div
                  v-if="pageDropPosition(pg) === 'before'"
                  data-test-id="pages-drop-indicator"
                  :class="pageStyles(pg, currentPageId).dropIndicator()"
                />
                <div
                  v-if="rename.editingId.value === pg.id"
                  :class="pageStyles(pg, currentPageId).renameRow()"
                >
                  <icon-lucide-file :class="pageStyles(pg, currentPageId).icon()" />
                  <input
                    ref="pageInput"
                    data-test-id="pages-item-input"
                    :class="pageStyles(pg, currentPageId).renameInput()"
                    :value="pg.name"
                    @blur="rename.commit(pg.id, $event)"
                    @keydown.stop="rename.onKeydown"
                  />
                </div>
                <div
                  v-else-if="isDivider(pg)"
                  data-test-id="pages-divider"
                  :class="pageStyles(pg, currentPageId).divider()"
                  @dblclick="startRename(pg, actions.rename)"
                >
                  <div :class="pageStyles(pg, currentPageId).dividerLine()" />
                </div>
                <button
                  v-else
                  data-test-id="pages-item"
                  :class="pageStyles(pg, currentPageId).item()"
                  @click="actions.switch(pg.id)"
                  @dblclick="startRename(pg, actions.rename)"
                >
                  <icon-lucide-file :class="pageStyles(pg, currentPageId).icon()" />
                  <span :class="pageStyles(pg, currentPageId).label()">{{ pg.name }}</span>
                </button>
                <div
                  v-if="pageDropPosition(pg) === 'after'"
                  data-test-id="pages-drop-indicator"
                  :class="pageStyles(pg, currentPageId).dropIndicator()"
                />
              </div>
            </ContextMenuTrigger>
            <ContextMenuPortal>
              <ContextMenuContent :class="menuCls.content" :side-offset="2" align="start">
                <ContextMenuItem
                  data-test-id="pages-context-rename"
                  :class="menuCls.item"
                  @select="startRename(pg, actions.rename)"
                >
                  <icon-lucide-pencil :class="menuCls.icon" />
                  <span>{{ pageMessages.rename }}</span>
                </ContextMenuItem>
                <ContextMenuItem
                  data-test-id="pages-context-delete"
                  :class="menuCls.item"
                  :disabled="pages.length <= 1"
                  @select="actions.delete(pg.id)"
                >
                  <icon-lucide-trash-2 :class="menuCls.icon" />
                  <span>{{ pageMessages.delete }}</span>
                </ContextMenuItem>
              </ContextMenuContent>
            </ContextMenuPortal>
          </ContextMenuRoot>
        </div>
      </div>
    </div>
  </PageListRoot>
</template>
