// src/components/ui/panel/PanelGrid.vue
<script lang="ts">
import type { PropertyGridRootSlots } from '@openweave/vue'
import type { ClassValue } from 'tailwind-variants'

export interface PanelGridProps {
  columns?: 1 | 2 | 3
  distribution?: 'equal' | 'wide-first'
  class?: ClassValue
}

export type PanelGridSlots = PropertyGridRootSlots
</script>

<script setup lang="ts">
import { PropertyGridRoot } from '@openweave/vue'
import { tv } from 'tailwind-variants'

import theme from '@/theme/panel/grid'

const { columns = 1, distribution = 'equal', class: className } = defineProps<PanelGridProps>()
defineSlots<PanelGridSlots>()
const panelGrid = tv(theme)
</script>

<template>
  <PropertyGridRoot
    :columns="columns"
    :distribution="distribution"
    :class="panelGrid({ columns, distribution, class: className })"
  >
    <slot />
    <template v-if="$slots.actions" #actions>
      <slot name="actions" />
    </template>
  </PropertyGridRoot>
</template>

// src/components/ui/panel/PanelGrid.tsx
import React from 'react'
import { tv } from 'tailwind-variants'
import { PropertyGridRoot } from '@openweave/react'

import theme from '@/theme/panel/grid'

export interface PanelGridProps {
  columns?: 1 | 2 | 3
  distribution?: 'equal' | 'wide-first'
  className?: string
  children: React.ReactNode
  actions?: React.ReactNode
}

export default function PanelGrid({
  columns = 1,
  distribution = 'equal',
  className,
  children,
  actions
}: PanelGridProps) {
  const styles = tv(theme)({ columns, distribution, class: className })

  return (
    <PropertyGridRoot
      columns={columns}
      distribution={distribution}
      className={styles}
    >
      {children}
      {actions && (
        <React.Fragment key="actions">
          {actions}
        </React.Fragment>
      )}
    </PropertyGridRoot>
  )
}
