// packages/vue/src/primitives/GradientEditor/GradientEditorBar.vue
<script setup lang="ts">
import { templateRef } from '@vueuse/core'
import { ref } from 'vue'

import type { GradientStop } from '@openweave/scene-graph'

const { stops, ui } = defineProps<{
  stops: GradientStop[]
  activeStopIndex: number
  barBackground: string
  ui?: {
    bar?: string
  }
}>()

const emit = defineEmits<{
  selectStop: [index: number]
  dragStop: [index: number, position: number]
}>()

const barRef = templateRef<HTMLElement>('barRef')
const draggingIndex = ref<number | null>(null)

function stopPointerDown(index: number, e: PointerEvent) {
  emit('selectStop', index)
  draggingIndex.value = index
  barRef.value?.setPointerCapture(e.pointerId)
}

function onPointerMove(e: PointerEvent) {
  const el = barRef.value
  if (!el || draggingIndex.value === null || !el.hasPointerCapture(e.pointerId)) return
  const rect = el.getBoundingClientRect()
  const pos = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width))
  emit('dragStop', draggingIndex.value, pos)
}

function onPointerUp() {
  draggingIndex.value = null
}

const actions = {
  stopPointerDown
}

defineExpose({ barRef })
</script>

<template>
  <div
    ref="barRef"
    :class="ui?.bar"
    :style="{ background: barBackground }"
    @pointermove="onPointerMove"
    @pointerup="onPointerUp"
  >
    <slot
      :stops="stops"
      :active-stop-index="activeStopIndex"
      :bar-background="barBackground"
      :actions="actions"
      :dragging-index="draggingIndex"
    />
  </div>
</template>

// packages/react/src/primitives/gradient-editor/GradientEditorBar.tsx
import React, {
  useRef,
  useState,
  useCallback,
  useImperativeHandle,
  forwardRef,
  type ReactNode
} from 'react'

import type { GradientStop } from '@openweave/scene-graph'

export interface GradientEditorBarProps {
  stops: GradientStop[]
  activeStopIndex: number
  barBackground: string
  ui?: {
    bar?: string
  }
  onSelectStop?: (index: number) => void
  onDragStop?: (index: number, position: number) => void
  children?: ReactNode | ((props: any) => ReactNode)
}

export const GradientEditorBar = forwardRef<HTMLDivElement, GradientEditorBarProps>(
  (
    { stops, activeStopIndex, barBackground, ui, onSelectStop, onDragStop, children },
    forwardedRef
  ) => {
    const barRef = useRef<HTMLDivElement>(null)
    const [draggingIndex, setDraggingIndex] = useState<number | null>(null)

    useImperativeHandle(forwardedRef, () => barRef.current!)

    const stopPointerDown = useCallback(
      (index: number, e: React.PointerEvent) => {
        onSelectStop?.(index)
        setDraggingIndex(index)
        barRef.current?.setPointerCapture(e.pointerId)
      },
      [onSelectStop]
    )

    const onPointerMove = useCallback(
      (e: React.PointerEvent) => {
        const el = barRef.current
        if (!el || draggingIndex === null || !el.hasPointerCapture(e.pointerId)) return
        const rect = el.getBoundingClientRect()
        const pos = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width))
        onDragStop?.(draggingIndex, pos)
      },
      [draggingIndex, onDragStop]
    )

    const onPointerUp = useCallback(() => {
      setDraggingIndex(null)
    }, [])

    const actions = {
      stopPointerDown
    }

    const renderedChildren =
      typeof children === 'function'
        ? children({
            stops,
            activeStopIndex,
            barBackground,
            actions,
            draggingIndex
          })
        : children

    return (
      <div
        ref={barRef}
        className={ui?.bar}
        style={{ background: barBackground }}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
      >
        {renderedChildren}
      </div>
    )
  }
)

GradientEditorBar.displayName = 'GradientEditorBar'
export default GradientEditorBar
