// src/components/layer-tree/LayerTree.tsx
import React, { useRef, useEffect, useCallback } from 'react'
import { tv } from 'tailwind-variants'
import * as ContextMenu from '@radix-ui/react-context-menu'
import {
  ChevronRight,
  Eye,
  EyeOff,
  Lock,
  Unlock
} from 'lucide-react'
import {
  LayerTreeRoot,
  LayerTreeItem,
  useInlineRename,
  type LayerSelectionMode
} from '@openweave/react'
import { useEditorStore } from '@/app/editor/active-store'
import { COMPONENT_TYPES, nodeIcon } from '@/app/editor/icons'
import layerTreeTheme from '@/theme/layer-tree'
import CanvasMenu from '../canvas/CanvasMenu'

const layerTree = tv(layerTreeTheme)
const INDENT = 16

export default function LayerTree() {
  const store = useEditorStore()
  const pageInputRef = useRef<HTMLInputElement>(null)

  const handleRenameCommit = useCallback((id: string, name: string) => {
    store.renameNode(id, name)
  }, [store])

  const rename = useInlineRename(handleRenameCommit)

  useEffect(() => {
    const renameId = store.state.renameNodeId
    if (renameId) {
      const node = store.graph.getNode(renameId)
      store.state.renameNodeId = null
      if (node) rename.start(node.id, node.name)
    }
  }, [store.state.renameNodeId, store.graph, rename])

  useEffect(() => {
    if (rename.editingId && pageInputRef.current) {
      rename.focusInput(pageInputRef.current)
    }
  }, [rename])

  function onLayerContextMenu(_e: React.MouseEvent, nodeId: string) {
    if (!store.state.selectedIds.has(nodeId)) {
      store.select([nodeId])
    }
  }

  function getSelectionMode(e: React.MouseEvent): LayerSelectionMode {
    return {
      additive: e.metaKey || e.ctrlKey,
      range: e.shiftKey
    }
  }

  return (
    <LayerTreeRoot indentPerLevel={INDENT}>
      {({ visibleRows, selectedIds, expanded, draggingId, instruction, instructionTargetId, actions }) => {
        const styles = layerTree()

        return (
          <ContextMenu.Root modal={false}>
            <ContextMenu.Trigger asChild>
              <div
                data-test-id="layers-scroll"
                data-slot="viewport"
                className={styles.viewport()}
                onFocus={() => actions.setFocused(true)}
                onBlur={() => actions.setFocused(false)}
              >
                {visibleRows.map(({ node, level, hasChildren }) => {
                  const isSelected = selectedIds.has(node.id)
                  const isExpanded = expanded.includes(node.id)
                  const isDragging = draggingId === node.id
                  const isEditing = rename.editingId === node.id
                  const isComponent = COMPONENT_TYPES.has(node.type)
                  const isChildDropTarget =
                    instructionTargetId === node.id && instruction?.type === 'make-child'
                  const NodeIconComp = nodeIcon(node)

                  const rowStyles = layerTree({
                    selected: isSelected,
                    dragging: isDragging,
                    visible: node.visible,
                    component: isComponent,
                    childDropTarget: isChildDropTarget
                  })

                  const padLeft = `${(level - 1) * INDENT}px`

                  return (
                    <LayerTreeItem
                      key={node.id}
                      node={node}
                      level={level}
                      hasChildren={hasChildren}
                    >
                      {({ actions: itemActions }) => (
                        <div
                          data-test-id="layers-item"
                          data-slot="row"
                          data-node-id={node.id}
                          data-selected={isSelected || undefined}
                          data-dragging={isDragging || undefined}
                          data-hidden={!node.visible || undefined}
                          className={rowStyles.row()}
                          style={{ paddingLeft: padLeft }}
                          onClick={(e) => itemActions.select(getSelectionMode(e).additive)}
                          onContextMenu={(e) => onLayerContextMenu(e, node.id)}
                          onDoubleClick={() => rename.start(node.id, node.name)}
                        >
                          {hasChildren ? (
                            <button
                              type="button"
                              className={`${rowStyles.disclosure()} ${isExpanded ? 'rotate-90' : ''}`}
                              onClick={(e) => {
                                e.stopPropagation()
                                itemActions.toggleExpand()
                              }}
                            >
                              <ChevronRight className="size-3" />
                            </button>
                          ) : (
                            <div className={rowStyles.disclosurePlaceholder()} />
                          )}

                          <NodeIconComp className={rowStyles.icon()} />

                          {isEditing ? (
                            <input
                              ref={pageInputRef}
                              data-test-id="layers-rename-input"
                              className={rowStyles.renameInput()}
                              defaultValue={node.name}
                              onBlur={(e) => {
                                itemActions.rename(e.target.value.trim() || node.name)
                                rename.commit(node.id, e)
                              }}
                              onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                  itemActions.rename(e.currentTarget.value.trim() || node.name)
                                  rename.commit(node.id, e)
                                } else if (e.key === 'Escape') {
                                  rename.cancel()
                                }
                              }}
                            />
                          ) : (
                            <span data-slot="label" className={rowStyles.label()}>
                              {node.name}
                            </span>
                          )}

                          <div className={rowStyles.actions()}>
                            <button
                              type="button"
                              title={node.locked ? 'Unlock' : 'Lock'}
                              className={rowStyles.action()}
                              onClick={(e) => {
                                e.stopPropagation()
                                itemActions.toggleLock()
                              }}
                            >
                              {node.locked ? (
                                <Lock className={rowStyles.actionIcon()} />
                              ) : (
                                <Unlock className={`${rowStyles.actionIcon()} opacity-0 group-hover/row:opacity-50`} />
                              )}
                            </button>

                            <button
                              type="button"
                              title={node.visible ? 'Hide' : 'Show'}
                              className={rowStyles.action()}
                              onClick={(e) => {
                                e.stopPropagation()
                                itemActions.toggleVisibility()
                              }}
                            >
                              {node.visible ? (
                                <Eye className={`${rowStyles.actionIcon()} opacity-0 group-hover/row:opacity-50`} />
                              ) : (
                                <EyeOff className={rowStyles.actionIcon()} />
                              )}
                            </button>
                          </div>
                        </div>
                      )}
                    </LayerTreeItem>
                  )
                })}
              </div>
            </ContextMenu.Trigger>

            <ContextMenu.Portal>
              <CanvasMenu />
            </ContextMenu.Portal>
          </ContextMenu.Root>
        )
      }}
    </LayerTreeRoot>
  )
}

// src/components/LayerTree/LayerTree.vue
<script setup lang="ts">
import { useAttrs, watch } from 'vue'
import { tv } from 'tailwind-variants'
import {
  TreeItem,
  TreeVirtualizer,
  ContextMenuRoot,
  ContextMenuTrigger,
  ContextMenuPortal
} from 'reka-ui'

import { LayerTreeRoot, LayerTreeItem, useInlineRename } from '@openweave/vue'
import type {
  LayerDragInstruction,
  LayerNode,
  LayerSelectionMode,
  LayerTreeVirtualizer
} from '@openweave/vue'
import { useEditorStore } from '@/app/editor/active-store'
import CanvasMenu from '../canvas/CanvasMenu.vue'
import LayerTreeNodeRow from './LayerTreeNodeRow.vue'
import LayerTreeRenameRow from './LayerTreeRenameRow.vue'
import { provideLayerTreeUI } from './ui'

import layerTreeTheme from '@/theme/layer-tree'

import type { LayerTreeUI } from './ui'

interface LayerTreeRootActions {
  select: (id: string, selection: boolean | LayerSelectionMode) => void
  toggleExpand: (id: string) => void
  setFocused: (focused: boolean) => void
  setVirtualizer: (virtualizer: LayerTreeVirtualizer) => void
}

interface LayerTreeSlotScope {
  actions: LayerTreeRootActions
  draggingId: string | null
  instruction: LayerDragInstruction | null
  instructionTargetId: string | null
  focused: boolean
}

defineOptions({ inheritAttrs: false })

const { ui } = defineProps<{ ui?: LayerTreeUI }>()

const INDENT = 16
const attrs = useAttrs()
const styles = tv(layerTreeTheme)()
provideLayerTreeUI(() => ui)
const store = useEditorStore()
const rename = useInlineRename((id, name) => store.renameNode(id, name))
const renameControls = {
  commit: rename.commit,
  onKeydown: rename.onKeydown,
  focusInput: rename.focusInput
}

watch(
  () => store.state.renameNodeId,
  (id) => {
    if (!id) return
    const node = store.graph.getNode(id)
    store.state.renameNodeId = null
    if (node) rename.start(node.id, node.name)
  },
  { immediate: true }
)

function onLayerRightClick(e: MouseEvent) {
  const row = (e.target as HTMLElement).closest<HTMLElement>('[data-node-id]')
  if (!row?.dataset.nodeId) return
  if (!store.state.selectedIds.has(row.dataset.nodeId)) store.select([row.dataset.nodeId])
}

function layerSelectionMode(e: CustomEvent): LayerSelectionMode {
  const mouseEvent = e.detail?.originalEvent as MouseEvent | undefined
  return {
    additive: !!(mouseEvent?.metaKey || mouseEvent?.ctrlKey),
    range: !!mouseEvent?.shiftKey
  }
}

function onTreeSelect(
  e: CustomEvent,
  id: string,
  select: (id: string, selection: boolean | LayerSelectionMode) => void
) {
  e.preventDefault()
  select(id, layerSelectionMode(e))
}

function isLayerNode(value: unknown): value is LayerNode {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value &&
    'name' in value &&
    'type' in value &&
    'layoutMode' in value &&
    'visible' in value &&
    'locked' in value &&
    typeof value.id === 'string' &&
    typeof value.name === 'string' &&
    typeof value.type === 'string' &&
    typeof value.layoutMode === 'string' &&
    typeof value.visible === 'boolean' &&
    typeof value.locked === 'boolean'
  )
}

function toLayerNode(value: unknown): LayerNode {
  if (isLayerNode(value)) return value
  throw new Error('[openweave] Invalid layer tree item')
}

function layerTextContent(value: unknown): string {
  return toLayerNode(value).name
}

function chrome(scope: Omit<LayerTreeSlotScope, 'actions'>) {
  return {
    draggingId: scope.draggingId,
    instruction: scope.instruction,
    instructionTargetId: scope.instructionTargetId,
    focused: scope.focused,
    indent: INDENT
  }
}

function registerVirtualizer(
  actions: LayerTreeRootActions,
  virtualizer: LayerTreeVirtualizer
): boolean {
  actions.setVirtualizer(virtualizer)
  return true
}

function onFocusOut(event: FocusEvent, actions: LayerTreeRootActions) {
  const next = event.relatedTarget
  if (
    next instanceof Node &&
    event.currentTarget instanceof Node &&
    event.currentTarget.contains(next)
  ) {
    return
  }
  actions.setFocused(false)
}
</script>

<template>
  <LayerTreeRoot v-slot="scope" :indent-per-level="INDENT">
    <ContextMenuRoot :modal="false">
      <div
        v-bind="attrs"
        class="relative min-h-0 flex-1 overflow-hidden"
        @focusin="scope.actions.setFocused(true)"
        @focusout="onFocusOut($event, scope.actions)"
      >
        <ContextMenuTrigger as-child @contextmenu="onLayerRightClick">
          <div
            data-test-id="layers-scroll"
            data-slot="viewport"
            :class="styles.viewport({ class: ui?.viewport })"
          >
            <TreeVirtualizer
              v-slot="{ item, virtualizer }"
              :estimate-size="24"
              :text-content="layerTextContent"
            >
              <template v-if="registerVirtualizer(scope.actions, virtualizer)">
                <TreeItem
                  v-slot="{ isExpanded }"
                  v-bind="item.bind"
                  as-child
                  @select="
                    (e: CustomEvent) =>
                      onTreeSelect(e, toLayerNode(item.value).id, scope.actions.select)
                  "
                  @toggle="
                    (e: CustomEvent) => {
                      if (e.detail.originalEvent?.type === 'click') e.preventDefault()
                    }
                  "
                >
                  <LayerTreeItem
                    v-slot="{ node, isSelected, padLeft, actions }"
                    :node="toLayerNode(item.value)"
                    :level="item.level"
                    :has-children="item.hasChildren"
                  >
                    <LayerTreeRenameRow
                      v-if="rename.editingId.value === node.id"
                      :node="node"
                      :has-children="item.hasChildren"
                      :pad-left="padLeft"
                      :expanded="isExpanded"
                      :actions="actions"
                      :rename-controls="renameControls"
                    />

                    <LayerTreeNodeRow
                      v-else
                      :node="node"
                      :level="item.level"
                      :has-children="item.hasChildren"
                      :selected="isSelected"
                      :pad-left="padLeft"
                      :expanded="isExpanded"
                      :actions="actions"
                      :chrome="chrome(scope)"
                      @rename-start="rename.start"
                    />
                  </LayerTreeItem>
                </TreeItem>
              </template>
            </TreeVirtualizer>
          </div>
        </ContextMenuTrigger>
      </div>
      <ContextMenuPortal>
        <CanvasMenu />
      </ContextMenuPortal>
    </ContextMenuRoot>
  </LayerTreeRoot>
</template>
