// src/components/ui/FillSwatch.vue
<script lang="ts">
import type { VNode } from 'vue'

import type { Fill } from '@openweave/scene-graph'
import type { FillSwatchSlotProps } from '@openweave/vue'
import type { ComponentUI } from '@/components/ui/types'
import type theme from '@/theme/fill-swatch'

export type FillSwatchUI = ComponentUI<typeof theme>

export interface FillSwatchProps {
  fill: Fill
  label?: string
  ui?: FillSwatchUI
}

export interface FillSwatchSlots {
  default?(props: FillSwatchSlotProps): VNode[]
}
</script>

<script setup lang="ts">
import { computed, normalizeClass, useAttrs } from 'vue'
import { tv } from 'tailwind-variants'
import { FillSwatch as FillSwatchPrimitive } from '@openweave/vue'

import fillSwatchTheme from '@/theme/fill-swatch'

const { fill, label, ui } = defineProps<FillSwatchProps>()
const attrs = useAttrs()
const styles = computed(() => tv(fillSwatchTheme)())
const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs
  return rest
})
defineSlots<FillSwatchSlots>()
defineOptions({ inheritAttrs: false })
</script>

<template>
  <FillSwatchPrimitive
    v-slot="swatch"
    v-bind="forwardedAttrs"
    :fill="fill"
    :label="label"
    :class="styles.root({ class: [ui?.root, normalizeClass(attrs.class)] })"
  >
    <slot v-bind="swatch">
      <span
        :class="styles.preview({ class: ui?.preview })"
        :style="{ background: swatch.background }"
      />
    </slot>
  </FillSwatchPrimitive>
</template>

// src/components/ui/FillSwatch.tsx
import React, { forwardRef } from 'react'
import type { HTMLAttributes, ReactNode } from 'react'
import { tv } from 'tailwind-variants'
import { FillSwatch as FillSwatchPrimitive } from '@openweave/react'
import type { Fill } from '@openweave/scene-graph'

import fillSwatchTheme from '@/theme/fill-swatch'
import type { ComponentUI } from '@/components/ui/types'

const styles = tv(fillSwatchTheme)()

export type FillSwatchUI = ComponentUI<typeof fillSwatchTheme>

export interface FillSwatchProps extends Omit<HTMLAttributes<HTMLButtonElement>, 'children'> {
  fill: Fill
  label?: string
  ui?: FillSwatchUI
  children?: ReactNode | ((props: { background?: string }) => ReactNode)
}

export const FillSwatch = forwardRef<HTMLButtonElement, FillSwatchProps>(
  ({ fill, label, ui, className, children, ...props }, ref) => {
    return (
      <FillSwatchPrimitive
        ref={ref}
        fill={fill}
        label={label}
        className={styles.root({ className: [ui?.root, className] })}
        {...props}
      >
        {(swatchProps: unknown) => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const props = swatchProps as any
          if (typeof children === 'function') {
            return children(props)
          }
          if (children) {
            return children
          }
          return (
            <span
              className={styles.preview({ className: ui?.preview })}
              style={{ background: props.background }}
            />
          )
        }}
      </FillSwatchPrimitive>
    )
  }
)
FillSwatch.displayName = 'FillSwatch'
