// packages/react/src/primitives/fill/FillSwatch.tsx
import { useBindingProvider } from '#react/controls/binding-provider'
import { Slot } from '@radix-ui/react-slot'
import React, { useMemo, forwardRef } from 'react'

import type { FillSwatchProps } from './types'
import { useFill } from './useFill'

const noop = () => undefined

export const FillSwatch = forwardRef<HTMLElement, FillSwatchProps>(
  ({ fill, label, as: Component = 'button', asChild = false, children, ...props }, ref) => {
    const provider = useBindingProvider()
    const { category, swatchBackground, transparent } = useFill(fill, noop)

    const boundVariables = (fill as unknown as { boundVariables?: { color?: { id: string } } })
      .boundVariables
    const variableId = fill.type === 'SOLID' ? boundVariables?.color?.id : undefined
    const boundVar = variableId && provider ? provider.resolve(variableId) : undefined

    const state = useMemo(() => {
      const bindingState = boundVar ? 'bound' : 'unbound'
      return {
        bindingState,
        stateAttrs: {
          'data-bound': boundVar ? ('' as const) : undefined,
          'data-binding-state': bindingState,
          'data-policy': 'detach-on-edit' as const
        }
      }
    }, [boundVar])

    const Comp = asChild ? Slot : Component

    const renderedChildren =
      typeof children === 'function'
        ? children({
            fill,
            color: fill.color,
            category,
            background: swatchBackground,
            transparent,
            bindingState: state.bindingState as any,
            stateAttrs: state.stateAttrs
          })
        : children

    return (
      <Comp
        ref={ref}
        aria-label={label ?? 'Color swatch'}
        title={label}
        {...state.stateAttrs}
        {...props}
      >
        {renderedChildren}
      </Comp>
    )
  }
)
FillSwatch.displayName = 'FillSwatch'

export default FillSwatch

// packages/vue/src/primitives/Fill/FillSwatch.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Primitive } from 'reka-ui'

import { useOptionalBindableValue } from '#vue/primitives/BindableValue/context'
import type { FillSwatchProps, FillSwatchSlots } from './types'
import { fillCategory, fillIsTransparent, fillSwatchBackground } from './useFill'

import type { Color } from '@openweave/scene-graph/primitives'

const { fill, label, as = 'span', asChild = false } = defineProps<FillSwatchProps>()
defineSlots<FillSwatchSlots>()
defineOptions({ inheritAttrs: false })

const binding = useOptionalBindableValue<Color>()
const bindingState = computed(() => binding?.state.value)
const boundColor = computed(() =>
  bindingState.value === 'bound' ? binding?.resolvedValue.value : undefined
)
const effectiveFill = computed(() =>
  fill.type === 'SOLID' && boundColor.value ? { ...fill, color: boundColor.value } : fill
)
const category = computed(() => fillCategory(effectiveFill.value))
const background = computed(() => fillSwatchBackground(effectiveFill.value))
const transparent = computed(() => fillIsTransparent(effectiveFill.value))
const accessibleLabel = computed(() => label ?? `${category.value.toLowerCase()} fill`)
const stateAttrs = computed(() => binding?.stateAttrs.value)
const slotProps = computed(() => ({
  fill: effectiveFill.value,
  color: effectiveFill.value.color,
  category: category.value,
  background: background.value,
  transparent: transparent.value,
  bindingState: bindingState.value,
  stateAttrs: stateAttrs.value
}))
</script>

<template>
  <Primitive
    v-bind="{ ...$attrs, ...stateAttrs }"
    :as="as"
    :as-child="asChild"
    :aria-label="accessibleLabel"
    :data-fill-type="effectiveFill.type"
    :data-fill-category="category"
    :data-transparent="transparent ? '' : undefined"
    :style="{ '--openweave-fill-swatch-background': background }"
    role="img"
    aria-roledescription="fill swatch"
    data-slot="swatch"
  >
    <slot v-bind="slotProps" />
  </Primitive>
</template>
