// packages/react/src/primitives/fill/FillRoot.tsx
import React from 'react'

import type { Fill } from '@openweave/scene-graph'

import type { FillRootSlotProps } from './types'
import { useFill } from './useFill'

export interface FillRootProps {
  fill: Fill
  onUpdate: (fill: Fill) => void
  children?: React.ReactNode | ((props: FillRootSlotProps) => React.ReactNode)
}

export function FillRoot({ fill, onUpdate, children }: FillRootProps) {
  const { category, swatchBackground, transparent, actions } = useFill(fill, onUpdate)

  const renderedChildren =
    typeof children === 'function'
      ? children({
          fill,
          category,
          swatchBackground,
          transparent,
          actions
        })
      : children

  return <>{renderedChildren}</>
}

export default FillRoot

// packages/vue/src/primitives/Fill/FillRoot.vue
<script setup lang="ts">
import { computed } from 'vue'

import type { FillRootSlots } from './types'
import { useFill } from './useFill'

import type { Fill } from '@openweave/scene-graph'

const { fill } = defineProps<{ fill: Fill }>()
const emit = defineEmits<{ update: [fill: Fill] }>()
defineSlots<FillRootSlots>()

const model = useFill(
  computed(() => fill),
  (updated) => emit('update', updated)
)
</script>

<template>
  <slot
    :fill="fill"
    :category="model.category.value"
    :swatch-background="model.swatchBackground.value"
    :transparent="model.transparent.value"
    :actions="model.actions"
  />
</template>
